"""
iOS Application Hooking & Dynamic Analysis Plugin

Generates tasks for iOS application pentesting including:
- Objection framework usage and Frida integration
- Class/method enumeration and hooking
- Runtime manipulation and return value overriding
- Non-jailbreak testing techniques (get-task-allow entitlement)
- IPA decryption and re-signing workflows
- Modern iOS 16+ Developer Mode configuration
- MobSF integration for automated analysis
- Manual alternatives for OSCP-style methodology

Extracted from HackTricks:
- mobile-pentesting/ios-pentesting/ios-hooking-with-objection.md
- mobile-pentesting/ios-pentesting/ios-pentesting-without-jailbreak.md

Generated by: CrackPot v1.0

Note: This plugin focuses on iOS application security testing,
not network port scanning. It's designed for manual invocation
when iOS app pentesting targets are identified.
"""

from typing import Dict, Any, List
from .base import ServicePlugin
from .registry import ServiceRegistry


@ServiceRegistry.register
class iOSHookingPlugin(ServicePlugin):
    """iOS application hooking and dynamic analysis plugin"""

    @property
    def name(self) -> str:
        return "ios-hooking"

    @property
    def default_ports(self) -> List[int]:
        return []  # Not port-based; app-level testing

    @property
    def service_names(self) -> List[str]:
        return ['ios-app', 'ios-hooking', 'mobile-app', 'frida', 'objection']

    def detect(self, port_info: Dict[str, Any], profile: 'TargetProfile') -> bool:
        """
        Detect iOS application testing context

        This plugin does not auto-detect from network scans.
        It's designed for manual invocation during iOS app pentesting.

        Usage:
            crack track finding <target> --type ios-app --source "Manual selection"
        """
        # Check if port_info indicates iOS testing context
        service = port_info.get('service', '').lower()
        product = port_info.get('product', '').lower()

        # Detect Frida server or iOS-specific services
        return (
            'frida' in service or
            'ios' in service or
            'objection' in service or
            'ios' in product
        )

    def get_task_tree(self, target: str, port: int, service_info: Dict[str, Any]) -> Dict[str, Any]:
        """
        Generate iOS app pentesting task tree

        Args:
            target: iOS device IP, app bundle ID, or app name
            port: Not applicable (use 0 as placeholder)
            service_info: Contains app details, version, etc.

        Returns:
            Comprehensive task tree for iOS app security testing
        """
        app_name = service_info.get('product', target)
        app_version = service_info.get('version', 'unknown')

        return {
            'id': f'ios-hooking-{target.replace(".", "-")}',
            'name': f'iOS App Security Testing: {app_name}',
            'type': 'parent',
            'children': [
                self._create_setup_phase(target, app_name),
                self._create_enumeration_phase(target, app_name),
                self._create_hooking_phase(target, app_name),
                self._create_bypass_phase(target, app_name),
                self._create_non_jailbreak_phase(target, app_name),
                self._create_automation_phase(target, app_name, app_version)
            ]
        }

    def _create_setup_phase(self, target: str, app_name: str) -> Dict[str, Any]:
        """Phase 1: Setup Frida/Objection environment"""
        return {
            'id': f'ios-setup-{target.replace(".", "-")}',
            'name': 'Phase 1: Setup Testing Environment',
            'type': 'parent',
            'children': [
                {
                    'id': f'ios-frida-ps-{target.replace(".", "-")}',
                    'name': 'List Running iOS Processes',
                    'type': 'command',
                    'metadata': {
                        'command': 'frida-ps -Uia',
                        'description': 'List all running processes on connected iOS device to identify target app',
                        'flag_explanations': {
                            'frida-ps': 'Frida process enumeration tool',
                            '-U': 'Connect to USB device (iOS device via USB)',
                            '-i': 'List installed applications (not just processes)',
                            '-a': 'Show application identifiers/bundle IDs'
                        },
                        'success_indicators': [
                            'List of running apps with bundle IDs displayed',
                            'Target app appears in list',
                            'Device connection successful'
                        ],
                        'failure_indicators': [
                            'Failed to enumerate processes (frida-server not running)',
                            'Device not detected (USB connection issue)',
                            'Permission denied (Developer Mode not enabled on iOS 16+)'
                        ],
                        'next_steps': [
                            'Identify target app bundle ID from list',
                            'Note exact bundle ID for objection (e.g., com.example.app)',
                            'Verify frida-server is running on device',
                            'If iOS 16+: Enable Developer Mode in Settings'
                        ],
                        'alternatives': [
                            'Manual: Settings → General → About → Applications (view installed apps)',
                            'ideviceinstaller -l (list installed apps via libimobiledevice)',
                            'iOS device logs: Console.app on macOS',
                            'Xcode → Devices and Simulators → View installed apps'
                        ],
                        'tags': ['QUICK_WIN', 'OSCP:HIGH', 'ENUM', 'MANUAL'],
                        'estimated_time': '1-2 minutes',
                        'notes': 'iOS 16+ requires Developer Mode enabled. Navigate to Settings → Privacy & Security → Developer Mode and toggle on.'
                    }
                },
                {
                    'id': f'ios-objection-connect-{target.replace(".", "-")}',
                    'name': f'Connect Objection to {app_name}',
                    'type': 'command',
                    'metadata': {
                        'command': f'objection -d --gadget "{app_name}" explore',
                        'description': 'Start Objection interactive session attached to target iOS app',
                        'flag_explanations': {
                            'objection': 'Runtime mobile exploration toolkit powered by Frida',
                            '-d': 'Enable debug mode (verbose output for troubleshooting)',
                            '--gadget': 'Specify target app by bundle ID or display name',
                            'explore': 'Start interactive REPL shell for runtime manipulation'
                        },
                        'success_indicators': [
                            'Objection REPL prompt appears',
                            'Successfully attached to process',
                            'App launches and remains running'
                        ],
                        'failure_indicators': [
                            'Application not found (wrong bundle ID)',
                            'Failed to spawn process (FairPlay protection)',
                            'Connection timeout (frida-server crashed)',
                            'App crashes immediately (anti-debugging detected)'
                        ],
                        'next_steps': [
                            'Verify connection: Run "env" to list app paths',
                            'Start enumeration: Use ios hooking commands',
                            'If connection fails: Check frida-server version compatibility',
                            'Document session for OSCP writeup'
                        ],
                        'alternatives': [
                            'objection -d --gadget "com.example.bundleid" explore (use full bundle ID)',
                            'frida -U -f com.example.app -l script.js --no-pause (raw Frida)',
                            'frida -U -n "App Name" -l script.js (attach by process name)',
                            'objection patchipa --source app.ipa --gadget-version 16.0.0 (embed Frida)',
                            'Manual: iOS Console logs + LLDB debugging'
                        ],
                        'tags': ['OSCP:HIGH', 'MANUAL', 'QUICK_WIN'],
                        'estimated_time': '2-3 minutes',
                        'notes': 'For jailbroken devices: Use exact bundle ID. For non-jailbreak: App must be re-signed with get-task-allow entitlement (see Phase 5).'
                    }
                },
                {
                    'id': f'ios-verify-connection-{target.replace(".", "-")}',
                    'name': 'Verify Objection Session',
                    'type': 'manual',
                    'metadata': {
                        'description': 'Verify Objection session is active and functional',
                        'alternatives': [
                            'In Objection REPL: Run "env" to display app paths',
                            'Expected output: BundlePath, DocumentDirectory, LibraryDirectory',
                            'Run "ios info binary" to display binary information',
                            'If no output: Session failed, restart objection'
                        ],
                        'success_indicators': [
                            'env command returns app directory paths',
                            'Commands execute without errors',
                            'App remains responsive'
                        ],
                        'failure_indicators': [
                            'Commands timeout',
                            'App crashes',
                            'No output from env command'
                        ],
                        'next_steps': [
                            'Proceed to enumeration phase',
                            'Document session setup in enumeration.md',
                            'Take screenshots of successful connection'
                        ],
                        'tags': ['MANUAL', 'OSCP:HIGH', 'QUICK_WIN'],
                        'estimated_time': '1 minute'
                    }
                }
            ]
        }

    def _create_enumeration_phase(self, target: str, app_name: str) -> Dict[str, Any]:
        """Phase 2: Application enumeration"""
        return {
            'id': f'ios-enum-{target.replace(".", "-")}',
            'name': 'Phase 2: Application Enumeration',
            'type': 'parent',
            'children': [
                {
                    'id': f'ios-app-paths-{target.replace(".", "-")}',
                    'name': 'Enumerate App File Paths',
                    'type': 'command',
                    'metadata': {
                        'command': 'env',
                        'description': 'Display iOS app sandbox paths (documents, cache, library directories)',
                        'flag_explanations': {
                            'env': 'Objection command to display environment paths (not Unix env)'
                        },
                        'success_indicators': [
                            'BundlePath displayed (app binary location)',
                            'DocumentDirectory displayed (app user data)',
                            'CachesDirectory displayed (temporary files)',
                            'LibraryDirectory displayed (preferences, databases)'
                        ],
                        'failure_indicators': [
                            'No output (objection session disconnected)',
                            'Permission denied (sandbox violation)'
                        ],
                        'next_steps': [
                            'Navigate to DocumentDirectory to find user data',
                            'Check CachesDirectory for sensitive cached data',
                            'Review LibraryDirectory for SQLite databases and plists',
                            'Document paths in enumeration.md with source'
                        ],
                        'alternatives': [
                            'Manual: Open app with Xcode debugger, view file system',
                            'ideviceinstaller info <bundle-id> (view app info)',
                            'iFunBox / iMazing (GUI file browser for jailbroken devices)',
                            'SSH to device (jailbroken): cd /var/mobile/Containers/Data/Application/'
                        ],
                        'tags': ['QUICK_WIN', 'OSCP:HIGH', 'ENUM', 'MANUAL'],
                        'estimated_time': '30 seconds',
                        'notes': 'Document exact paths for OSCP report. These paths contain sensitive data like local databases, cached credentials, and user files.'
                    }
                },
                {
                    'id': f'ios-list-bundles-{target.replace(".", "-")}',
                    'name': 'List Application Bundles',
                    'type': 'command',
                    'metadata': {
                        'command': 'ios bundles list_bundles',
                        'description': 'List all bundles loaded by the application (main app and dependencies)',
                        'flag_explanations': {
                            'ios bundles list_bundles': 'Objection command to enumerate loaded bundles/frameworks'
                        },
                        'success_indicators': [
                            'Main app bundle displayed with version',
                            'System frameworks listed',
                            'Third-party frameworks identified'
                        ],
                        'failure_indicators': [
                            'Empty list (app not fully loaded)',
                            'Command not recognized (objection version mismatch)'
                        ],
                        'next_steps': [
                            'Identify third-party frameworks for vulnerability research',
                            'Check framework versions against CVE databases',
                            'Look for outdated libraries (security risks)',
                            'Document bundle versions for exploit research'
                        ],
                        'alternatives': [
                            'Manual: Unzip IPA, review Frameworks directory',
                            'otool -L <binary> (list linked libraries on macOS)',
                            'strings <binary> | grep -i framework',
                            'class-dump framework binaries to find methods'
                        ],
                        'tags': ['OSCP:MEDIUM', 'ENUM', 'RESEARCH'],
                        'estimated_time': '2 minutes',
                        'notes': 'Focus on third-party frameworks (React Native, Firebase, analytics SDKs). These often have known vulnerabilities.'
                    }
                },
                {
                    'id': f'ios-list-frameworks-{target.replace(".", "-")}',
                    'name': 'List External Frameworks',
                    'type': 'command',
                    'metadata': {
                        'command': 'ios bundles list_frameworks',
                        'description': 'Enumerate external frameworks used by app (React Native, Cordova, third-party SDKs)',
                        'flag_explanations': {
                            'ios bundles list_frameworks': 'Lists non-system frameworks embedded in app bundle'
                        },
                        'success_indicators': [
                            'External frameworks listed with versions',
                            'Popular frameworks identified (React, Firebase, etc.)',
                            'CocoaPods dependencies shown'
                        ],
                        'failure_indicators': [
                            'No external frameworks (pure native app)',
                            'Command fails (objection compatibility)'
                        ],
                        'next_steps': [
                            'Research framework versions: searchsploit <framework> <version>',
                            'Check for outdated libraries (CVE lookup)',
                            'Test framework-specific vulnerabilities',
                            'Document all framework versions with sources'
                        ],
                        'alternatives': [
                            'Manual: Unzip IPA, inspect Podfile.lock for versions',
                            'strings <binary> | grep -i "org.cocoapods"',
                            'class-dump frameworks to enumerate classes/methods',
                            'Check package.json for React Native dependencies'
                        ],
                        'tags': ['OSCP:MEDIUM', 'ENUM', 'RESEARCH'],
                        'estimated_time': '3 minutes',
                        'notes': 'React Native apps often have JavaScript vulnerabilities. Firebase SDK misconfigurations are common.'
                    }
                },
                {
                    'id': f'ios-list-modules-{target.replace(".", "-")}',
                    'name': 'List Loaded Memory Modules',
                    'type': 'command',
                    'metadata': {
                        'command': 'memory list modules',
                        'description': 'Display all loaded modules in app memory (libraries, frameworks, dylibs)',
                        'flag_explanations': {
                            'memory list modules': 'Objection command to show loaded modules with base addresses and sizes'
                        },
                        'success_indicators': [
                            'Module list displayed with base addresses',
                            'Sizes shown (indicates module complexity)',
                            'System and custom dylibs identified'
                        ],
                        'failure_indicators': [
                            'Memory access denied (anti-debugging)',
                            'Empty list (app crashed or session lost)'
                        ],
                        'next_steps': [
                            'Identify custom dylibs for reverse engineering',
                            'Note base addresses for memory manipulation',
                            'Look for suspicious modules (obfuscated names)',
                            'Export modules for offline analysis'
                        ],
                        'alternatives': [
                            'Manual: LLDB debugger → image list',
                            'vmmap <pid> (display memory map on macOS)',
                            'Hopper Disassembler → Load Address analysis',
                            'Frida script: Process.enumerateModules().forEach(m => console.log(m.name))'
                        ],
                        'tags': ['OSCP:MEDIUM', 'ENUM', 'ADVANCED'],
                        'estimated_time': '2 minutes',
                        'notes': 'Large modules may contain significant logic. Small custom dylibs often contain sensitive operations.'
                    }
                },
                {
                    'id': f'ios-list-classes-{target.replace(".", "-")}',
                    'name': 'List Application Classes',
                    'type': 'command',
                    'metadata': {
                        'command': 'ios hooking list classes',
                        'description': 'Enumerate all Objective-C/Swift classes loaded by app',
                        'flag_explanations': {
                            'ios hooking list classes': 'Objection command to dump all class names from app runtime'
                        },
                        'success_indicators': [
                            'Large list of classes displayed',
                            'App-specific classes visible (com.company.app.*)',
                            'System classes included (UIKit, Foundation)'
                        ],
                        'failure_indicators': [
                            'Timeout (too many classes)',
                            'Empty list (Swift stripped app)',
                            'Crash (memory exhaustion)'
                        ],
                        'next_steps': [
                            'Filter for app-specific classes: ios hooking search classes <app-name>',
                            'Look for authentication classes (Login, Auth, JWT, Token)',
                            'Identify data storage classes (Database, Cache, Keychain)',
                            'Find API communication classes (APIClient, NetworkManager)'
                        ],
                        'alternatives': [
                            'ios hooking search classes <search-term> (filter results)',
                            'class-dump <binary> (offline static analysis)',
                            'Hopper Disassembler → Classes view',
                            'Manual: Frida script with ObjC.classes enumeration'
                        ],
                        'tags': ['OSCP:HIGH', 'ENUM'],
                        'estimated_time': '5 minutes (large output)',
                        'notes': 'Output can be huge (1000+ classes). Use search command instead to filter. Focus on app-specific classes, not system classes.'
                    }
                },
                {
                    'id': f'ios-search-classes-{target.replace(".", "-")}',
                    'name': f'Search for {app_name} Classes',
                    'type': 'command',
                    'metadata': {
                        'command': f'ios hooking search classes {app_name.split()[0]}',
                        'description': f'Search for classes containing "{app_name.split()[0]}" (app-specific classes)',
                        'flag_explanations': {
                            'ios hooking search classes': 'Filter class list by search term',
                            app_name.split()[0]: 'Search term (app name or bundle ID fragment)'
                        },
                        'success_indicators': [
                            'App-specific classes found (e.g., iGoat_Swift.*)',
                            'ViewController classes listed',
                            'Data model classes shown'
                        ],
                        'failure_indicators': [
                            'No results (app is pure Swift, no Objective-C runtime)',
                            'Wrong search term (try bundle ID or app name)'
                        ],
                        'next_steps': [
                            'Identify interesting classes for hooking',
                            'List methods: ios hooking list class_methods <class-name>',
                            'Target authentication/authorization classes first',
                            'Document class hierarchy for report'
                        ],
                        'alternatives': [
                            'Try different search terms: bundle ID, company name',
                            'Search for specific functionality: ios hooking search classes Login',
                            'Search for sensitive data: ios hooking search classes Password',
                            'Search for crypto: ios hooking search classes Crypt'
                        ],
                        'tags': ['QUICK_WIN', 'OSCP:HIGH', 'ENUM'],
                        'estimated_time': '1-2 minutes',
                        'notes': 'Good search terms: Login, Auth, API, Database, Keychain, Token, User, Admin, Payment, Credit'
                    }
                },
                {
                    'id': f'ios-list-class-methods-{target.replace(".", "-")}',
                    'name': 'List Methods of Target Class',
                    'type': 'manual',
                    'metadata': {
                        'description': 'Enumerate methods of a specific class to identify hookable targets',
                        'alternatives': [
                            'ios hooking list class_methods <class-name>',
                            'Example: ios hooking list class_methods iGoat_Swift.LoginViewController',
                            'Look for methods like: login, authenticate, verify, validate',
                            'Instance methods start with "-", class methods with "+"',
                            'Document interesting methods for hooking in next phase'
                        ],
                        'success_indicators': [
                            'Method list displayed',
                            'Method signatures shown (parameters, return types)',
                            'Interesting methods identified (login, verify, etc.)'
                        ],
                        'failure_indicators': [
                            'Class not found (wrong name or not loaded)',
                            'No methods (empty class or pure data struct)'
                        ],
                        'next_steps': [
                            'Select high-value methods for hooking',
                            'Methods with "verify", "check", "validate" are prime bypass targets',
                            'Methods with "password", "token", "api" may leak credentials',
                            'Proceed to hooking phase'
                        ],
                        'tags': ['MANUAL', 'OSCP:HIGH', 'ENUM'],
                        'estimated_time': '2-3 minutes per class',
                        'notes': 'Focus on: authentication methods, verification methods, network request methods, data storage methods'
                    }
                },
                {
                    'id': f'ios-search-methods-{target.replace(".", "-")}',
                    'name': 'Search for Specific Methods',
                    'type': 'manual',
                    'metadata': {
                        'description': 'Search for methods across all classes by name',
                        'alternatives': [
                            'ios hooking search methods <search-term>',
                            'Example: ios hooking search methods verify',
                            'Example: ios hooking search methods password',
                            'Example: ios hooking search methods token',
                            'Results show [ClassName + methodName] or [ClassName - methodName]'
                        ],
                        'success_indicators': [
                            'Multiple matches found across classes',
                            'Method signatures displayed',
                            'Sensitive methods identified'
                        ],
                        'failure_indicators': [
                            'No results (try different search term)',
                            'Too many results (refine search)'
                        ],
                        'next_steps': [
                            'Prioritize methods in app-specific classes',
                            'Hook methods for dynamic analysis',
                            'Document method signatures for report'
                        ],
                        'tags': ['MANUAL', 'OSCP:HIGH', 'ENUM'],
                        'estimated_time': '2-5 minutes',
                        'notes': 'High-value search terms: verify, check, validate, auth, login, password, token, api, encrypt, decrypt, admin, root, jailbreak'
                    }
                }
            ]
        }

    def _create_hooking_phase(self, target: str, app_name: str) -> Dict[str, Any]:
        """Phase 3: Runtime hooking and manipulation"""
        return {
            'id': f'ios-hook-{target.replace(".", "-")}',
            'name': 'Phase 3: Runtime Hooking & Manipulation',
            'type': 'parent',
            'children': [
                {
                    'id': f'ios-hook-all-methods-{target.replace(".", "-")}',
                    'name': 'Hook All Methods of a Class',
                    'type': 'manual',
                    'metadata': {
                        'description': 'Hook all methods of a class to observe parameters and return values',
                        'alternatives': [
                            'ios hooking watch class <class-name>',
                            'Example: ios hooking watch class iGoat_Swift.LoginViewController',
                            'This dumps all method calls with parameters and return values',
                            'Useful for discovering authentication flows and data handling',
                            'Output shows: method invoked, arguments passed, return value'
                        ],
                        'success_indicators': [
                            'Hooks installed successfully',
                            'Method calls logged in real-time',
                            'Parameters and return values displayed',
                            'App remains functional'
                        ],
                        'failure_indicators': [
                            'Hook installation failed (class not loaded)',
                            'App crashes (incompatible hooking)',
                            'No output (methods not called yet)'
                        ],
                        'next_steps': [
                            'Interact with app to trigger hooked methods',
                            'Analyze captured parameters for sensitive data',
                            'Look for hardcoded credentials or API keys',
                            'Document interesting findings in investigation_checklist.md'
                        ],
                        'tags': ['OSCP:HIGH', 'MANUAL', 'EXPLOIT'],
                        'estimated_time': '5-10 minutes',
                        'notes': 'This is noisy and generates lots of output. Filter by triggering specific app functionality (e.g., login screen).'
                    }
                },
                {
                    'id': f'ios-hook-single-method-{target.replace(".", "-")}',
                    'name': 'Hook Specific Method with Full Tracing',
                    'type': 'manual',
                    'metadata': {
                        'description': 'Hook a specific method with parameter dumping, backtrace, and return value logging',
                        'alternatives': [
                            'ios hooking watch method "-[<class-name> <method-name>]" --dump-args --dump-return --dump-backtrace',
                            'Example: ios hooking watch method "-[iGoat_Swift.LoginViewController loginButtonPressed:]" --dump-args --dump-return --dump-backtrace',
                            'Format: "-[ClassName methodName:]" for instance methods',
                            'Format: "+[ClassName methodName:]" for class methods',
                            '--dump-args: Show all parameters passed to method',
                            '--dump-return: Show return value',
                            '--dump-backtrace: Show call stack (where method was called from)'
                        ],
                        'success_indicators': [
                            'Hook installed successfully',
                            'Arguments captured when method called',
                            'Return value logged',
                            'Backtrace shows call chain'
                        ],
                        'failure_indicators': [
                            'Method not found (incorrect syntax)',
                            'No output (method not called)',
                            'App crashes (method critical to app stability)'
                        ],
                        'next_steps': [
                            'Trigger method by interacting with app',
                            'Analyze parameters for sensitive data (passwords, tokens)',
                            'Analyze return value (authentication success/failure)',
                            'Use backtrace to understand control flow',
                            'Document method behavior for bypass attempts'
                        ],
                        'tags': ['OSCP:HIGH', 'MANUAL', 'EXPLOIT'],
                        'estimated_time': '3-5 minutes per method',
                        'notes': 'Target methods: loginButtonPressed, verifyCredentials, checkJailbreak, validateLicense, isUserAuthorized'
                    }
                },
                {
                    'id': f'ios-hook-change-return-{target.replace(".", "-")}',
                    'name': 'Override Method Return Value',
                    'type': 'manual',
                    'metadata': {
                        'description': 'Force a method to return a specific boolean value (bypass authentication checks)',
                        'alternatives': [
                            'ios hooking set return_value "-[<class-name> <method-name>]" true',
                            'ios hooking set return_value "-[<class-name> <method-name>]" false',
                            'Example: ios hooking set return_value "-[JailbreakDetection isJailbroken]" false',
                            'Example: ios hooking set return_value "-[AuthManager isUserAuthorized]" true',
                            'This bypasses security checks that rely on boolean returns'
                        ],
                        'success_indicators': [
                            'Return value override successful',
                            'App behavior changes (bypassed check)',
                            'Access granted to protected functionality',
                            'Jailbreak detection bypassed'
                        ],
                        'failure_indicators': [
                            'App still denies access (additional checks exist)',
                            'App crashes (method return type mismatch)',
                            'Override has no effect (logic checks something else)'
                        ],
                        'next_steps': [
                            'Test if bypass is successful (interact with app)',
                            'If bypass fails: Analyze method implementation with Hopper',
                            'Look for additional verification methods to hook',
                            'Document successful bypass in breakthrough.md with exact command'
                        ],
                        'tags': ['QUICK_WIN', 'OSCP:HIGH', 'EXPLOIT', 'BYPASS'],
                        'estimated_time': '2-3 minutes per method',
                        'notes': 'Common bypass targets: isJailbroken, isRooted, isDebuggerAttached, isUserPremium, hasValidLicense, isSessionValid'
                    }
                },
                {
                    'id': f'ios-hook-generate-script-{target.replace(".", "-")}',
                    'name': 'Generate Frida Hooking Script Template',
                    'type': 'manual',
                    'metadata': {
                        'description': 'Generate Frida JavaScript template for advanced hooking (custom logic)',
                        'alternatives': [
                            'ios hooking generate simple <class-name>',
                            'Example: ios hooking generate simple iGoat_Swift.LoginViewController',
                            'This creates Frida script with Interceptor.attach() for each method',
                            'Customize script to add logic: modify parameters, change behavior',
                            'Save script and load with: frida -U -f <bundle-id> -l script.js'
                        ],
                        'success_indicators': [
                            'Script template generated',
                            'Contains Interceptor.attach() for each method',
                            'onEnter and onLeave hooks present'
                        ],
                        'failure_indicators': [
                            'Class not found',
                            'No methods to hook (empty class)'
                        ],
                        'next_steps': [
                            'Copy generated script to file (script.js)',
                            'Customize onEnter/onLeave logic as needed',
                            'Modify arguments: args[0].replace(ptr("0x1234"))',
                            'Change return value: retval.replace(ptr("0x1"))',
                            'Load script: frida -U -f com.app.bundle -l script.js --no-pause'
                        ],
                        'alternatives': [
                            'Manual Frida script from scratch',
                            'Use frida-tools: frida -U -f <app> -l <script>',
                            'Objection plugin: objection explore --plugin <script>',
                            'Frida Codeshare: search for existing hooks'
                        ],
                        'tags': ['OSCP:MEDIUM', 'ADVANCED', 'EXPLOIT'],
                        'estimated_time': '10-15 minutes (with customization)',
                        'notes': 'Generated script is a template. Add custom logic for parameter modification, logging, or bypasses.'
                    }
                },
                {
                    'id': f'ios-hook-monitor-crypto-{target.replace(".", "-")}',
                    'name': 'Monitor Cryptographic Operations',
                    'type': 'manual',
                    'metadata': {
                        'description': 'Hook CommonCrypto and Security framework to capture encryption keys and data',
                        'alternatives': [
                            'ios hooking watch method "+[CommonCryptor cryptorWithOperation:algorithm:options:key:keyLength:iv:ivLength:error:]" --dump-args',
                            'ios hooking watch method "-[SecKeyRef encryptData:withAlgorithm:error:]" --dump-args',
                            'This captures encryption keys, IVs, and plaintext before encryption',
                            'Manual Frida script for comprehensive crypto monitoring'
                        ],
                        'success_indicators': [
                            'Encryption operations captured',
                            'Keys and IVs logged',
                            'Plaintext data visible before encryption'
                        ],
                        'failure_indicators': [
                            'No crypto operations detected',
                            'App uses custom crypto (not CommonCrypto)'
                        ],
                        'next_steps': [
                            'Extract encryption keys for offline decryption',
                            'Analyze key derivation (weak keys, hardcoded keys)',
                            'Check for insecure ECB mode (no IV)',
                            'Document crypto weaknesses in vulnerability_research.md'
                        ],
                        'tags': ['OSCP:MEDIUM', 'ADVANCED', 'RESEARCH'],
                        'estimated_time': '15-20 minutes',
                        'notes': 'CommonCrypto is iOS standard crypto library. Look for hardcoded keys, weak algorithms (DES, MD5), and insecure modes (ECB).'
                    }
                },
                {
                    'id': f'ios-hook-url-requests-{target.replace(".", "-")}',
                    'name': 'Intercept Network Requests',
                    'type': 'manual',
                    'metadata': {
                        'description': 'Hook NSURLSession/URLSession to capture all HTTP/HTTPS requests and responses',
                        'alternatives': [
                            'ios hooking watch method "-[NSURLSession dataTaskWithRequest:completionHandler:]" --dump-args',
                            'ios hooking watch method "-[NSMutableURLRequest setHTTPBody:]" --dump-args',
                            'This captures API endpoints, headers, request bodies',
                            'Alternative: Use Burp Suite with SSL pinning bypass'
                        ],
                        'success_indicators': [
                            'HTTP requests captured',
                            'API endpoints logged',
                            'Request headers and bodies visible',
                            'Authentication tokens captured'
                        ],
                        'failure_indicators': [
                            'No requests captured (app uses native sockets)',
                            'SSL pinning blocks proxy (need pinning bypass)'
                        ],
                        'next_steps': [
                            'Analyze API endpoints for vulnerabilities',
                            'Extract authentication tokens (JWT, OAuth)',
                            'Test API endpoints directly (curl, Postman)',
                            'Look for insecure HTTP (not HTTPS)',
                            'Document API structure in enumeration.md'
                        ],
                        'alternatives': [
                            'Burp Suite proxy with SSL pinning bypass',
                            'Charles Proxy (iOS certificate trust)',
                            'mitmproxy with Frida SSL unpinning',
                            'Manual: Frida script with URLProtocol hooking'
                        ],
                        'tags': ['OSCP:HIGH', 'ENUM', 'EXPLOIT'],
                        'estimated_time': '10-15 minutes',
                        'notes': 'Many apps use certificate pinning. If proxy fails, use Frida to bypass pinning (objection SSL pinning bypass).'
                    }
                }
            ]
        }

    def _create_bypass_phase(self, target: str, app_name: str) -> Dict[str, Any]:
        """Phase 4: Security bypass techniques"""
        return {
            'id': f'ios-bypass-{target.replace(".", "-")}',
            'name': 'Phase 4: Security Bypass Techniques',
            'type': 'parent',
            'children': [
                {
                    'id': f'ios-bypass-jailbreak-{target.replace(".", "-")}',
                    'name': 'Bypass Jailbreak Detection',
                    'type': 'manual',
                    'metadata': {
                        'description': 'Bypass app jailbreak detection to run on jailbroken device',
                        'alternatives': [
                            'Search for jailbreak detection: ios hooking search methods jailbreak',
                            'Hook detection method: ios hooking set return_value "-[JailbreakDetector isJailbroken]" false',
                            'Common method names: isJailbroken, isDeviceJailbroken, detectJailbreak',
                            'Also search for: cydia, substrate, checkCydia',
                            'May need to hook multiple methods'
                        ],
                        'success_indicators': [
                            'App launches on jailbroken device',
                            'No jailbreak warning displayed',
                            'App functionality fully accessible'
                        ],
                        'failure_indicators': [
                            'App still detects jailbreak',
                            'App crashes on launch',
                            'Functionality restricted'
                        ],
                        'next_steps': [
                            'If bypass fails: Reverse engineer detection logic with Hopper',
                            'Look for file existence checks (/Applications/Cydia.app)',
                            'Look for fork() availability checks',
                            'Hook multiple detection methods',
                            'Document successful bypass chain in breakthrough.md'
                        ],
                        'alternatives': [
                            'Frida script with comprehensive jailbreak bypass',
                            'Shadow (tweak): Hides jailbreak from apps',
                            'Liberty Lite (Cydia tweak): Auto-bypass',
                            'Manual: Patch binary with Hopper (remove detection code)'
                        ],
                        'tags': ['QUICK_WIN', 'OSCP:HIGH', 'BYPASS', 'EXPLOIT'],
                        'estimated_time': '5-10 minutes',
                        'notes': 'Apps often have multiple layers of jailbreak detection. Hook all methods, not just one.'
                    }
                },
                {
                    'id': f'ios-bypass-ssl-pinning-{target.replace(".", "-")}',
                    'name': 'Bypass SSL Certificate Pinning',
                    'type': 'manual',
                    'metadata': {
                        'description': 'Disable SSL pinning to intercept HTTPS traffic with Burp Suite/proxy',
                        'alternatives': [
                            'Objection: ios sslpinning disable',
                            'This hooks common SSL pinning implementations',
                            'Alternative: Frida SSL unpinning script from Frida Codeshare',
                            'Alternative: SSL Kill Switch 2 (Cydia tweak for jailbroken devices)'
                        ],
                        'success_indicators': [
                            'SSL pinning disabled message',
                            'Burp Suite captures HTTPS traffic',
                            'No certificate validation errors',
                            'API requests visible in proxy'
                        ],
                        'failure_indicators': [
                            'App still rejects proxy certificate',
                            'No traffic in Burp Suite',
                            'App displays certificate error',
                            'App refuses to connect'
                        ],
                        'next_steps': [
                            'Configure device proxy: Settings → Wi-Fi → HTTP Proxy',
                            'Install Burp CA certificate on device',
                            'Trust certificate: Settings → General → About → Certificate Trust',
                            'Verify traffic in Burp Suite',
                            'Document SSL pinning bypass in breakthrough.md'
                        ],
                        'alternatives': [
                            'Frida Codeshare: search "SSL unpinning iOS"',
                            'SSL Kill Switch 2 (jailbroken)',
                            'Manual: Patch app binary to remove pinning',
                            'mitmproxy with Frida script'
                        ],
                        'tags': ['QUICK_WIN', 'OSCP:HIGH', 'BYPASS', 'EXPLOIT'],
                        'estimated_time': '5-10 minutes',
                        'notes': 'Objection built-in bypass works for AFNetworking, NSURLSession. Custom pinning may require custom Frida script.'
                    }
                },
                {
                    'id': f'ios-bypass-root-detection-{target.replace(".", "-")}',
                    'name': 'Bypass Root Detection (Alternative Check)',
                    'type': 'manual',
                    'metadata': {
                        'description': 'Bypass alternative root detection mechanisms (file checks, syscall checks)',
                        'alternatives': [
                            'Hook file existence checks: stat(), access(), fopen()',
                            'Hook fork() to return failure (some detections use fork availability)',
                            'Search for detection strings: ios hooking search methods root',
                            'Look for methods checking: /bin/bash, /usr/sbin/sshd, /etc/apt'
                        ],
                        'success_indicators': [
                            'File checks return "not found"',
                            'fork() returns failure',
                            'App no longer detects jailbreak'
                        ],
                        'failure_indicators': [
                            'Detection persists',
                            'App functionality still restricted'
                        ],
                        'next_steps': [
                            'Identify all detection mechanisms',
                            'Hook each mechanism individually',
                            'Test incrementally to isolate effective bypass',
                            'Document complete bypass chain'
                        ],
                        'tags': ['OSCP:MEDIUM', 'BYPASS', 'ADVANCED'],
                        'estimated_time': '15-20 minutes',
                        'notes': 'Advanced apps check multiple indicators: Cydia, substrate, file permissions, symlinks, fork availability.'
                    }
                },
                {
                    'id': f'ios-bypass-debugger-{target.replace(".", "-")}',
                    'name': 'Bypass Debugger Detection',
                    'type': 'manual',
                    'metadata': {
                        'description': 'Bypass anti-debugging checks (sysctl P_TRACED, ptrace)',
                        'alternatives': [
                            'Hook ptrace: Make it always fail',
                            'Hook sysctl P_TRACED check to return false',
                            'Search for methods: ios hooking search methods debug',
                            'Frida automatically bypasses some debugger checks'
                        ],
                        'success_indicators': [
                            'App runs under Frida/debugger',
                            'No anti-debugging alerts',
                            'Debugging functionality works'
                        ],
                        'failure_indicators': [
                            'App crashes on Frida attach',
                            'App detects debugger and exits'
                        ],
                        'next_steps': [
                            'Identify specific anti-debugging technique',
                            'Hook detection syscall/function',
                            'Test with LLDB debugger',
                            'Document bypass'
                        ],
                        'tags': ['OSCP:MEDIUM', 'BYPASS', 'ADVANCED'],
                        'estimated_time': '10-15 minutes',
                        'notes': 'Common checks: ptrace(PT_DENY_ATTACH), sysctl P_TRACED, isatty(), getppid() comparison.'
                    }
                }
            ]
        }

    def _create_non_jailbreak_phase(self, target: str, app_name: str) -> Dict[str, Any]:
        """Phase 5: Non-jailbreak testing (iOS 16+ compatible)"""
        return {
            'id': f'ios-non-jb-{target.replace(".", "-")}',
            'name': 'Phase 5: Non-Jailbreak Testing Workflow',
            'type': 'parent',
            'children': [
                {
                    'id': f'ios-obtain-ipa-{target.replace(".", "-")}',
                    'name': 'Obtain Decrypted IPA',
                    'type': 'parent',
                    'children': [
                        {
                            'id': f'ios-ipa-apple-configurator-{target.replace(".", "-")}',
                            'name': 'Download IPA via Apple Configurator (macOS)',
                            'type': 'manual',
                            'metadata': {
                                'description': 'Download IPA from App Store using Apple Configurator (macOS-only method)',
                                'alternatives': [
                                    '1. Install target app on iPhone via App Store',
                                    '2. Install Apple Configurator 2 on macOS',
                                    '3. Open Terminal: cd ~/Library/Group\\ Containers/K36BKF7T3D.group.com.apple.configurator/Library/Caches/Assets/TemporaryItems/MobileApps',
                                    '4. Open Apple Configurator, connect iPhone via USB',
                                    '5. Double-click device → Add → Apps',
                                    '6. Select target app (triggers download)',
                                    '7. IPA appears in TemporaryItems/MobileApps directory',
                                    '8. Copy IPA before it auto-deletes'
                                ],
                                'success_indicators': [
                                    'IPA file appears in MobileApps directory',
                                    'File size matches app size (100MB+)',
                                    'IPA filename matches app name'
                                ],
                                'failure_indicators': [
                                    'No IPA downloaded (app already installed)',
                                    'Directory empty (wrong path)',
                                    'IPA deleted automatically (too slow to copy)'
                                ],
                                'next_steps': [
                                    'Copy IPA to working directory',
                                    'Verify IPA: unzip -l app.ipa',
                                    'IPA is encrypted (FairPlay DRM)',
                                    'Proceed to decryption step'
                                ],
                                'tags': ['MANUAL', 'OSCP:HIGH'],
                                'estimated_time': '10 minutes',
                                'notes': 'This method downloads encrypted IPA. Requires macOS with Apple Configurator. IPA auto-deletes after install, copy quickly.'
                            }
                        },
                        {
                            'id': f'ios-ipa-decrypt-{target.replace(".", "-")}',
                            'name': 'Decrypt IPA (Jailbroken Device Required)',
                            'type': 'manual',
                            'metadata': {
                                'description': 'Decrypt FairPlay-protected IPA using jailbroken iOS device',
                                'alternatives': [
                                    'Option 1: frida-ios-dump (requires Frida on jailbroken device)',
                                    '  git clone https://github.com/AloneMonkey/frida-ios-dump',
                                    '  python3 dump.py <app-bundle-id>',
                                    '',
                                    'Option 2: CrackerXI (jailbroken, GUI tool from Cydia)',
                                    '  Install CrackerXI from Cydia',
                                    '  Open CrackerXI → Select app → Decrypt',
                                    '',
                                    'Option 3: Clutch (command-line, jailbroken)',
                                    '  clutch -d <app-bundle-id>',
                                    '',
                                    'Option 4: bfinject (jailbroken)',
                                    '  bash bfinject -P <app-bundle-id> -L decrypt'
                                ],
                                'success_indicators': [
                                    'Decrypted IPA saved to file',
                                    'No FairPlay encryption in binary',
                                    'IPA can be extracted without errors'
                                ],
                                'failure_indicators': [
                                    'Decryption fails (app not running)',
                                    'Jailbreak detection prevents decryption',
                                    'FairPlay still present (incomplete decryption)'
                                ],
                                'next_steps': [
                                    'Verify decryption: otool -l <binary> | grep crypt (cryptid should be 0)',
                                    'Extract IPA: unzip app.ipa',
                                    'Proceed to re-signing with get-task-allow',
                                    'Transfer decrypted IPA to macOS for re-signing'
                                ],
                                'tags': ['MANUAL', 'OSCP:HIGH'],
                                'estimated_time': '15-20 minutes',
                                'notes': 'Requires old jailbroken device (iOS 12-14). Newer jailbreaks may not support decryption tools. Ask client for decrypted IPA if possible.'
                            }
                        },
                        {
                            'id': f'ios-request-decrypted-{target.replace(".", "-")}',
                            'name': 'Request Decrypted IPA from Client',
                            'type': 'manual',
                            'metadata': {
                                'description': 'Ask client to provide decrypted IPA (recommended)',
                                'alternatives': [
                                    'Email client requesting decrypted IPA file',
                                    'Explain: Encrypted IPA cannot be tested without jailbreak',
                                    'Client can use internal build or decrypt themselves',
                                    'Most cooperative clients provide IPA directly'
                                ],
                                'success_indicators': [
                                    'Client provides IPA file',
                                    'IPA is unencrypted (verify with otool -l)'
                                ],
                                'failure_indicators': [
                                    'Client refuses or unable to provide',
                                    'Provided IPA still encrypted'
                                ],
                                'next_steps': [
                                    'Verify IPA is decrypted',
                                    'Proceed to re-signing phase'
                                ],
                                'tags': ['MANUAL', 'OSCP:HIGH', 'QUICK_WIN'],
                                'estimated_time': '1-2 days (wait time)',
                                'notes': 'Most efficient method. Clients often have development builds that are already unencrypted.'
                            }
                        }
                    ]
                },
                {
                    'id': f'ios-resign-ipa-{target.replace(".", "-")}',
                    'name': 'Re-sign IPA with get-task-allow Entitlement',
                    'type': 'parent',
                    'children': [
                        {
                            'id': f'ios-modify-entitlements-{target.replace(".", "-")}',
                            'name': 'Add get-task-allow Entitlement',
                            'type': 'manual',
                            'metadata': {
                                'description': 'Modify app entitlements to allow debugging and Frida attachment',
                                'alternatives': [
                                    '1. Unzip IPA: unzip app.ipa -d app_contents',
                                    '2. Find app binary: cd Payload/App.app',
                                    '3. Extract entitlements: codesign -d --entitlements - App > entitlements.xml',
                                    '4. Edit entitlements.xml, add: <key>get-task-allow</key><true/>',
                                    '5. Re-sign with modified entitlements (next step)'
                                ],
                                'success_indicators': [
                                    'entitlements.xml file created',
                                    'get-task-allow key added',
                                    'XML is well-formed'
                                ],
                                'failure_indicators': [
                                    'codesign fails (macOS only)',
                                    'XML parse error'
                                ],
                                'next_steps': [
                                    'Obtain Apple Developer certificate (free account OK)',
                                    'Proceed to re-signing step'
                                ],
                                'tags': ['MANUAL', 'OSCP:HIGH'],
                                'estimated_time': '5 minutes',
                                'notes': 'get-task-allow entitlement allows task_for_pid() calls, enabling Frida/LLDB attachment.'
                            }
                        },
                        {
                            'id': f'ios-resign-tool-{target.replace(".", "-")}',
                            'name': 'Re-sign IPA with iOS App Signer (macOS)',
                            'type': 'manual',
                            'metadata': {
                                'description': 'Re-sign IPA using iOS App Signer (GUI tool, macOS-only)',
                                'alternatives': [
                                    'Download iOS App Signer: https://github.com/DanTheMan827/ios-app-signer',
                                    'Open iOS App Signer app',
                                    'Input IPA file: Select decrypted IPA',
                                    'Signing Certificate: Select your Apple Developer certificate',
                                    'Provisioning Profile: Select matching profile',
                                    'Entitlements: Enable "get-task-allow"',
                                    'Output: Save as resigned.ipa',
                                    'Click "Start" to re-sign'
                                ],
                                'success_indicators': [
                                    'Re-signing completes successfully',
                                    'resigned.ipa file created',
                                    'No codesign errors'
                                ],
                                'failure_indicators': [
                                    'Certificate mismatch',
                                    'Provisioning profile invalid',
                                    'Entitlements conflict'
                                ],
                                'next_steps': [
                                    'Verify signature: codesign -dv --verbose=4 resigned.ipa',
                                    'Install on device: ideviceinstaller -i resigned.ipa',
                                    'Enable Developer Mode (iOS 16+)'
                                ],
                                'alternatives': [
                                    'Command-line: codesign -f -s "Developer Certificate" --entitlements entitlements.xml App.app',
                                    'iResign (GUI tool): https://github.com/maciekish/iReSign',
                                    'zsign (Linux-compatible): https://github.com/zhlynn/zsign'
                                ],
                                'tags': ['MANUAL', 'OSCP:HIGH'],
                                'estimated_time': '10 minutes',
                                'notes': 'Free Apple Developer account works. Provisioning profile expires after 7 days (re-sign weekly).'
                            }
                        },
                        {
                            'id': f'ios-obtain-cert-{target.replace(".", "-")}',
                            'name': 'Obtain Apple Developer Certificate (Free)',
                            'type': 'manual',
                            'metadata': {
                                'description': 'Create free Apple Developer certificate and provisioning profile',
                                'alternatives': [
                                    '1. Open Xcode',
                                    '2. Create new iOS app project (any template)',
                                    '3. Signing & Capabilities tab',
                                    '4. Team: Add Apple ID',
                                    '5. Xcode auto-creates certificate and provisioning profile',
                                    '6. Certificate location: Keychain Access → My Certificates',
                                    '7. Profile location: ~/Library/MobileDevice/Provisioning\\ Profiles/'
                                ],
                                'success_indicators': [
                                    'Certificate appears in Keychain',
                                    'Provisioning profile created',
                                    'Xcode shows no signing errors'
                                ],
                                'failure_indicators': [
                                    'Apple ID verification fails',
                                    'Two-factor authentication issues'
                                ],
                                'next_steps': [
                                    'Note certificate name for re-signing',
                                    'Note provisioning profile UUID',
                                    'Proceed to re-signing'
                                ],
                                'tags': ['MANUAL', 'OSCP:HIGH'],
                                'estimated_time': '10-15 minutes',
                                'notes': 'Free certificates expire after 7 days. Re-sign and re-install weekly. No paid Apple Developer account needed.'
                            }
                        }
                    ]
                },
                {
                    'id': f'ios-install-resigned-{target.replace(".", "-")}',
                    'name': 'Install Re-signed IPA on Device',
                    'type': 'parent',
                    'children': [
                        {
                            'id': f'ios-enable-dev-mode-{target.replace(".", "-")}',
                            'name': 'Enable Developer Mode (iOS 16+)',
                            'type': 'manual',
                            'metadata': {
                                'description': 'Enable iOS 16+ Developer Mode to allow debugging',
                                'alternatives': [
                                    '1. Install ANY developer-signed app on device first',
                                    '2. iOS prompts to enable Developer Mode',
                                    '3. Navigate: Settings → Privacy & Security → Developer Mode',
                                    '4. Toggle Developer Mode ON',
                                    '5. Device reboots',
                                    '6. Enter passcode after reboot',
                                    '7. Confirm "Turn On" Developer Mode'
                                ],
                                'success_indicators': [
                                    'Developer Mode toggle enabled',
                                    'Device reboots successfully',
                                    'Developer Mode remains on after reboot'
                                ],
                                'failure_indicators': [
                                    'Developer Mode option not visible (iOS < 16)',
                                    'Toggle grayed out'
                                ],
                                'next_steps': [
                                    'Developer Mode persists until disabled or device wiped',
                                    'Proceed to IPA installation',
                                    'Note: Only needed once per device'
                                ],
                                'tags': ['MANUAL', 'OSCP:HIGH', 'QUICK_WIN'],
                                'estimated_time': '5 minutes',
                                'notes': 'iOS 16+ requirement. Without Developer Mode, apps with get-task-allow refuse to launch. Also blocks Frida/LLDB.'
                            }
                        },
                        {
                            'id': f'ios-install-ipa-{target.replace(".", "-")}',
                            'name': 'Install IPA via ideviceinstaller',
                            'type': 'command',
                            'metadata': {
                                'command': f'ideviceinstaller -i resigned.ipa',
                                'description': 'Install re-signed IPA on connected iOS device via USB',
                                'flag_explanations': {
                                    'ideviceinstaller': 'libimobiledevice tool for IPA installation',
                                    '-i': 'Install IPA file',
                                    'resigned.ipa': 'Path to re-signed IPA file'
                                },
                                'success_indicators': [
                                    'Installation progress displayed',
                                    'Installation complete message',
                                    'App icon appears on device home screen'
                                ],
                                'failure_indicators': [
                                    'Device not detected (USB issue)',
                                    'Installation failed: invalid signature',
                                    'Installation failed: provisioning profile expired'
                                ],
                                'next_steps': [
                                    'Trust developer certificate: Settings → General → VPN & Device Management',
                                    'Tap certificate → Trust',
                                    'Launch app to verify it runs',
                                    'Connect Frida/Objection'
                                ],
                                'alternatives': [
                                    'Xcode: Window → Devices and Simulators → + → Add IPA',
                                    'AltStore: Sideload IPA via AltServer (auto re-signs)',
                                    'SideStore: Self-hosted AltStore alternative',
                                    'Cydia Impactor (deprecated, may not work on iOS 15+)',
                                    'ideviceinstaller -i resigned.ipa -w (wait for debugger)'
                                ],
                                'tags': ['OSCP:HIGH', 'MANUAL'],
                                'estimated_time': '5 minutes',
                                'notes': 'If installation fails with "untrusted developer", trust certificate in Settings first.'
                            }
                        },
                        {
                            'id': f'ios-trust-cert-{target.replace(".", "-")}',
                            'name': 'Trust Developer Certificate on Device',
                            'type': 'manual',
                            'metadata': {
                                'description': 'Configure iOS device to trust your developer certificate',
                                'alternatives': [
                                    '1. Settings → General → VPN & Device Management',
                                    '2. Under "Developer App", tap your certificate name',
                                    '3. Tap "Trust [Certificate Name]"',
                                    '4. Confirm trust',
                                    '5. App is now launchable'
                                ],
                                'success_indicators': [
                                    'Certificate shows as trusted',
                                    'App launches without error',
                                    'No "Untrusted Developer" message'
                                ],
                                'failure_indicators': [
                                    'Certificate not listed',
                                    'Trust option grayed out'
                                ],
                                'next_steps': [
                                    'Launch app from home screen',
                                    'Verify app runs normally',
                                    'Connect Frida: frida-ps -Uai',
                                    'Start Objection session'
                                ],
                                'tags': ['MANUAL', 'OSCP:HIGH', 'QUICK_WIN'],
                                'estimated_time': '2 minutes',
                                'notes': 'Required for all sideloaded apps. Trust persists until certificate expires (7 days for free accounts).'
                            }
                        }
                    ]
                },
                {
                    'id': f'ios-sideload-tools-{target.replace(".", "-")}',
                    'name': 'Modern Sideloading Tools (Alternative)',
                    'type': 'parent',
                    'children': [
                        {
                            'id': f'ios-altstore-{target.replace(".", "-")}',
                            'name': 'Use AltStore for Automatic Re-signing',
                            'type': 'manual',
                            'metadata': {
                                'description': 'Use AltStore to automatically re-sign and refresh IPA every 7 days',
                                'alternatives': [
                                    'Download AltStore: https://altstore.io/',
                                    'Install AltServer on macOS/Windows',
                                    'Connect device via USB',
                                    'Install AltStore on device via AltServer',
                                    'Open AltStore on device → + → Import IPA',
                                    'AltStore auto re-signs with your Apple ID',
                                    'AltStore refreshes signature every 7 days over Wi-Fi'
                                ],
                                'success_indicators': [
                                    'AltStore installed on device',
                                    'IPA imported and installed',
                                    'Auto-refresh enabled',
                                    'App remains functional after 7 days'
                                ],
                                'failure_indicators': [
                                    'Apple ID two-factor issues',
                                    'App limit reached (3 apps max for free accounts)',
                                    'Wi-Fi refresh fails (computer not on same network)'
                                ],
                                'next_steps': [
                                    'Keep AltServer running on computer for auto-refresh',
                                    'Connect to same Wi-Fi network',
                                    'AltStore handles re-signing automatically',
                                    'Proceed with Frida testing'
                                ],
                                'alternatives': [
                                    'SideStore (self-hosted AltStore fork)',
                                    'Sideloadly (Windows/Mac sideloading tool)'
                                ],
                                'tags': ['MANUAL', 'OSCP:MEDIUM'],
                                'estimated_time': '20-30 minutes (initial setup)',
                                'notes': 'Best for long-term testing. Free accounts limited to 3 apps. Computer must be on same network for auto-refresh.'
                            }
                        },
                        {
                            'id': f'ios-trollstore-{target.replace(".", "-")}',
                            'name': 'TrollStore (iOS 14.0-15.4.1 Only)',
                            'type': 'manual',
                            'metadata': {
                                'description': 'Use TrollStore for permanent signing (no 7-day limit) on vulnerable iOS versions',
                                'alternatives': [
                                    'Check iOS version: Settings → General → About',
                                    'TrollStore works on iOS 14.0 - 15.4.1 (CoreTrust bug)',
                                    'Install TrollStore via TrollHelper',
                                    'Install IPAs via TrollStore (permanent signature)',
                                    'No computer needed after initial setup',
                                    'No 3-app limit'
                                ],
                                'success_indicators': [
                                    'TrollStore installed',
                                    'IPAs install permanently',
                                    'No re-signing needed'
                                ],
                                'failure_indicators': [
                                    'iOS version not vulnerable (15.5+)',
                                    'CoreTrust bug patched'
                                ],
                                'next_steps': [
                                    'Install all testing IPAs via TrollStore',
                                    'No maintenance needed',
                                    'Proceed with testing'
                                ],
                                'tags': ['MANUAL', 'OSCP:MEDIUM', 'QUICK_WIN'],
                                'estimated_time': '15 minutes',
                                'notes': 'Only works on iOS 14.0-15.4.1. CoreTrust bug patched in iOS 15.5+. If available, this is the best method (permanent signing).'
                            }
                        }
                    ]
                },
                {
                    'id': f'ios-hook-non-jb-{target.replace(".", "-")}',
                    'name': 'Hook Re-signed App (Non-Jailbreak)',
                    'type': 'manual',
                    'metadata': {
                        'description': 'Verify Frida/Objection works on non-jailbroken device with re-signed app',
                        'alternatives': [
                            'Test Frida: frida-ps -Uai',
                            'Should list installed apps including re-signed app',
                            'Connect Objection: objection -d --gadget "com.app.bundle" explore',
                            'Verify hooks work: ios hooking list classes',
                            'All hooking commands from Phase 2-4 work identically'
                        ],
                        'success_indicators': [
                            'Frida connects to app',
                            'Objection session starts',
                            'Hooking commands work',
                            'App remains functional'
                        ],
                        'failure_indicators': [
                            'Failed to attach (get-task-allow missing)',
                            'Developer Mode not enabled (iOS 16+)',
                            'App crashes on hook (anti-debugging)'
                        ],
                        'next_steps': [
                            'Repeat all enumeration and hooking tasks',
                            'Non-jailbreak testing is equivalent to jailbreak testing',
                            'Document setup process for OSCP writeup',
                            'Proceed with full pentesting workflow'
                        ],
                        'tags': ['OSCP:HIGH', 'MANUAL', 'QUICK_WIN'],
                        'estimated_time': '5 minutes',
                        'notes': 'Once setup is complete, non-jailbreak testing is identical to jailbreak testing. All Objection/Frida commands work.'
                    }
                }
            ]
        }

    def _create_automation_phase(self, target: str, app_name: str, app_version: str) -> Dict[str, Any]:
        """Phase 6: Automated analysis and tools"""
        return {
            'id': f'ios-automation-{target.replace(".", "-")}',
            'name': 'Phase 6: Automated Analysis',
            'type': 'parent',
            'children': [
                {
                    'id': f'ios-mobsf-{target.replace(".", "-")}',
                    'name': 'MobSF Automated Analysis',
                    'type': 'parent',
                    'children': [
                        {
                            'id': f'ios-mobsf-setup-{target.replace(".", "-")}',
                            'name': 'Setup MobSF Docker Container',
                            'type': 'command',
                            'metadata': {
                                'command': 'docker run -d -p 8000:8000 --privileged -v /var/run/usbmuxd:/var/run/usbmuxd opensecurity/mobile-security-framework-mobsf:latest',
                                'description': 'Launch MobSF in Docker with iOS device support (usbmuxd passthrough)',
                                'flag_explanations': {
                                    'docker run': 'Run Docker container',
                                    '-d': 'Detached mode (runs in background)',
                                    '-p 8000:8000': 'Port mapping (host:container)',
                                    '--privileged': 'Privileged mode (required for USB access)',
                                    '-v /var/run/usbmuxd:/var/run/usbmuxd': 'Mount usbmuxd socket (iOS device communication)',
                                    'opensecurity/mobile-security-framework-mobsf:latest': 'MobSF Docker image'
                                },
                                'success_indicators': [
                                    'Container starts successfully',
                                    'MobSF accessible at http://127.0.0.1:8000',
                                    'Web interface loads'
                                ],
                                'failure_indicators': [
                                    'Port 8000 already in use',
                                    'Docker not installed',
                                    'Permission denied (need sudo or Docker group)'
                                ],
                                'next_steps': [
                                    'Open browser: http://127.0.0.1:8000',
                                    'Upload re-signed IPA',
                                    'MobSF auto-analyzes and instruments app',
                                    'Review findings in web UI'
                                ],
                                'alternatives': [
                                    'Install MobSF natively: git clone https://github.com/MobSF/Mobile-Security-Framework-MobSF',
                                    'Run on VM: Follow MobSF installation guide',
                                    'Use hosted MobSF (if available from client)',
                                    'Manual analysis with other tools (slower)'
                                ],
                                'tags': ['OSCP:MEDIUM', 'AUTOMATED', 'RESEARCH'],
                                'estimated_time': '10 minutes (first-time setup)',
                                'notes': 'MobSF requires Docker. usbmuxd passthrough enables device interaction. MobSF provides static + dynamic analysis.'
                            }
                        },
                        {
                            'id': f'ios-mobsf-upload-{target.replace(".", "-")}',
                            'name': 'Upload IPA to MobSF',
                            'type': 'manual',
                            'metadata': {
                                'description': 'Upload re-signed IPA to MobSF for automated static and dynamic analysis',
                                'alternatives': [
                                    'Open MobSF: http://127.0.0.1:8000',
                                    'Drag and drop IPA file or click upload',
                                    'MobSF extracts and analyzes IPA',
                                    'Wait for static analysis to complete (5-10 min)',
                                    'Review: Code analysis, Permissions, Binary analysis'
                                ],
                                'success_indicators': [
                                    'IPA uploaded successfully',
                                    'Static analysis completes',
                                    'Findings report generated',
                                    'Security score displayed'
                                ],
                                'failure_indicators': [
                                    'Upload fails (IPA too large)',
                                    'Analysis crashes (malformed IPA)',
                                    'Timeout (slow system)'
                                ],
                                'next_steps': [
                                    'Review static analysis findings',
                                    'Check for hardcoded secrets, API keys',
                                    'Review binary protections (PIE, ARC, encryption)',
                                    'Proceed to dynamic analysis'
                                ],
                                'tags': ['MANUAL', 'OSCP:MEDIUM', 'AUTOMATED'],
                                'estimated_time': '10-15 minutes',
                                'notes': 'MobSF static analysis scans: insecure storage, weak crypto, exposed components, hardcoded secrets, binary protections.'
                            }
                        },
                        {
                            'id': f'ios-mobsf-dynamic-{target.replace(".", "-")}',
                            'name': 'MobSF Dynamic Analysis',
                            'type': 'manual',
                            'metadata': {
                                'description': 'Use MobSF dynamic analysis to instrument and monitor app at runtime',
                                'alternatives': [
                                    'In MobSF report: Click "Dynamic Analyzer"',
                                    'Connect iOS device via USB',
                                    'MobSF deploys Frida to device',
                                    'MobSF instruments app automatically',
                                    'Interact with app via device',
                                    'MobSF captures: API calls, file operations, crypto usage'
                                ],
                                'success_indicators': [
                                    'Dynamic analysis starts',
                                    'Frida hooks installed',
                                    'App launches and remains running',
                                    'Activity logs captured'
                                ],
                                'failure_indicators': [
                                    'Device not detected',
                                    'Frida attachment fails',
                                    'App crashes'
                                ],
                                'next_steps': [
                                    'Interact with all app features',
                                    'Trigger authentication, data storage, network calls',
                                    'Review MobSF logs for sensitive data leaks',
                                    'Export findings for OSCP report'
                                ],
                                'tags': ['MANUAL', 'OSCP:MEDIUM', 'AUTOMATED'],
                                'estimated_time': '20-30 minutes',
                                'notes': 'MobSF dynamic analysis provides: Network traffic, File I/O, Keychain access, Logs, Screenshots. Similar to manual Frida but automated.'
                            }
                        },
                        {
                            'id': f'ios-mobsf-report-{target.replace(".", "-")}',
                            'name': 'Export MobSF Report',
                            'type': 'manual',
                            'metadata': {
                                'description': 'Generate comprehensive MobSF report for OSCP documentation',
                                'alternatives': [
                                    'In MobSF: Click "Generate Report"',
                                    'Select PDF or JSON format',
                                    'Report includes: Static findings, Dynamic findings, Screenshots',
                                    'Save report to documentation directory'
                                ],
                                'success_indicators': [
                                    'Report generated successfully',
                                    'All findings included',
                                    'Report is well-formatted'
                                ],
                                'failure_indicators': [
                                    'Report generation fails',
                                    'Missing sections'
                                ],
                                'next_steps': [
                                    'Review report for critical findings',
                                    'Cross-reference with manual testing results',
                                    'Document any findings not in MobSF report',
                                    'Include report in OSCP writeup'
                                ],
                                'tags': ['MANUAL', 'OSCP:MEDIUM', 'RESEARCH'],
                                'estimated_time': '5 minutes',
                                'notes': 'MobSF report is excellent for OSCP documentation. Shows comprehensive analysis with screenshots. Always verify findings manually.'
                            }
                        }
                    ]
                },
                {
                    'id': f'ios-frida-scripts-{target.replace(".", "-")}',
                    'name': 'Frida Codeshare Scripts',
                    'type': 'manual',
                    'metadata': {
                        'description': 'Use community Frida scripts for common iOS bypasses and analysis',
                        'alternatives': [
                            'Browse Frida Codeshare: https://codeshare.frida.re/',
                            'Search for: "iOS SSL pinning bypass"',
                            'Search for: "iOS jailbreak bypass"',
                            'Search for: "iOS anti-debug bypass"',
                            'Download script and load with Frida',
                            'frida -U -f com.app.bundle -l script.js --no-pause'
                        ],
                        'success_indicators': [
                            'Script loads successfully',
                            'Bypass works',
                            'App behavior changes as expected'
                        ],
                        'failure_indicators': [
                            'Script errors',
                            'Bypass ineffective (app-specific protections)',
                            'App crashes'
                        ],
                        'next_steps': [
                            'Customize script for target app',
                            'Combine multiple scripts',
                            'Document successful bypasses',
                            'Save working scripts for future use'
                        ],
                        'alternatives': [
                            'Objection built-in bypasses (easier)',
                            'Write custom Frida scripts',
                            'Use Ghidra/Hopper for static analysis'
                        ],
                        'tags': ['MANUAL', 'OSCP:MEDIUM', 'EXPLOIT'],
                        'estimated_time': '15-30 minutes',
                        'notes': 'Popular scripts: ios-ssl-bypass, ios-jailbreak-detection-bypass, ios-screenshot-bypass, ios-keychain-dump'
                    }
                },
                {
                    'id': f'ios-static-analysis-{target.replace(".", "-")}',
                    'name': 'Static Binary Analysis',
                    'type': 'manual',
                    'metadata': {
                        'description': 'Reverse engineer iOS binary with Hopper/Ghidra for logic analysis',
                        'alternatives': [
                            'Extract binary from IPA: unzip app.ipa',
                            'Binary location: Payload/App.app/App',
                            'Load in Hopper Disassembler (macOS): $99, best for iOS',
                            'Load in Ghidra (free, cross-platform): Slower but free',
                            'Analyze: Objective-C methods, Swift functions, string references',
                            'Search for: hardcoded keys, URLs, jailbreak checks, debug functions'
                        ],
                        'success_indicators': [
                            'Binary loads in disassembler',
                            'Symbols visible',
                            'Method implementations decompiled',
                            'Interesting strings found'
                        ],
                        'failure_indicators': [
                            'Binary encrypted (need decrypted IPA)',
                            'Heavy obfuscation',
                            'Symbols stripped'
                        ],
                        'next_steps': [
                            'Find jailbreak detection logic (patch binary)',
                            'Extract hardcoded credentials',
                            'Identify API endpoints',
                            'Document logic flaws',
                            'Use findings to guide dynamic analysis'
                        ],
                        'alternatives': [
                            'class-dump (extract Objective-C headers)',
                            'radare2 (command-line reverse engineering)',
                            'IDA Pro (expensive, professional)',
                            'Binary Ninja (mid-tier option)'
                        ],
                        'tags': ['OSCP:MEDIUM', 'ADVANCED', 'RESEARCH'],
                        'estimated_time': '1-3 hours',
                        'notes': 'Static analysis is time-consuming but reveals logic that dynamic testing may miss. Focus on security-critical methods.'
                    }
                }
            ]
        }

    def get_manual_alternatives(self, task_id: str) -> List[str]:
        """
        Get manual alternatives for iOS hooking tasks

        Args:
            task_id: Task identifier

        Returns:
            List of manual alternative approaches
        """
        alternatives = {
            'frida-ps': [
                'Settings → General → About → Applications (view installed)',
                'Xcode → Devices and Simulators → View apps',
                'ideviceinstaller -l (libimobiledevice)'
            ],
            'objection-connect': [
                'Direct Frida: frida -U -f <bundle-id> -l script.js',
                'LLDB debugger: debugserver *:1234 -a App',
                'Console.app on macOS (view logs)'
            ],
            'enumerate-classes': [
                'class-dump <binary> (offline static analysis)',
                'Hopper Disassembler → Classes view',
                'otool -ov <binary> (list Objective-C segments)'
            ],
            'hook-method': [
                'Manual Frida script with Interceptor.attach()',
                'Method swizzling (if jailbroken)',
                'Binary patching with Hopper (permanent modification)'
            ],
            'ssl-pinning': [
                'Burp Suite + SSL Kill Switch 2 (jailbroken)',
                'Patch binary: Remove pinning code with Hopper',
                'Frida Codeshare: ios-ssl-bypass script'
            ]
        }

        # Return alternatives if task_id matches pattern
        for key in alternatives:
            if key in task_id:
                return alternatives[key]

        # Default alternatives
        return [
            'Manual testing with device interaction',
            'Static analysis with disassembler',
            'Custom Frida script development',
            'Xcode debugging tools'
        ]
