"""
macOS System Enumeration Plugin

Generates comprehensive tasks for macOS system enumeration including:
- System information gathering
- User and process enumeration
- Network configuration
- Installed software and services
- Security configuration
- Auto-start and persistence locations
- Privilege escalation vectors

Extracted from HackTricks macOS documentation:
- macos-useful-commands.md
- macos-auto-start-locations.md

Generated by: CrackPot v1.0
"""

from typing import Dict, Any, List
from .base import ServicePlugin
from .registry import ServiceRegistry


@ServiceRegistry.register
class MacOSEnumerationPlugin(ServicePlugin):
    """macOS system enumeration plugin for post-exploitation"""

    @property
    def name(self) -> str:
        return "macos-enumeration"

    @property
    def default_ports(self) -> List[int]:
        return []  # Not port-based, triggered by OS detection

    @property
    def service_names(self) -> List[str]:
        return ['macos', 'darwin', 'osx']

    def detect(self, port_info: Dict[str, Any], profile: 'TargetProfile') -> bool:
        """Detect macOS systems"""
        ostype = port_info.get('ostype', '').lower()
        os_info = port_info.get('os', '').lower()
        service = port_info.get('service', '').lower()

        # Check for macOS indicators
        if any(indicator in ostype for indicator in ['darwin', 'macos', 'mac os']):
            return True

        if any(indicator in os_info for indicator in ['darwin', 'macos', 'mac os']):
            return True

        # Some macOS-specific services
        if service in ['afp', 'apple-filing']:
            return True

        return False

    def detect_from_finding(self, finding: Dict[str, Any], profile=None) -> int:
        """
        Detect macOS enumeration activation from findings

        Activates on:
        - macOS OS detected (high confidence)
        - macOS shell obtained (high confidence)

        Returns:
            int: Confidence score (0-100)
        """
        from ..core.constants import FindingTypes
        import logging
        logger = logging.getLogger(__name__)

        finding_type = finding.get('type', '').lower()
        description = finding.get('description', '').lower()

        # Perfect match - macOS OS
        if finding_type == FindingTypes.OS_MACOS:
            logger.info("macOS enumeration activating: macOS OS detected")
            return 95

        # High - Shell on macOS
        if finding_type == FindingTypes.SHELL_OBTAINED:
            macos_hints = ['macos', 'darwin', 'osx', '/users/', '/applications/']
            if any(hint in description for hint in macos_hints):
                logger.info("macOS enumeration activating: macOS shell detected")
                return 90

        # Medium - OS detected with macOS mention
        if finding_type == FindingTypes.OS_DETECTED:
            if any(term in description for term in ['macos', 'darwin', 'osx', 'mac os']):
                return 85

        return 0

    def get_task_tree(self, target: str, port: int, service_info: Dict[str, Any]) -> Dict[str, Any]:
        """Generate macOS enumeration task tree"""

        tasks = {
            'id': f'macos-enum-{target}',
            'name': f'macOS System Enumeration: {target}',
            'type': 'parent',
            'children': []
        }

        # Phase 1: Basic System Information
        tasks['children'].append({
            'id': f'macos-sysinfo-{target}',
            'name': 'System Information Gathering',
            'type': 'parent',
            'children': [
                {
                    'id': f'macos-basic-info-{target}',
                    'name': 'Basic System Info',
                    'type': 'command',
                    'metadata': {
                        'command': f'ssh {target} "uname -a && sw_vers"',
                        'description': 'Get macOS version and kernel information',
                        'tags': ['OSCP:HIGH', 'QUICK_WIN', 'MANUAL'],
                        'flag_explanations': {
                            'uname -a': 'Display all system information (kernel, hostname, version)',
                            'sw_vers': 'Show macOS software version details'
                        },
                        'success_indicators': [
                            'Darwin kernel version displayed',
                            'macOS version number shown',
                            'Build number visible'
                        ],
                        'failure_indicators': [
                            'Command not found (not macOS)',
                            'Permission denied',
                            'Connection refused'
                        ],
                        'next_steps': [
                            'Note macOS version for vulnerability research',
                            'Check kernel version for local exploits',
                            'Run system_profiler for detailed info'
                        ],
                        'alternatives': [
                            'system_profiler SPSoftwareDataType',
                            'sw_vers -productVersion',
                            'cat /System/Library/CoreServices/SystemVersion.plist'
                        ],
                        'notes': 'macOS version critical for exploit compatibility',
                        'estimated_time': '30 seconds'
                    }
                },
                {
                    'id': f'macos-system-profiler-{target}',
                    'name': 'Detailed System Profile',
                    'type': 'command',
                    'metadata': {
                        'command': f'ssh {target} "system_profiler SPSoftwareDataType SPNetworkDataType SPHardwareDataType"',
                        'description': 'Comprehensive system information gathering',
                        'tags': ['OSCP:HIGH', 'ENUM'],
                        'flag_explanations': {
                            'SPSoftwareDataType': 'Software and OS information',
                            'SPNetworkDataType': 'Network interfaces and configuration',
                            'SPHardwareDataType': 'Hardware specifications and serial numbers'
                        },
                        'success_indicators': [
                            'Computer name and model displayed',
                            'OS version and boot time shown',
                            'Network interfaces enumerated',
                            'Hardware UUID visible'
                        ],
                        'failure_indicators': [
                            'Timeout (slow command on remote system)',
                            'Partial output only'
                        ],
                        'next_steps': [
                            'Note computer name and UUID',
                            'Document network interfaces',
                            'Check boot time (indicates last restart)'
                        ],
                        'alternatives': [
                            'system_profiler -listDataTypes (see all available types)',
                            'system_profiler SPFirewallDataType (firewall status)',
                            'system_profiler SPDeveloperToolsDataType (dev tools)'
                        ],
                        'notes': 'Can be slow on some systems. Use specific DataTypes for speed',
                        'estimated_time': '1-2 minutes'
                    }
                },
                {
                    'id': f'macos-uptime-{target}',
                    'name': 'Check System Uptime',
                    'type': 'command',
                    'metadata': {
                        'command': f'ssh {target} "uptime && w"',
                        'description': 'Check how long system has been running and active users',
                        'tags': ['QUICK_WIN', 'MANUAL', 'OSCP:MEDIUM'],
                        'flag_explanations': {
                            'uptime': 'Show system uptime and load average',
                            'w': 'Show who is logged in and what they are doing'
                        },
                        'success_indicators': [
                            'Uptime displayed',
                            'Load averages shown',
                            'Currently logged-in users listed'
                        ],
                        'failure_indicators': [
                            'No output'
                        ],
                        'next_steps': [
                            'Note active users (avoid detection)',
                            'Check if recently rebooted (patches applied?)',
                            'Monitor for admin logins'
                        ],
                        'alternatives': [
                            'who (show logged in users)',
                            'last (show login history)',
                            'w -h (hide header)'
                        ],
                        'notes': 'Recent reboot may indicate patching. Long uptime may mean vulnerabilities',
                        'estimated_time': '10 seconds'
                    }
                }
            ]
        })

        # Phase 2: User and Permission Enumeration
        tasks['children'].append({
            'id': f'macos-user-enum-{target}',
            'name': 'User and Permission Enumeration',
            'type': 'parent',
            'children': [
                {
                    'id': f'macos-current-user-{target}',
                    'name': 'Identify Current User',
                    'type': 'command',
                    'metadata': {
                        'command': f'ssh {target} "whoami && id && groups"',
                        'description': 'Identify current user, UID, GID, and group memberships',
                        'tags': ['OSCP:HIGH', 'QUICK_WIN', 'MANUAL'],
                        'flag_explanations': {
                            'whoami': 'Display current username',
                            'id': 'Display user and group IDs (uid, gid, groups)',
                            'groups': 'List all group memberships'
                        },
                        'success_indicators': [
                            'Username displayed',
                            'UID and GID shown',
                            'Group memberships listed (check for admin, wheel)'
                        ],
                        'failure_indicators': [
                            'Command not found'
                        ],
                        'next_steps': [
                            'Check if user is in admin group (sudo privileges)',
                            'Check if user is in wheel group (su privileges)',
                            'Test sudo access: sudo -l'
                        ],
                        'alternatives': [
                            'echo $USER',
                            'dscl . -read /Users/$USER',
                            'finger $USER'
                        ],
                        'notes': 'Admin group membership often means sudo access',
                        'estimated_time': '10 seconds'
                    }
                },
                {
                    'id': f'macos-list-users-{target}',
                    'name': 'Enumerate All Users',
                    'type': 'command',
                    'metadata': {
                        'command': f'ssh {target} "dscl . list /Users | grep -v \'^_\'"',
                        'description': 'List all user accounts (excluding system accounts)',
                        'tags': ['OSCP:HIGH', 'ENUM', 'MANUAL'],
                        'flag_explanations': {
                            'dscl': 'Directory Service command line utility',
                            '. list /Users': 'List all users from local directory',
                            'grep -v \'^_\'': 'Exclude system accounts (start with underscore)'
                        },
                        'success_indicators': [
                            'List of usernames displayed',
                            'System accounts filtered out'
                        ],
                        'failure_indicators': [
                            'Permission denied',
                            'Empty list'
                        ],
                        'next_steps': [
                            'Identify administrator accounts',
                            'Check home directories: ls -la /Users/',
                            'Look for recently created users'
                        ],
                        'alternatives': [
                            'ls -la /Users/ (list home directories)',
                            'dscl . -readall /Users UniqueID (get all UIDs)',
                            'cat /etc/passwd (limited on macOS)'
                        ],
                        'notes': 'System accounts start with underscore. Focus on regular users',
                        'estimated_time': '15 seconds'
                    }
                },
                {
                    'id': f'macos-admin-users-{target}',
                    'name': 'Identify Administrator Users',
                    'type': 'command',
                    'metadata': {
                        'command': f'ssh {target} "dscl . -read /Groups/admin GroupMembership"',
                        'description': 'List all users in admin group (have sudo access)',
                        'tags': ['OSCP:HIGH', 'QUICK_WIN', 'ENUM'],
                        'flag_explanations': {
                            'dscl': 'Directory Service command line utility',
                            '. -read /Groups/admin': 'Read admin group properties',
                            'GroupMembership': 'Display group members'
                        },
                        'success_indicators': [
                            'List of admin users displayed',
                            'GroupMembership field populated'
                        ],
                        'failure_indicators': [
                            'Permission denied',
                            'Group not found'
                        ],
                        'next_steps': [
                            'Target admin users for credential attacks',
                            'Check sudo policies: sudo -l',
                            'Look for weak admin passwords'
                        ],
                        'alternatives': [
                            'dscl . -read /Groups/wheel GroupMembership',
                            'sudo dscl . -list /Users | while read user; do sudo groups $user; done'
                        ],
                        'notes': 'Admin users can sudo. Wheel group can su to root',
                        'estimated_time': '15 seconds'
                    }
                },
                {
                    'id': f'macos-sudo-rights-{target}',
                    'name': 'Check Sudo Privileges',
                    'type': 'command',
                    'metadata': {
                        'command': f'ssh {target} "sudo -l"',
                        'description': 'List commands current user can run with sudo',
                        'tags': ['OSCP:HIGH', 'QUICK_WIN', 'PRIVESC'],
                        'flag_explanations': {
                            'sudo': 'Execute command as another user (usually root)',
                            '-l': 'List commands user is allowed to run with sudo'
                        },
                        'success_indicators': [
                            'List of allowed sudo commands',
                            'NOPASSWD entries (no password required)',
                            'ALL = (ALL) (full sudo access)'
                        ],
                        'failure_indicators': [
                            'User may not run sudo',
                            'Password prompt (try common passwords)',
                            'Permission denied'
                        ],
                        'next_steps': [
                            'Check for dangerous sudo entries (ALL, NOPASSWD)',
                            'Test GTFOBins for allowed binaries',
                            'Look for custom scripts with sudo access'
                        ],
                        'alternatives': [
                            'cat /etc/sudoers (requires root)',
                            'ls -la /etc/sudoers.d/ (additional sudo configs)'
                        ],
                        'notes': 'NOPASSWD entries are quick wins. Check https://gtfobins.github.io/',
                        'estimated_time': '20 seconds'
                    }
                }
            ]
        })

        # Phase 3: Network Configuration
        tasks['children'].append({
            'id': f'macos-network-enum-{target}',
            'name': 'Network Configuration Enumeration',
            'type': 'parent',
            'children': [
                {
                    'id': f'macos-network-interfaces-{target}',
                    'name': 'Enumerate Network Interfaces',
                    'type': 'command',
                    'metadata': {
                        'command': f'ssh {target} "ifconfig -a"',
                        'description': 'List all network interfaces and IP addresses',
                        'tags': ['OSCP:HIGH', 'QUICK_WIN', 'ENUM'],
                        'flag_explanations': {
                            'ifconfig': 'Configure network interface parameters',
                            '-a': 'Display all interfaces (including inactive)'
                        },
                        'success_indicators': [
                            'Network interfaces listed (en0, en1, etc.)',
                            'IP addresses displayed',
                            'MAC addresses visible',
                            'Interface status (up/down) shown'
                        ],
                        'failure_indicators': [
                            'Permission denied',
                            'Command not found'
                        ],
                        'next_steps': [
                            'Note all IP addresses (pivot candidates)',
                            'Identify dual-homed hosts (multiple networks)',
                            'Check for VPN interfaces (utun)',
                            'Document wireless interfaces (en0 typically WiFi)'
                        ],
                        'alternatives': [
                            'networksetup -listallhardwareports',
                            'networksetup -listallnetworkservices',
                            'scutil --nwi (network information)'
                        ],
                        'notes': 'Multiple IPs indicate potential pivot points to other networks',
                        'estimated_time': '15 seconds'
                    }
                },
                {
                    'id': f'macos-arp-table-{target}',
                    'name': 'View ARP Table',
                    'type': 'command',
                    'metadata': {
                        'command': f'ssh {target} "arp -a"',
                        'description': 'Display ARP cache (discover other hosts on local network)',
                        'tags': ['OSCP:HIGH', 'QUICK_WIN', 'RECON'],
                        'flag_explanations': {
                            'arp': 'Address Resolution Protocol (IP to MAC mapping)',
                            '-a': 'Display all entries in ARP cache'
                        },
                        'success_indicators': [
                            'List of IP and MAC addresses',
                            'Multiple entries (active network)',
                            'Gateway address identified'
                        ],
                        'failure_indicators': [
                            'Empty ARP cache',
                            'Permission denied'
                        ],
                        'next_steps': [
                            'Identify other hosts on network',
                            'Note gateway MAC address',
                            'Use discovered IPs for lateral movement',
                            'Check for interesting hostnames'
                        ],
                        'alternatives': [
                            'arp -i en0 -l -a (specific interface)',
                            'ndp -a (IPv6 neighbor discovery)'
                        ],
                        'notes': 'ARP cache shows recently communicated hosts. Great for network mapping',
                        'estimated_time': '10 seconds'
                    }
                },
                {
                    'id': f'macos-listening-ports-{target}',
                    'name': 'Enumerate Listening Ports',
                    'type': 'command',
                    'metadata': {
                        'command': f'ssh {target} "lsof -i -P -n | grep LISTEN"',
                        'description': 'List all listening network ports and associated processes',
                        'tags': ['OSCP:HIGH', 'ENUM', 'MANUAL'],
                        'flag_explanations': {
                            'lsof': 'List open files (includes network sockets)',
                            '-i': 'Select IPv4/IPv6 files',
                            '-P': 'Show port numbers (not service names)',
                            '-n': 'Don\'t resolve hostnames (faster)',
                            'grep LISTEN': 'Filter for listening sockets only'
                        },
                        'success_indicators': [
                            'List of listening ports displayed',
                            'Process names shown',
                            'User running each service visible',
                            'Local bind addresses shown'
                        ],
                        'failure_indicators': [
                            'Permission denied (need sudo for full list)',
                            'Empty output'
                        ],
                        'next_steps': [
                            'Identify services running as root',
                            'Check for unusual listening ports',
                            'Test access to each service',
                            'Look for development servers (8000, 3000, etc.)'
                        ],
                        'alternatives': [
                            'netstat -an | grep LISTEN',
                            'sudo lsof -i -P -n | grep LISTEN (full list)',
                            'nettop (monitor network usage)'
                        ],
                        'notes': 'Services on 127.0.0.1 may be accessible via SSH tunnel',
                        'estimated_time': '20 seconds'
                    }
                },
                {
                    'id': f'macos-network-config-{target}',
                    'name': 'Network Configuration Details',
                    'type': 'command',
                    'metadata': {
                        'command': f'ssh {target} "networksetup -listallnetworkservices && networksetup -getinfo Wi-Fi"',
                        'description': 'Get detailed network service configuration',
                        'tags': ['OSCP:MEDIUM', 'ENUM'],
                        'flag_explanations': {
                            'networksetup': 'Configure network settings',
                            '-listallnetworkservices': 'List all configured network services',
                            '-getinfo': 'Get detailed configuration for service',
                            'Wi-Fi': 'WiFi service name (adapt for Ethernet, etc.)'
                        },
                        'success_indicators': [
                            'Network services listed',
                            'IP configuration displayed (DHCP/manual)',
                            'DNS servers shown',
                            'Gateway address visible'
                        ],
                        'failure_indicators': [
                            'Permission denied',
                            'Service not found (adjust name)'
                        ],
                        'next_steps': [
                            'Check proxy settings: networksetup -getwebproxy Wi-Fi',
                            'Check for auto-proxy: networksetup -getautoproxyurl Wi-Fi',
                            'Document DNS servers (potential targets)',
                            'Check firewall: system_profiler SPFirewallDataType'
                        ],
                        'alternatives': [
                            'networksetup -getwebproxy Wi-Fi (HTTP proxy)',
                            'networksetup -getftpproxy Wi-Fi (FTP proxy)',
                            'scutil --dns (DNS configuration)'
                        ],
                        'notes': 'Proxy configurations may reveal internal infrastructure',
                        'estimated_time': '30 seconds'
                    }
                },
                {
                    'id': f'macos-smb-shares-{target}',
                    'name': 'Check Mounted SMB Shares',
                    'type': 'command',
                    'metadata': {
                        'command': f'ssh {target} "smbutil statshares -a"',
                        'description': 'Display SMB shares mounted on the system',
                        'tags': ['OSCP:MEDIUM', 'QUICK_WIN', 'ENUM'],
                        'flag_explanations': {
                            'smbutil': 'SMB utility for managing connections',
                            'statshares': 'Display status of SMB shares',
                            '-a': 'Show all shares'
                        },
                        'success_indicators': [
                            'List of mounted shares',
                            'Server names visible',
                            'Share names and mount points shown'
                        ],
                        'failure_indicators': [
                            'No shares mounted',
                            'Command not found'
                        ],
                        'next_steps': [
                            'Access mounted shares for data',
                            'Check permissions on share contents',
                            'Look for credentials in share data',
                            'Document share servers (lateral movement targets)'
                        ],
                        'alternatives': [
                            'mount | grep smbfs (show SMB mounts)',
                            'df -h | grep smb (SMB mount points)'
                        ],
                        'notes': 'Mounted shares often contain sensitive data',
                        'estimated_time': '15 seconds'
                    }
                }
            ]
        })

        # Phase 4: Installed Software and Services
        tasks['children'].append({
            'id': f'macos-software-enum-{target}',
            'name': 'Software and Service Enumeration',
            'type': 'parent',
            'children': [
                {
                    'id': f'macos-installed-apps-{target}',
                    'name': 'List Installed Applications',
                    'type': 'command',
                    'metadata': {
                        'command': f'ssh {target} "system_profiler SPApplicationsDataType -json"',
                        'description': 'Enumerate all installed applications',
                        'tags': ['OSCP:HIGH', 'ENUM'],
                        'flag_explanations': {
                            'system_profiler': 'Report system configuration',
                            'SPApplicationsDataType': 'Applications data type',
                            '-json': 'Output in JSON format (easier parsing)'
                        },
                        'success_indicators': [
                            'List of installed apps with versions',
                            'Installation paths shown',
                            'Last modified dates visible'
                        ],
                        'failure_indicators': [
                            'Timeout (slow command)',
                            'Partial output'
                        ],
                        'next_steps': [
                            'Research vulnerable app versions',
                            'Check for privilege escalation vectors',
                            'Look for security tools (detection risk)',
                            'Identify development tools'
                        ],
                        'alternatives': [
                            'ls -la /Applications/',
                            'mdfind "kMDItemKind == Application"',
                            'system_profiler SPApplicationsDataType (text format)'
                        ],
                        'notes': 'Focus on outdated apps. Check searchsploit for versions',
                        'estimated_time': '2-3 minutes'
                    }
                },
                {
                    'id': f'macos-launchd-services-{target}',
                    'name': 'Enumerate LaunchDaemons and LaunchAgents',
                    'type': 'command',
                    'metadata': {
                        'command': f'ssh {target} "launchctl list"',
                        'description': 'List all running launchd services',
                        'tags': ['OSCP:HIGH', 'ENUM'],
                        'flag_explanations': {
                            'launchctl': 'Interface to launchd (system service manager)',
                            'list': 'List loaded services with PIDs and status codes'
                        },
                        'success_indicators': [
                            'List of running services',
                            'Process IDs shown',
                            'Service labels visible'
                        ],
                        'failure_indicators': [
                            'Permission denied for some services',
                            'Empty list'
                        ],
                        'next_steps': [
                            'Identify interesting services',
                            'Check service configurations in /Library/LaunchDaemons/',
                            'Look for custom/third-party services',
                            'Check for SUID binaries in service paths'
                        ],
                        'alternatives': [
                            'ls -la /Library/LaunchDaemons/',
                            'ls -la /Library/LaunchAgents/',
                            'ls -la ~/Library/LaunchAgents/',
                            'launchctl print system (detailed system domain)',
                            'launchctl print gui/$(id -u) (user domain)'
                        ],
                        'notes': 'LaunchDaemons run as root. LaunchAgents run as user',
                        'estimated_time': '30 seconds'
                    }
                },
                {
                    'id': f'macos-brew-packages-{target}',
                    'name': 'List Homebrew Packages',
                    'type': 'command',
                    'metadata': {
                        'command': f'ssh {target} "brew list"',
                        'description': 'Enumerate installed Homebrew packages',
                        'tags': ['OSCP:MEDIUM', 'ENUM'],
                        'flag_explanations': {
                            'brew': 'Homebrew package manager for macOS',
                            'list': 'List all installed formulae'
                        },
                        'success_indicators': [
                            'List of installed packages',
                            'Package names displayed'
                        ],
                        'failure_indicators': [
                            'Command not found (Homebrew not installed)',
                            'Empty list'
                        ],
                        'next_steps': [
                            'Check versions: brew info <package>',
                            'Research outdated packages for vulnerabilities',
                            'Look for security tools (nmap, metasploit, etc.)',
                            'Check for development tools'
                        ],
                        'alternatives': [
                            'ls -la /usr/local/Cellar/ (Homebrew install directory)',
                            'brew --version (check Homebrew version)',
                            'brew outdated (list outdated packages)'
                        ],
                        'notes': 'Homebrew common on developer/power-user systems',
                        'estimated_time': '15 seconds'
                    }
                },
                {
                    'id': f'macos-running-processes-{target}',
                    'name': 'Enumerate Running Processes',
                    'type': 'command',
                    'metadata': {
                        'command': f'ssh {target} "ps aux | head -50"',
                        'description': 'List running processes (limit to first 50 for readability)',
                        'tags': ['OSCP:HIGH', 'QUICK_WIN', 'ENUM'],
                        'flag_explanations': {
                            'ps': 'Process status',
                            'a': 'Show processes from all users',
                            'u': 'User-oriented format (show user column)',
                            'x': 'Show processes without controlling terminal',
                            'head -50': 'Display first 50 lines'
                        },
                        'success_indicators': [
                            'Process list with users',
                            'CPU and memory usage shown',
                            'Command lines visible'
                        ],
                        'failure_indicators': [
                            'Truncated output',
                            'Permission denied'
                        ],
                        'next_steps': [
                            'Identify processes running as root',
                            'Look for security tools (AV, EDR, monitoring)',
                            'Check for interesting services (databases, web servers)',
                            'Note process command lines (may contain credentials)'
                        ],
                        'alternatives': [
                            'ps aux | grep root (root processes)',
                            'ps -ef (different format)',
                            'top -l 1 (process snapshot with stats)'
                        ],
                        'notes': 'Full ps output can be huge. Filter for interesting processes',
                        'estimated_time': '15 seconds'
                    }
                }
            ]
        })

        # Phase 5: Persistence and Auto-Start Locations
        tasks['children'].append({
            'id': f'macos-persistence-enum-{target}',
            'name': 'Persistence Mechanism Enumeration',
            'type': 'parent',
            'children': [
                {
                    'id': f'macos-launch-agents-daemons-{target}',
                    'name': 'Check LaunchAgents and LaunchDaemons',
                    'type': 'command',
                    'metadata': {
                        'command': f'ssh {target} "find /Library/Launch* ~/Library/Launch* /System/Library/Launch* -type f -name \'*.plist\' 2>/dev/null | head -20"',
                        'description': 'Find LaunchAgent and LaunchDaemon plists (persistence)',
                        'tags': ['OSCP:HIGH', 'PERSISTENCE', 'ENUM'],
                        'flag_explanations': {
                            'find': 'Search for files',
                            '/Library/Launch*': 'System-wide launch locations',
                            '~/Library/Launch*': 'User-specific launch locations',
                            '-type f': 'Files only (not directories)',
                            '-name \'*.plist\'': 'Property list files only',
                            '2>/dev/null': 'Suppress permission errors',
                            'head -20': 'Limit to first 20 results'
                        },
                        'success_indicators': [
                            'List of plist files',
                            'Paths to launch items',
                            'User and system locations shown'
                        ],
                        'failure_indicators': [
                            'Permission denied on all paths',
                            'No files found'
                        ],
                        'next_steps': [
                            'Read interesting plists: cat <path>',
                            'Look for unusual or custom services',
                            'Check ProgramArguments for executables',
                            'Identify writable plist files for persistence'
                        ],
                        'alternatives': [
                            'ls -la /Library/LaunchDaemons/',
                            'ls -la /Library/LaunchAgents/',
                            'ls -la ~/Library/LaunchAgents/',
                            'plutil -p <file.plist> (pretty-print plist)'
                        ],
                        'notes': 'LaunchDaemons run at boot. LaunchAgents run at login',
                        'estimated_time': '30 seconds'
                    }
                },
                {
                    'id': f'macos-login-items-{target}',
                    'name': 'Enumerate Login Items',
                    'type': 'command',
                    'metadata': {
                        'command': f'ssh {target} "osascript -e \'tell application \"System Events\" to get the name of every login item\'"',
                        'description': 'List applications that run at user login',
                        'tags': ['OSCP:MEDIUM', 'PERSISTENCE', 'ENUM'],
                        'flag_explanations': {
                            'osascript': 'Execute AppleScript',
                            '-e': 'Execute command string',
                            'tell application "System Events"': 'Query System Events app',
                            'get the name of every login item': 'Retrieve all login items'
                        },
                        'success_indicators': [
                            'List of login item names',
                            'Applications that auto-start shown'
                        ],
                        'failure_indicators': [
                            'Permission denied (requires automation permissions)',
                            'Empty list',
                            'AppleScript error'
                        ],
                        'next_steps': [
                            'Identify suspicious login items',
                            'Check login item paths in ~/Library/Application Support/',
                            'Look for backdoor applications',
                            'Check /var/db/com.apple.xpc.launchd/loginitems.*.plist'
                        ],
                        'alternatives': [
                            'cat ~/Library/Application\\ Support/com.apple.backgroundtaskmanagementagent',
                            'ls -la ~/Library/Application\\ Support/',
                            'sfltool dumpbtm (background task management - requires root)'
                        ],
                        'notes': 'Login items visible in System Preferences > Users & Groups > Login Items',
                        'estimated_time': '20 seconds'
                    }
                },
                {
                    'id': f'macos-shell-profiles-{target}',
                    'name': 'Check Shell Startup Files',
                    'type': 'command',
                    'metadata': {
                        'command': f'ssh {target} "ls -la ~/.zshrc ~/.zlogin ~/.zshenv ~/.bashrc ~/.bash_profile ~/.profile 2>/dev/null"',
                        'description': 'Find shell initialization files (persistence via command injection)',
                        'tags': ['OSCP:HIGH', 'PERSISTENCE', 'QUICK_WIN'],
                        'flag_explanations': {
                            'ls -la': 'List with details (check modifications)',
                            '~/.zshrc': 'Zsh configuration (default shell)',
                            '~/.bashrc': 'Bash configuration',
                            '~/.profile': 'Generic shell profile',
                            '2>/dev/null': 'Suppress file not found errors'
                        },
                        'success_indicators': [
                            'List of shell profile files',
                            'Modification times shown',
                            'File sizes displayed'
                        ],
                        'failure_indicators': [
                            'No files found (unlikely)',
                            'Permission denied'
                        ],
                        'next_steps': [
                            'Read files: cat ~/.zshrc',
                            'Look for suspicious commands',
                            'Check for backdoors or reverse shells',
                            'Note recently modified files'
                        ],
                        'alternatives': [
                            'cat ~/.zshrc (read zsh config)',
                            'cat ~/.bashrc (read bash config)',
                            'grep -r "bash -i" ~/ 2>/dev/null (find reverse shells)'
                        ],
                        'notes': 'Shell profiles execute at login. Easy persistence method',
                        'estimated_time': '15 seconds'
                    }
                },
                {
                    'id': f'macos-cron-jobs-{target}',
                    'name': 'Check Cron Jobs',
                    'type': 'command',
                    'metadata': {
                        'command': f'ssh {target} "crontab -l 2>/dev/null && ls -la /usr/lib/cron/tabs/ /var/at/tabs/ /etc/periodic/ 2>/dev/null"',
                        'description': 'Enumerate scheduled tasks (persistence via cron)',
                        'tags': ['OSCP:MEDIUM', 'PERSISTENCE', 'ENUM'],
                        'flag_explanations': {
                            'crontab': 'User cron table',
                            '-l': 'List current user\'s cron jobs',
                            '/usr/lib/cron/tabs/': 'System cron job storage',
                            '/var/at/tabs/': 'at job storage',
                            '/etc/periodic/': 'Periodic scripts (daily, weekly, monthly)'
                        },
                        'success_indicators': [
                            'Cron jobs listed',
                            'Periodic directories shown',
                            'Scheduled tasks visible'
                        ],
                        'failure_indicators': [
                            'No crontab for user',
                            'Permission denied on system locations'
                        ],
                        'next_steps': [
                            'Examine periodic scripts in /etc/periodic/daily,weekly,monthly',
                            'Check for writable cron scripts',
                            'Look for suspicious scheduled tasks',
                            'Check at jobs: atq'
                        ],
                        'alternatives': [
                            'ls -lR /etc/periodic/ (list all periodic scripts)',
                            'cat /etc/crontab (system crontab)',
                            'sudo crontab -l -u root (root crontab)'
                        ],
                        'notes': 'Periodic scripts run by system launch daemons',
                        'estimated_time': '20 seconds'
                    }
                },
                {
                    'id': f'macos-ssh-keys-{target}',
                    'name': 'Check SSH Keys',
                    'type': 'command',
                    'metadata': {
                        'command': f'ssh {target} "ls -la ~/.ssh/ && cat ~/.ssh/authorized_keys 2>/dev/null"',
                        'description': 'Enumerate SSH keys (persistence and lateral movement)',
                        'tags': ['OSCP:HIGH', 'QUICK_WIN', 'PERSISTENCE'],
                        'flag_explanations': {
                            'ls -la ~/.ssh/': 'List SSH directory contents',
                            'cat ~/.ssh/authorized_keys': 'Show authorized public keys',
                            '2>/dev/null': 'Suppress errors if file missing'
                        },
                        'success_indicators': [
                            'SSH directory exists',
                            'Private keys present (id_rsa, id_ed25519)',
                            'Authorized keys listed',
                            'Known hosts file present'
                        ],
                        'failure_indicators': [
                            'Directory doesn\'t exist',
                            'Empty directory',
                            'Permission denied'
                        ],
                        'next_steps': [
                            'Download private keys if accessible',
                            'Check known_hosts for lateral movement targets',
                            'Review authorized_keys for backdoor keys',
                            'Try keys on other systems: ssh -i key user@host'
                        ],
                        'alternatives': [
                            'cat ~/.ssh/id_rsa (private key)',
                            'cat ~/.ssh/known_hosts (previous connections)',
                            'cat ~/.ssh/config (SSH client config)',
                            'find ~/.ssh/ -type f -exec file {} \\; (identify key types)'
                        ],
                        'notes': 'Private keys enable password-less access to other systems',
                        'estimated_time': '15 seconds'
                    }
                }
            ]
        })

        # Phase 6: Security Configuration
        tasks['children'].append({
            'id': f'macos-security-enum-{target}',
            'name': 'Security Configuration Enumeration',
            'type': 'parent',
            'children': [
                {
                    'id': f'macos-firewall-status-{target}',
                    'name': 'Check Firewall Status',
                    'type': 'command',
                    'metadata': {
                        'command': f'ssh {target} "system_profiler SPFirewallDataType"',
                        'description': 'Check macOS firewall configuration',
                        'tags': ['OSCP:MEDIUM', 'ENUM'],
                        'flag_explanations': {
                            'system_profiler': 'Report system configuration',
                            'SPFirewallDataType': 'Firewall data type'
                        },
                        'success_indicators': [
                            'Firewall status shown (enabled/disabled)',
                            'Firewall mode displayed',
                            'Allowed applications listed'
                        ],
                        'failure_indicators': [
                            'Permission denied',
                            'Timeout'
                        ],
                        'next_steps': [
                            'If disabled, less detection risk',
                            'Check which apps are allowed',
                            'Test blocked ports',
                            'Note stealth mode status'
                        ],
                        'alternatives': [
                            'sudo /usr/libexec/ApplicationFirewall/socketfilterfw --getglobalstate',
                            'sudo /usr/libexec/ApplicationFirewall/socketfilterfw --listapps'
                        ],
                        'notes': 'Firewall often disabled on internal networks',
                        'estimated_time': '30 seconds'
                    }
                },
                {
                    'id': f'macos-sip-status-{target}',
                    'name': 'Check System Integrity Protection (SIP)',
                    'type': 'command',
                    'metadata': {
                        'command': f'ssh {target} "csrutil status"',
                        'description': 'Check if System Integrity Protection is enabled',
                        'tags': ['OSCP:HIGH', 'QUICK_WIN', 'ENUM'],
                        'flag_explanations': {
                            'csrutil': 'Configure System Integrity Protection',
                            'status': 'Display SIP status'
                        },
                        'success_indicators': [
                            'SIP status displayed (enabled/disabled)',
                            'Configuration details shown'
                        ],
                        'failure_indicators': [
                            'Command not found (old macOS)',
                            'Error message'
                        ],
                        'next_steps': [
                            'If disabled, more exploitation options available',
                            'Check for SIP bypass techniques if enabled',
                            'Look for writable system directories'
                        ],
                        'alternatives': [
                            'nvram -p | grep csr-active-config (SIP config)',
                            'ls -lO /System/Library/ (check file flags)'
                        ],
                        'notes': 'SIP protects system files. Disabled = major security weakness',
                        'estimated_time': '10 seconds'
                    }
                },
                {
                    'id': f'macos-gatekeeper-status-{target}',
                    'name': 'Check Gatekeeper Status',
                    'type': 'command',
                    'metadata': {
                        'command': f'ssh {target} "spctl --status"',
                        'description': 'Check if Gatekeeper (app verification) is enabled',
                        'tags': ['OSCP:MEDIUM', 'QUICK_WIN', 'ENUM'],
                        'flag_explanations': {
                            'spctl': 'Security assessment policy tool',
                            '--status': 'Display Gatekeeper status'
                        },
                        'success_indicators': [
                            'Gatekeeper status shown (enabled/disabled)',
                            'Assessment enabled/disabled message'
                        ],
                        'failure_indicators': [
                            'Permission denied',
                            'Command not found'
                        ],
                        'next_steps': [
                            'If disabled, unsigned apps can run',
                            'Test app execution restrictions',
                            'Check for bypass techniques'
                        ],
                        'alternatives': [
                            'sudo spctl --master-disable (disable - requires root)',
                            'sudo spctl --master-enable (enable - requires root)'
                        ],
                        'notes': 'Gatekeeper blocks unsigned apps. Disabled = easier payload execution',
                        'estimated_time': '10 seconds'
                    }
                },
                {
                    'id': f'macos-kernel-extensions-{target}',
                    'name': 'List Loaded Kernel Extensions',
                    'type': 'command',
                    'metadata': {
                        'command': f'ssh {target} "kextstat | head -30"',
                        'description': 'List loaded kernel extensions (drivers)',
                        'tags': ['OSCP:MEDIUM', 'ENUM'],
                        'flag_explanations': {
                            'kextstat': 'Display status of loaded kernel extensions',
                            'head -30': 'Limit to first 30 entries'
                        },
                        'success_indicators': [
                            'List of loaded kexts',
                            'Version numbers shown',
                            'Reference counts displayed'
                        ],
                        'failure_indicators': [
                            'Permission denied',
                            'Empty output'
                        ],
                        'next_steps': [
                            'Identify third-party kexts (non-Apple)',
                            'Research vulnerable kext versions',
                            'Check kext locations: ls /Library/Extensions/',
                            'Look for security tool kexts (EDR, AV)'
                        ],
                        'alternatives': [
                            'kextstat | grep -v com.apple (non-Apple kexts)',
                            'ls -la /Library/Extensions/',
                            'kextfind -b <bundle-id> (find kext by ID)'
                        ],
                        'notes': 'Kernel extensions run with kernel privileges. Vulnerabilities = system compromise',
                        'estimated_time': '15 seconds'
                    }
                }
            ]
        })

        # Phase 7: Privilege Escalation Vectors
        tasks['children'].append({
            'id': f'macos-privesc-enum-{target}',
            'name': 'Privilege Escalation Enumeration',
            'type': 'parent',
            'children': [
                {
                    'id': f'macos-suid-binaries-{target}',
                    'name': 'Find SUID Binaries',
                    'type': 'command',
                    'metadata': {
                        'command': f'ssh {target} "find / -perm -u=s -type f 2>/dev/null | head -20"',
                        'description': 'Find SUID binaries (potential privilege escalation)',
                        'tags': ['OSCP:HIGH', 'PRIVESC', 'ENUM'],
                        'flag_explanations': {
                            'find': 'Search for files',
                            '/': 'Search from root directory',
                            '-perm -u=s': 'Find files with SUID bit set',
                            '-type f': 'Files only',
                            '2>/dev/null': 'Suppress permission errors',
                            'head -20': 'Limit to first 20 results'
                        },
                        'success_indicators': [
                            'List of SUID binaries',
                            'Paths to executables',
                            'Unusual binaries found'
                        ],
                        'failure_indicators': [
                            'Empty list',
                            'Permission denied on all paths'
                        ],
                        'next_steps': [
                            'Check each binary against GTFOBins',
                            'Test unusual SUID binaries',
                            'Look for custom SUID programs',
                            'Check binary versions for vulnerabilities'
                        ],
                        'alternatives': [
                            'find / -perm -4000 -type f 2>/dev/null',
                            'find / -user root -perm -4000 2>/dev/null'
                        ],
                        'notes': 'Cross-reference with https://gtfobins.github.io/ for exploitation',
                        'estimated_time': '1-2 minutes'
                    }
                },
                {
                    'id': f'macos-writable-paths-{target}',
                    'name': 'Find World-Writable Files and Directories',
                    'type': 'command',
                    'metadata': {
                        'command': f'ssh {target} "find / -perm -2 -type f 2>/dev/null | grep -v /proc | head -20"',
                        'description': 'Find world-writable files (potential for backdoors)',
                        'tags': ['OSCP:MEDIUM', 'PRIVESC', 'ENUM'],
                        'flag_explanations': {
                            'find': 'Search for files',
                            '/': 'Search from root',
                            '-perm -2': 'World-writable permission bit set',
                            '-type f': 'Files only',
                            'grep -v /proc': 'Exclude proc filesystem',
                            '2>/dev/null': 'Suppress errors'
                        },
                        'success_indicators': [
                            'List of writable files',
                            'Paths displayed',
                            'Interesting targets found'
                        ],
                        'failure_indicators': [
                            'No files found',
                            'Permission denied'
                        ],
                        'next_steps': [
                            'Check if writable files are executed by system',
                            'Look for cron scripts or launch daemons',
                            'Test modifying files for privilege escalation',
                            'Check for config files'
                        ],
                        'alternatives': [
                            'find / -perm -2 -type d 2>/dev/null (writable directories)',
                            'find /etc /usr /opt -perm -2 2>/dev/null (specific paths)'
                        ],
                        'notes': 'World-writable files in privileged locations = high risk',
                        'estimated_time': '1-2 minutes'
                    }
                },
                {
                    'id': f'macos-password-files-{target}',
                    'name': 'Search for Password Files',
                    'type': 'command',
                    'metadata': {
                        'command': f'ssh {target} "mdfind password | grep -v \'^/System\' | head -20"',
                        'description': 'Search for files containing "password" in name or content',
                        'tags': ['OSCP:HIGH', 'QUICK_WIN', 'ENUM'],
                        'flag_explanations': {
                            'mdfind': 'Spotlight search from command line',
                            'password': 'Search term',
                            'grep -v \'^/System\'': 'Exclude system directory',
                            'head -20': 'Limit results'
                        },
                        'success_indicators': [
                            'Files containing password references',
                            'Config files listed',
                            'Scripts or notes found'
                        ],
                        'failure_indicators': [
                            'No results',
                            'Indexing disabled'
                        ],
                        'next_steps': [
                            'Read each file for credentials',
                            'Search for other terms: mdfind credential',
                            'Check browser data: ~/Library/Application Support/Google/Chrome/',
                            'Look for .env files, config files'
                        ],
                        'alternatives': [
                            'mdfind -name password (filename only)',
                            'grep -r "password" /Users/$USER 2>/dev/null',
                            'find / -name "*password*" 2>/dev/null'
                        ],
                        'notes': 'Spotlight indexes content. Fast but may miss new files',
                        'estimated_time': '30 seconds'
                    }
                },
                {
                    'id': f'macos-environment-variables-{target}',
                    'name': 'Check Environment Variables',
                    'type': 'command',
                    'metadata': {
                        'command': f'ssh {target} "env && cat ~/.bash_history ~/.zsh_history 2>/dev/null | grep -i pass"',
                        'description': 'Check environment variables and command history for secrets',
                        'tags': ['OSCP:HIGH', 'QUICK_WIN', 'ENUM'],
                        'flag_explanations': {
                            'env': 'Display all environment variables',
                            'cat ~/.bash_history': 'Show bash command history',
                            'cat ~/.zsh_history': 'Show zsh command history',
                            'grep -i pass': 'Search for password references'
                        },
                        'success_indicators': [
                            'Environment variables displayed',
                            'Command history shown',
                            'Credentials or API keys found'
                        ],
                        'failure_indicators': [
                            'Empty history',
                            'History files don\'t exist'
                        ],
                        'next_steps': [
                            'Check for API keys in environment',
                            'Look for AWS credentials',
                            'Search history for passwords in commands',
                            'Check for database connection strings'
                        ],
                        'alternatives': [
                            'printenv (same as env)',
                            'history (current session history)',
                            'cat ~/.bash_profile | grep export'
                        ],
                        'notes': 'Developers often put secrets in env vars. Check history for cleartext passwords',
                        'estimated_time': '20 seconds'
                    }
                }
            ]
        })

        # Phase 8: Automated Enumeration Tools
        tasks['children'].append({
            'id': f'macos-auto-enum-{target}',
            'name': 'Automated Enumeration Tools',
            'type': 'parent',
            'children': [
                {
                    'id': f'macos-run-macpeas-{target}',
                    'name': 'Run MacPEAS',
                    'type': 'manual',
                    'metadata': {
                        'description': 'Run MacPEAS automated macOS enumeration tool',
                        'tags': ['OSCP:HIGH', 'AUTOMATED', 'ENUM'],
                        'alternatives': [
                            '# Download MacPEAS',
                            'curl -L https://github.com/carlospolop/PEASS-ng/releases/latest/download/linpeas.sh -o macpeas.sh',
                            '# Transfer to target',
                            'scp macpeas.sh {target}:/tmp/',
                            '# Execute on target',
                            'ssh {target} "chmod +x /tmp/macpeas.sh && /tmp/macpeas.sh"'
                        ],
                        'notes': 'MacPEAS performs comprehensive automated enumeration. Review output for privesc vectors',
                        'estimated_time': '5-10 minutes'
                    }
                },
                {
                    'id': f'macos-run-swiftbelt-{target}',
                    'name': 'Run SwiftBelt',
                    'type': 'manual',
                    'metadata': {
                        'description': 'Run SwiftBelt for macOS security enumeration',
                        'tags': ['OSCP:MEDIUM', 'AUTOMATED', 'ENUM'],
                        'alternatives': [
                            '# Clone SwiftBelt',
                            'git clone https://github.com/cedowens/SwiftBelt',
                            '# Build (requires Xcode)',
                            'cd SwiftBelt && swift build',
                            '# Transfer binary to target',
                            '# Execute on target',
                            './SwiftBelt'
                        ],
                        'notes': 'SwiftBelt checks: Running apps, network connections, security tools, Safari history, etc.',
                        'estimated_time': '2-3 minutes'
                    }
                },
                {
                    'id': f'macos-metasploit-enum-{target}',
                    'name': 'Metasploit macOS Enumeration Module',
                    'type': 'manual',
                    'metadata': {
                        'description': 'Use Metasploit post-exploitation enumeration for macOS',
                        'tags': ['OSCP:LOW', 'AUTOMATED', 'ENUM'],
                        'alternatives': [
                            '# In Metasploit (requires active session)',
                            'use post/osx/gather/enum_osx',
                            'set SESSION <session_id>',
                            'run',
                            '# Alternative modules:',
                            'use post/osx/gather/hashdump',
                            'use post/osx/gather/password_prompt_spoof'
                        ],
                        'notes': 'Requires Metasploit session. More common in red team operations than OSCP',
                        'estimated_time': '2-3 minutes'
                    }
                }
            ]
        })

        # === USER & ACCOUNT ENUMERATION ===
        user_enum = {
            'id': f'macos-user-enum-{target}',
            'name': 'macOS User & Account Enumeration',
            'type': 'parent',
            'children': []
        }

        # Standard users
        user_enum['children'].append({
            'id': f'macos-list-users-{target}',
            'name': 'List Local Users',
            'type': 'command',
            'metadata': {
                'command': f'ssh {target} "dscl . list /Users | grep -v \'^_\'"',
                'description': 'List non-daemon local users (excludes system accounts starting with _)',
                'tags': ['OSCP:HIGH', 'QUICK_WIN', 'MANUAL'],
                'flag_explanations': {
                    'dscl': 'Directory Services command line utility',
                    '. list /Users': 'List all users in local directory',
                    'grep -v \'^_\'': 'Exclude daemon accounts (start with underscore)'
                },
                'success_indicators': [
                    'User list displayed',
                    'Standard users visible (not starting with _)',
                    'Admin users potentially identified'
                ],
                'failure_indicators': [
                    'Permission denied',
                    'Empty output (unlikely)'
                ],
                'next_steps': [
                    'Check which users are admins: dscl . -read /Groups/admin GroupMembership',
                    'Enumerate user home directories',
                    'Check for user privileges and sudo access'
                ],
                'alternatives': [
                    'dscacheutil -q user',
                    'ls /Users',
                    'cat /etc/passwd (limited on macOS)',
                    'id -u <username> (check specific user)'
                ],
                'notes': 'macOS daemon accounts start with _ (like _www, _postgres). Standard users: standard, admin, root. Guest account may be enabled.',
                'estimated_time': '10 seconds'
            }
        })

        # Daemon accounts
        user_enum['children'].append({
            'id': f'macos-daemon-accounts-{target}',
            'name': 'Enumerate Daemon Accounts',
            'type': 'command',
            'metadata': {
                'command': f'ssh {target} "dscl . list /Users | grep \'^_\' | head -20"',
                'description': 'List system daemon accounts (for process analysis)',
                'tags': ['OSCP:MEDIUM', 'ENUM'],
                'flag_explanations': {
                    'grep \'^_\'': 'Show only accounts starting with underscore (daemons)',
                    'head -20': 'Limit output to first 20 (many daemon accounts exist)'
                },
                'success_indicators': [
                    'Daemon accounts listed (_www, _postgres, _mysql, _ftp, etc.)',
                    'Service accounts visible'
                ],
                'failure_indicators': [
                    'Permission denied'
                ],
                'next_steps': [
                    'Correlate daemon accounts with running services',
                    'Check for unusual daemon accounts (potential persistence)',
                    'Map daemons to exploit opportunities'
                ],
                'alternatives': [
                    'dscacheutil -q user | grep "^name: _"',
                    'ps aux | grep "^_" (show running daemon processes)'
                ],
                'notes': 'Common daemons: _www (web), _mysql, _postgres, _sshd, _postfix, _cyrus (mail). Custom daemons may indicate installed services.',
                'estimated_time': '10 seconds'
            }
        })

        # Admin group
        user_enum['children'].append({
            'id': f'macos-admin-users-{target}',
            'name': 'Identify Admin Users',
            'type': 'command',
            'metadata': {
                'command': f'ssh {target} "dscl . -read /Groups/admin GroupMembership"',
                'description': 'List users with admin privileges (can sudo)',
                'tags': ['OSCP:HIGH', 'QUICK_WIN', 'MANUAL'],
                'flag_explanations': {
                    '-read /Groups/admin': 'Read admin group properties',
                    'GroupMembership': 'Show members of the admin group'
                },
                'success_indicators': [
                    'Admin users listed',
                    'Root always present',
                    'Standard admin users identified'
                ],
                'failure_indicators': [
                    'Permission denied',
                    'Group not found (unlikely)'
                ],
                'next_steps': [
                    'Target admin users for credential theft',
                    'Check sudo configuration: sudo -l',
                    'Review admin user home directories for sensitive files'
                ],
                'alternatives': [
                    'dseditgroup -o read admin',
                    'dscl . -read /Users/<username> | grep PrimaryGroupID (500 = admin on macOS)',
                    'groups <username> (check user group membership)'
                ],
                'notes': 'Admin users can run sudo and install software. All admin group members have sudoers file access.',
                'estimated_time': '10 seconds'
            }
        })

        # Guest account status
        user_enum['children'].append({
            'id': f'macos-guest-status-{target}',
            'name': 'Check Guest Account Status',
            'type': 'command',
            'metadata': {
                'command': f'ssh {target} "sysadminctl -guestAccount status"',
                'description': 'Check if guest account is enabled (low-privilege access)',
                'tags': ['OSCP:MEDIUM', 'QUICK_WIN', 'MANUAL'],
                'flag_explanations': {
                    'sysadminctl': 'System administration utility',
                    '-guestAccount status': 'Query guest account state'
                },
                'success_indicators': [
                    'Guest account enabled/disabled shown',
                    'Status clearly reported'
                ],
                'failure_indicators': [
                    'Command requires admin privileges',
                    'Tool not available'
                ],
                'next_steps': [
                    'If enabled: test guest login via GUI or VNC',
                    'Check guest account restrictions',
                    'Enumerate other security features'
                ],
                'alternatives': [
                    'Manual: System Preferences > Users & Groups > Guest User',
                    'dscl . -read /Users/Guest (check guest user properties)',
                    'Check afpGuestAccess: sysadminctl -afpGuestAccess status'
                ],
                'notes': 'Guest accounts have strict permissions but may provide foothold. AFP/SMB guest access is separate.',
                'estimated_time': '5 seconds'
            }
        })

        # External accounts
        user_enum['children'].append({
            'id': f'macos-external-accounts-{target}',
            'name': 'Enumerate External Account Providers',
            'type': 'command',
            'metadata': {
                'command': f'ssh {target} "cat /Library/Preferences/SystemConfiguration/com.apple.accounts.exists.plist 2>/dev/null"',
                'description': 'Check for external authentication providers (Google, Facebook, etc.)',
                'tags': ['OSCP:LOW', 'ENUM'],
                'flag_explanations': {
                    'com.apple.accounts.exists.plist': 'System configuration for account types',
                    '2>/dev/null': 'Suppress errors if file missing'
                },
                'success_indicators': [
                    'Plist file exists and readable',
                    'Account types listed',
                    'External providers configured'
                ],
                'failure_indicators': [
                    'File not found',
                    'Permission denied',
                    'Empty configuration'
                ],
                'next_steps': [
                    'Check for OAuth tokens in Keychain',
                    'Review authentication plugins in /System/Library/Accounts/Authentication/',
                    'Examine accountsd daemon activity'
                ],
                'alternatives': [
                    'plutil -p /Library/Preferences/SystemConfiguration/com.apple.accounts.exists.plist',
                    'ls /System/Library/Accounts/Authentication/ (list auth plugins)',
                    'ps aux | grep accountsd (check if running)'
                ],
                'notes': 'External accounts managed by accountsd daemon. Plugins in /System/Library/Accounts/Authentication/. May contain OAuth tokens.',
                'estimated_time': '10 seconds'
            }
        })

        # User privileges summary
        user_enum['children'].append({
            'id': f'macos-user-privs-{target}',
            'name': 'Check Current User Privileges',
            'type': 'command',
            'metadata': {
                'command': f'ssh {target} "id && groups && sudo -l 2>/dev/null"',
                'description': 'Check current user identity, groups, and sudo permissions',
                'tags': ['OSCP:HIGH', 'QUICK_WIN', 'MANUAL'],
                'flag_explanations': {
                    'id': 'Show user ID, group ID, and group membership',
                    'groups': 'List all groups for current user',
                    'sudo -l': 'List sudo permissions (commands user can run as root)'
                },
                'success_indicators': [
                    'User ID and groups displayed',
                    'Sudo permissions listed (if any)',
                    'Admin group membership visible'
                ],
                'failure_indicators': [
                    'sudo -l returns no permissions',
                    'Permission denied'
                ],
                'next_steps': [
                    'If admin: full privesc via sudo',
                    'If standard user: look for SUID binaries, writable services, etc.',
                    'Check for sudo misconfigurations'
                ],
                'alternatives': [
                    'whoami (just username)',
                    'id -u (numeric UID)',
                    'dscl . -read /Users/$(whoami) (full user properties)'
                ],
                'notes': 'Admin users (uid 501+, admin group) have sudo. Standard users have limited privileges. Root is uid 0.',
                'estimated_time': '10 seconds'
            }
        })

        tasks['children'].append(user_enum)

        # === DEFENSIVE SOFTWARE DETECTION ===
        defensive_detect = {
            'id': f'macos-defensive-apps-{target}',
            'name': 'Defensive Software Detection',
            'type': 'parent',
            'children': []
        }

        # Firewall detection
        defensive_detect['children'].append({
            'id': f'macos-firewall-detect-{target}',
            'name': 'Detect Installed Firewalls',
            'type': 'command',
            'metadata': {
                'command': f'ssh {target} "ls -la /Applications | grep -iE \'little.*snitch|lulu|vallum|hands.*off|radio.*silence\'"',
                'description': 'Detect third-party firewall applications',
                'tags': ['OSCP:HIGH', 'QUICK_WIN', 'ENUM'],
                'flag_explanations': {
                    'grep -iE': 'Case-insensitive extended regex',
                    'little.*snitch': 'Little Snitch (popular commercial firewall)',
                    'lulu': 'LuLu (Objective-See free firewall)',
                    'vallum': 'Vallum (application firewall)',
                    'hands.*off': 'Hands Off! (network monitor)',
                    'radio.*silence': 'Radio Silence (outbound firewall)'
                },
                'success_indicators': [
                    'Firewall apps listed',
                    'Installation directories visible',
                    'Version info in app bundle'
                ],
                'failure_indicators': [
                    'No firewalls found',
                    'Permission denied on /Applications'
                ],
                'next_steps': [
                    'If Little Snitch: check rules in ~/Library/Application Support/Little Snitch/',
                    'If LuLu: check rules in ~/Library/Preferences/com.objective-see.lulu.plist',
                    'Identify allowed/blocked connections',
                    'Plan firewall bypass strategy'
                ],
                'alternatives': [
                    'mdfind "kMDItemKind == Application" | grep -i firewall',
                    'system_profiler SPApplicationsDataType | grep -i firewall',
                    'ps aux | grep -iE "little.*snitch|lulu" (check if running)'
                ],
                'notes': 'Little Snitch: expensive, feature-rich GUI. LuLu: free, basic alerts. Both monitor outbound connections. Bypass: use Apple-signed binaries or whitelisted domains.',
                'estimated_time': '10 seconds'
            }
        })

        # Persistence detection tools
        defensive_detect['children'].append({
            'id': f'macos-persistence-detect-tools-{target}',
            'name': 'Detect Persistence Monitoring Tools',
            'type': 'command',
            'metadata': {
                'command': f'ssh {target} "ls -la /Applications | grep -iE \'knockknock|blockblock|oversight|ransomwhere\'"',
                'description': 'Detect Objective-See security tools for persistence detection',
                'tags': ['OSCP:MEDIUM', 'ENUM'],
                'flag_explanations': {
                    'knockknock': 'One-shot persistence scanner',
                    'blockblock': 'Real-time persistence monitor',
                    'oversight': 'Microphone/camera monitor',
                    'ransomwhere': 'Ransomware detector'
                },
                'success_indicators': [
                    'Security tools found',
                    'Objective-See apps listed',
                    'Monitoring tools active'
                ],
                'failure_indicators': [
                    'No security tools found',
                    'Permission denied'
                ],
                'next_steps': [
                    'Avoid common persistence locations if BlockBlock detected',
                    'Use alternative persistence methods',
                    'Check tool configuration for whitelisted paths',
                    'Consider disabling tools if admin access obtained'
                ],
                'alternatives': [
                    'mdfind "kMDItemCFBundleIdentifier == com.objective-see.*"',
                    r'ps aux | grep -i "blockblock\|knockknock\|oversight"',
                    'ls /Library/LaunchDaemons/ | grep objective-see'
                ],
                'notes': 'BlockBlock monitors persistence creation in real-time. KnockKnock is one-shot scan. All by Objective-See (free). Alert user on suspicious activity.',
                'estimated_time': '10 seconds'
            }
        })

        # Keylogger detection
        defensive_detect['children'].append({
            'id': f'macos-keylogger-detect-tools-{target}',
            'name': 'Detect Keylogger Detection Tools',
            'type': 'command',
            'metadata': {
                'command': f'ssh {target} "ls -la /Applications | grep -iE \'reikey|key.*monitor\'"',
                'description': 'Detect tools that find keyboard event taps (keyloggers)',
                'tags': ['OSCP:LOW', 'ENUM'],
                'flag_explanations': {
                    'reikey': 'ReiKey (Objective-See) - detects keyboard event taps',
                    'key.*monitor': 'Generic keylogger monitors'
                },
                'success_indicators': [
                    'ReiKey or similar found',
                    'Keylogger detection active'
                ],
                'failure_indicators': [
                    'No detection tools found',
                    'Permission denied'
                ],
                'next_steps': [
                    'Avoid installing keyboard event taps',
                    'Use alternative credential theft (memory dumps, keychain)',
                    'Check if ReiKey alerts user to your activity'
                ],
                'alternatives': [
                    'mdfind "kMDItemDisplayName == *ReiKey*"',
                    'ps aux | grep -i reikey',
                    'ioreg -l | grep kCGEventTapDidBecomeTap (manual check for event taps)'
                ],
                'notes': 'ReiKey detects CGEventTap API usage. Alternative: use Accessibility API or memory scraping for credentials.',
                'estimated_time': '10 seconds'
            }
        })

        # EDR/AV detection
        defensive_detect['children'].append({
            'id': f'macos-edr-av-detect-{target}',
            'name': 'Detect EDR/Antivirus Software',
            'type': 'command',
            'metadata': {
                'command': f'ssh {target} "ls -la /Applications | grep -iE \'sentinel|crowdstrike|carbon.*black|cylance|sophos|kaspersky|avast|avg|bitdefender\'"',
                'description': 'Detect enterprise EDR and consumer antivirus',
                'tags': ['OSCP:HIGH', 'ENUM'],
                'flag_explanations': {
                    'sentinel': 'SentinelOne EDR',
                    'crowdstrike': 'CrowdStrike Falcon EDR',
                    'carbon.*black': 'VMware Carbon Black',
                    'cylance': 'BlackBerry Cylance',
                    'sophos|kaspersky|avast|avg|bitdefender': 'Common AV products'
                },
                'success_indicators': [
                    'EDR/AV products found',
                    'Security agents detected',
                    'Enterprise protection visible'
                ],
                'failure_indicators': [
                    'No security software found',
                    'Only built-in XProtect present'
                ],
                'next_steps': [
                    'Research EDR/AV bypass techniques for detected product',
                    'Avoid file-based execution (use memory-only)',
                    'Use Apple-signed binaries where possible',
                    'Check for exclusions and whitelisted paths'
                ],
                'alternatives': [
                    'ps aux | grep -iE "sentinel|falcon|cb|cylance" (check running processes)',
                    'ls /Library/LaunchDaemons/ | grep -iE "sentinel|crowdstrike"',
                    r'system_profiler SPApplicationsDataType | grep -i "security\|antivirus"'
                ],
                'notes': 'XProtect is built-in (basic). Gatekeeper checks signatures. EDR = advanced detection. Consumer AV = signature-based. Enterprise macs often have SentinelOne or CrowdStrike.',
                'estimated_time': '15 seconds'
            }
        })

        # Built-in protections status
        defensive_detect['children'].append({
            'id': f'macos-builtin-protections-{target}',
            'name': 'Check Built-in Security Features',
            'type': 'command',
            'metadata': {
                'command': f'ssh {target} "csrutil status; spctl --status; /usr/libexec/ApplicationFirewall/socketfilterfw --getglobalstate"',
                'description': 'Check SIP, Gatekeeper, and Application Firewall status',
                'tags': ['OSCP:HIGH', 'QUICK_WIN', 'MANUAL'],
                'flag_explanations': {
                    'csrutil status': 'System Integrity Protection (SIP) status',
                    'spctl --status': 'Gatekeeper (app verification) status',
                    'socketfilterfw --getglobalstate': 'Application Firewall enabled/disabled'
                },
                'success_indicators': [
                    'SIP enabled/disabled clearly shown',
                    'Gatekeeper status visible',
                    'Firewall state reported'
                ],
                'failure_indicators': [
                    'Commands require elevated privileges',
                    'Tools not available'
                ],
                'next_steps': [
                    'If SIP disabled: kernel-level attacks possible',
                    'If Gatekeeper disabled: unsigned apps can run',
                    'If firewall off: network access unrestricted',
                    'Plan exploitation based on security posture'
                ],
                'alternatives': [
                    'nvram -p | grep "csr-active-config" (SIP via NVRAM)',
                    'spctl --assess --verbose /Applications/App.app (test specific app)',
                    'defaults read /Library/Preferences/com.apple.alf globalstate (firewall plist)'
                ],
                'notes': 'SIP protects system files. Gatekeeper checks code signatures. App Firewall = basic outbound control. All can be bypassed with proper techniques.',
                'estimated_time': '10 seconds'
            }
        })

        tasks['children'].append(defensive_detect)

        return tasks
